/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CallHistoryNodePanel.java
 *
 * Created on 2011-9-23, 15:35:38
 */
package com.lorent.vovo.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;

import org.apache.log4j.Logger;

import com.lorent.vovo.Vovo;
import com.lorent.vovo.util.Constants;

/**
 *
 * @author Administrator
 */
public class CallHistoryNodePanel extends javax.swing.JPanel {

    private static Logger log = Logger.getLogger(CallHistoryNodePanel.class);
    private int callHistoryState ;
    private String callHistoryText;
    private String callHistoryTime;
    private int id;

    public int getId() {
        return id;
    }

    
    public void setInfo(int callHistoryState,String callHistoryText,String callHistoryTime,int id){
        this.callHistoryState = callHistoryState;
        this.callHistoryText = callHistoryText;
        this.callHistoryTime = callHistoryTime;
        this.id = id;
        if (callHistoryState == Constants.CALLHISTORY_CALL_OUT) {
            callStateLabel.setIcon(new ImageIcon(getClass().getResource("/com/lorent/vovo/resource/images/dial/dial_state_callout1.png")));
        }
        else if(callHistoryState == Constants.CALLHISTORY_CALL_IN){
            callStateLabel.setIcon(new ImageIcon(getClass().getResource("/com/lorent/vovo/resource/images/dial/dial_state_callin1.png")));
        }else if(callHistoryState == Constants.CALLHISTORY_CALL_IN_NOT_LISTEN){
            callStateLabel.setIcon(new ImageIcon(getClass().getResource("/com/lorent/vovo/resource/images/dial/edit-undo-6.png")));
        }
        textLabel.setText(callHistoryText);
        timeJLabel.setText(callHistoryTime);
    }

    public String getCallHistoryTime() {
        return callHistoryTime;
    }
    
    public int getCallHistoryState() {
        return callHistoryState;
    }

    public String getCallHistoryText() {
        return callHistoryText;
    }
    
    /** Creates new form CallHistoryNodePanel */
    public CallHistoryNodePanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        topJPanel = new javax.swing.JPanel();
        callStateLabel = new javax.swing.JLabel();
        textLabel = new javax.swing.JLabel();
        bottumJPanel = new javax.swing.JPanel();
        timeJLabel = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        topJPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        callStateLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lorent/vovo/resource/images/head/treenode_head_online.png"))); // NOI18N
        topJPanel.add(callStateLabel);
        topJPanel.add(textLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        add(topJPanel, gridBagConstraints);

        bottumJPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        bottumJPanel.add(timeJLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        add(bottumJPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getTextLabel() {
        return textLabel;
    }//GEN-LAST:event_formMouseExited
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottumJPanel;
    private javax.swing.JLabel callStateLabel;
    private javax.swing.JLabel textLabel;
    private javax.swing.JLabel timeJLabel;
    private javax.swing.JPanel topJPanel;
    // End of variables declaration//GEN-END:variables

    public JPanel getBottumJPanel() {
        return bottumJPanel;
    }

    public void setBottumJPanel(JPanel bottumJPanel) {
        this.bottumJPanel = bottumJPanel;
    }

    public JPanel getTopJPanel() {
        return topJPanel;
    }

    public void setTopJPanel(JPanel topJPanel) {
        this.topJPanel = topJPanel;
    }
    
}
