/*
 * CameraHeadImgDialog.java
 *
 * Created on __DATE__, __TIME__
 */

package com.lorent.vovo.ui;

import java.awt.image.BufferedImage;

import javax.swing.JOptionPane;

import com.lorent.common.util.FmjUtil;
import com.lorent.vovo.Vovo;
import com.lorent.vovo.util.VovoStringUtil;

/**
 *
 * @author  __USER__
 */
public class CameraHeadImgDialog extends javax.swing.JDialog {

	private FmjUtil fmj = null;
	private BufferedImage image;

	public BufferedImage getPhone() {
		return image;
	}

	/** Creates new form CameraHeadImgDialog */
	public CameraHeadImgDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		this.saveButton.setVisible(false);
		this.repeatPhoneButton.setVisible(false);
		try {
			fmj = new FmjUtil();
			int flag = fmj.start(cameraPanel);
			if(flag != 0){
				this.setVisible(false);
				JOptionPane.showMessageDialog(null, VovoStringUtil.getErrorString("camera.isnot.normal"), VovoStringUtil.getErrorString("error.normal.tip"), JOptionPane.ERROR_MESSAGE);
			}
		} catch (Exception ex) {
			ex.printStackTrace();
		}

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		cameraPanel = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		takePhoneButton = new javax.swing.JButton();
		saveButton = new javax.swing.JButton();
		repeatPhoneButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle(Vovo.getMyContext().getViewManager().getUIString(
				"ChangeHeadImgDialog.camera.image"));
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				formWindowClosing(evt);
			}
		});

		javax.swing.GroupLayout cameraPanelLayout = new javax.swing.GroupLayout(
				cameraPanel);
		cameraPanel.setLayout(cameraPanelLayout);
		cameraPanelLayout.setHorizontalGroup(cameraPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 400, Short.MAX_VALUE));
		cameraPanelLayout.setVerticalGroup(cameraPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 267, Short.MAX_VALUE));

		getContentPane().add(cameraPanel, java.awt.BorderLayout.CENTER);

		jPanel2.setOpaque(false);

		takePhoneButton.setText(Vovo.getMyContext().getViewManager()
				.getUIString("CameraHeadImgDialog.takephone.txt"));
		takePhoneButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				takePhoneButtonActionPerformed(evt);
			}
		});
		jPanel2.add(takePhoneButton);

		saveButton.setText(Vovo.getMyContext().getViewManager().getUIString(
				"CameraHeadImgDialog.savephone.txt"));
		saveButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				saveButtonActionPerformed(evt);
			}
		});
		jPanel2.add(saveButton);

		repeatPhoneButton.setText(Vovo.getMyContext().getViewManager()
				.getUIString("CameraHeadImgDialog.repeatphone.txt"));
		repeatPhoneButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						repeatPhoneButtonActionPerformed(evt);
					}
				});
		jPanel2.add(repeatPhoneButton);

		getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private java.util.concurrent.LinkedBlockingQueue<SavePhoneListener> savePhoneQueue = new java.util.concurrent.LinkedBlockingQueue<SavePhoneListener>();

	public interface SavePhoneListener {
		void doAction();
	}

	public void addSavePhoneListener(SavePhoneListener listener) {
		savePhoneQueue.offer(listener);
	}

	private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {
		for (SavePhoneListener listener : savePhoneQueue) {
			listener.doAction();
		}
		this.setVisible(false);
	}

	private void formWindowClosing(java.awt.event.WindowEvent evt) {
		fmj.closeCamera();
	}

	private void repeatPhoneButtonActionPerformed(java.awt.event.ActionEvent evt) {
		fmj.repeatPhone();
		this.takePhoneButton.setVisible(true);
		this.saveButton.setVisible(false);
		this.repeatPhoneButton.setVisible(false);
	}

	private void takePhoneButtonActionPerformed(java.awt.event.ActionEvent evt) {
		image = fmj.takePhone();
		this.takePhoneButton.setVisible(false);
		this.saveButton.setVisible(true);
		this.repeatPhoneButton.setVisible(true);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				CameraHeadImgDialog dialog = new CameraHeadImgDialog(
						new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JPanel cameraPanel;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JButton repeatPhoneButton;
	private javax.swing.JButton saveButton;
	private javax.swing.JButton takePhoneButton;
	// End of variables declaration//GEN-END:variables

}