/*
 * ChangeHeadImgDialog.java
 *
 * Created on __DATE__, __TIME__
 */

package com.lorent.vovo.ui;

import java.awt.image.BufferedImage;
import java.io.File;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JFileChooser;

import org.jdesktop.swingx.painter.ImagePainter;
import org.jdesktop.swingx.painter.ImagePainter.ScaleType;

import com.lorent.common.dto.VovoMyInfo;
import com.lorent.vovo.Vovo;
import com.lorent.vovo.ui.CustomHeadOperatePanel.MouseReleaseListener;
import com.lorent.vovo.ui.HeadSampleImgPanel.HeadSampleImgPanelMouseClickListener;
import com.lorent.vovo.util.Constants;
import com.lorent.vovo.util.DataUtil;
import com.lorent.vovo.util.ImageUtil;
import com.lorent.vovo.util.PicScale;

/**
 *
 * @author  __USER__
 */
public class ChangeHeadImgDialog extends javax.swing.JDialog {

	private UserSettingDialog settingDialog;
	private BufferedImage resultImage;

	/** Creates new form ChangeHeadImgDialog */
	public ChangeHeadImgDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		imgListPanel.removeAll();
		jScrollPane1.getViewport().setOpaque(false);
		BufferedImage backgroundimg = Vovo.getMyContext().getDataManager()
				.getValue(
						Constants.DataKey.BACKGROUND_GAUSSIAN_IMAGE.toString());
		ImagePainter ip = new ImagePainter(backgroundimg);
		//			ip.setScaleToFit(true);
		ip.setScaleType(ScaleType.Distort);
		//			this.bannerPanel.setBackgroundPainter(ip);
		jXPanel1.setBackgroundPainter(ip);
		BufferedImage whiteImage = Vovo.getMyContext().getDataManager()
				.getValue(Constants.DataKey.WHITE_IMAGE.toString());
		ImagePainter ip2 = new ImagePainter(whiteImage);
		ip2.setScaleToFit(true);
		ip2.setScaleType(ScaleType.Distort);
		backgroundXPanel.setBackgroundPainter(ip2);

		HeadImgRawPanel rawPanel = null;
		int i = 0;
		//		Map<String, ImageIcon> map = loadSystemHeadImg();
		//		Set<String> keys = map.keySet();
		List<String> list = loadSystemHeadImg();
		HeadSampleImgPanelMouseClickListener listener = new HeadSampleImgPanelMouseClickListener() {
			@Override
			public void doAction(String fileName) {
				setPreviewLabelImg(fileName);
			}

		};
		for (String key : list) {
			i++;
			if (i % 4 == 1) {
				rawPanel = new HeadImgRawPanel();
				imgListPanel.add(rawPanel);
			}
			HeadSampleImgPanel imgPanel = new HeadSampleImgPanel(key);
			imgPanel.setMouseClickListener(listener);
			rawPanel.addHeadSampleImgPanel(imgPanel);
		}

		VovoMyInfo vovoMyInfo = DataUtil.getMyInfo();
		ImageUtil.adjustLabelIcon(this.previewLabel, vovoMyInfo);

	}

	public ChangeHeadImgDialog(java.awt.Frame parent, boolean modal,
			UserSettingDialog settingDialog) {
		this(parent, modal);
		this.settingDialog = settingDialog;
	}

	public List<String> loadSystemHeadImg() {
		List<String> list = new ArrayList<String>();
		for (int i = 1; i < 1000; i++) {
			String filename = "head_" + i + ".jpg";
			URL url = this.getClass().getResource(
					Constants.SYSTEM_HEAD_IMAGE_PATH_SYS + filename);
			if (url == null) {
				break;
			} else {
				list.add(filename);
			}
		}
		return list;
	}

	/*private Map<String, ImageIcon> loadSystemHeadImg() {
		Map<String, ImageIcon> map = new HashMap<String, ImageIcon>();
		for (int i = 1; i < 1000; i++) {
			String filename = "head_" + i + ".jpg";
			URL url = this.getClass().getResource(
					Constants.SYSTEM_HEAD_IMAGE_PATH_SYS + filename);
			if (url == null) {
				break;
			} else {
				ImageIcon icon = new ImageIcon(url);
				map.put(filename, icon);
			}
		}
		return map;
	}*/

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		jXPanel1 = new org.jdesktop.swingx.JXPanel();
		backgroundXPanel = new org.jdesktop.swingx.JXPanel();
		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jPanel5 = new javax.swing.JPanel();
		jPanel11 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jPanel12 = new javax.swing.JPanel();
		previewLabel = new javax.swing.JLabel();
		jPanel13 = new javax.swing.JPanel();
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel4 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		imgListPanel = new javax.swing.JPanel();
		jPanel7 = new javax.swing.JPanel();
		jPanel8 = new javax.swing.JPanel();
		jPanel9 = new javax.swing.JPanel();
		jPanel6 = new javax.swing.JPanel();
		jPanel10 = new javax.swing.JPanel();
		jButton3 = new javax.swing.JButton();
		customerImgPanel = new javax.swing.JPanel();
		jPanel3 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle(Vovo.getMyContext().getViewManager().getUIString(
				"UserSettingDialog.changeUserLogo"));
		setResizable(false);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				formWindowClosing(evt);
			}
		});

		jXPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 430));
		jXPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
		jXPanel1.setOpaque(false);
		jXPanel1.setPreferredSize(new java.awt.Dimension(450, 370));
		jXPanel1.setLayout(new java.awt.BorderLayout());

		backgroundXPanel
				.setMaximumSize(new java.awt.Dimension(2147483647, 430));
		backgroundXPanel.setMinimumSize(new java.awt.Dimension(0, 0));
		backgroundXPanel.setOpaque(false);
		backgroundXPanel.setPreferredSize(new java.awt.Dimension(450, 370));
		backgroundXPanel.setLayout(new java.awt.GridBagLayout());

		jPanel1.setMaximumSize(new java.awt.Dimension(32767, 20));
		jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
		jPanel1.setOpaque(false);
		jPanel1.setPreferredSize(new java.awt.Dimension(100, 0));
		jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2,
				2));

		jLabel2.setText(Vovo.getMyContext().getViewManager().getUIString(
				"ChangeHeadImgDialog.selectimg.txt"));
		jPanel1.add(jLabel2);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		backgroundXPanel.add(jPanel1, gridBagConstraints);

		jPanel2.setMaximumSize(new java.awt.Dimension(2147483647, 380));
		jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));
		jPanel2.setOpaque(false);
		jPanel2.setPreferredSize(new java.awt.Dimension(450, 340));
		jPanel2.setLayout(new java.awt.BorderLayout());

		jPanel5.setMaximumSize(new java.awt.Dimension(2147483647, 380));
		jPanel5.setOpaque(false);
		jPanel5.setLayout(new java.awt.GridBagLayout());

		jPanel11.setMaximumSize(new java.awt.Dimension(32767, 25));
		jPanel11.setOpaque(false);
		jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT,
				10, 5));

		jLabel1.setText(Vovo.getMyContext().getViewManager().getUIString(
				"UserSettingDialog.preview.txt"));
		jPanel11.add(jLabel1);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		jPanel5.add(jPanel11, gridBagConstraints);

		jPanel12.setMaximumSize(new java.awt.Dimension(2147483647, 110));
		jPanel12.setMinimumSize(new java.awt.Dimension(115, 115));
		jPanel12.setOpaque(false);
		jPanel12.setPreferredSize(new java.awt.Dimension(115, 115));

		previewLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		previewLabel
				.setIcon(new javax.swing.ImageIcon(
						getClass()
								.getResource(
										"/com/lorent/vovo/resource/images/systemheads/sys/head_1.jpg"))); // NOI18N
		previewLabel.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(204, 204, 204)));
		previewLabel
				.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		previewLabel.setIconTextGap(0);
		previewLabel.setMaximumSize(new java.awt.Dimension(100, 100));
		previewLabel.setMinimumSize(new java.awt.Dimension(100, 100));
		previewLabel.setPreferredSize(new java.awt.Dimension(100, 100));

		javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(
				jPanel12);
		jPanel12.setLayout(jPanel12Layout);
		jPanel12Layout.setHorizontalGroup(jPanel12Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel12Layout.createSequentialGroup().addContainerGap()
						.addComponent(previewLabel,
								javax.swing.GroupLayout.PREFERRED_SIZE, 100,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));
		jPanel12Layout.setVerticalGroup(jPanel12Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel12Layout.createSequentialGroup().addContainerGap(
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(previewLabel,
								javax.swing.GroupLayout.PREFERRED_SIZE, 100,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		jPanel5.add(jPanel12, gridBagConstraints);

		jPanel13.setMaximumSize(new java.awt.Dimension(32767, 310));
		jPanel13.setOpaque(false);

		javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(
				jPanel13);
		jPanel13.setLayout(jPanel13Layout);
		jPanel13Layout.setHorizontalGroup(jPanel13Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 115,
				Short.MAX_VALUE));
		jPanel13Layout.setVerticalGroup(jPanel13Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 200,
				Short.MAX_VALUE));

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 1.0;
		jPanel5.add(jPanel13, gridBagConstraints);

		jPanel2.add(jPanel5, java.awt.BorderLayout.EAST);

		jTabbedPane1.setPreferredSize(new java.awt.Dimension(0, 0));

		jPanel4.setMaximumSize(new java.awt.Dimension(2147483647, 380));
		jPanel4.setOpaque(false);
		jPanel4.setLayout(new java.awt.BorderLayout());

		jScrollPane1.setBorder(null);
		jScrollPane1
				.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
		jScrollPane1.setMaximumSize(new java.awt.Dimension(32767, 380));
		jScrollPane1.setOpaque(false);

		imgListPanel.setMaximumSize(new java.awt.Dimension(280, 330));
		imgListPanel.setMinimumSize(new java.awt.Dimension(280, 0));
		imgListPanel.setOpaque(false);
		imgListPanel.setPreferredSize(new java.awt.Dimension(280, 0));
		imgListPanel.setLayout(new javax.swing.BoxLayout(imgListPanel,
				javax.swing.BoxLayout.Y_AXIS));

		jPanel7.setMaximumSize(new java.awt.Dimension(32767, 14));
		jPanel7.setPreferredSize(new java.awt.Dimension(14, 14));

		javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(
				jPanel7);
		jPanel7.setLayout(jPanel7Layout);
		jPanel7Layout.setHorizontalGroup(jPanel7Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 386,
				Short.MAX_VALUE));
		jPanel7Layout.setVerticalGroup(jPanel7Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 14,
				Short.MAX_VALUE));

		imgListPanel.add(jPanel7);

		jPanel8.setMaximumSize(new java.awt.Dimension(32767, 14));
		jPanel8.setPreferredSize(new java.awt.Dimension(100, 14));

		javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(
				jPanel8);
		jPanel8.setLayout(jPanel8Layout);
		jPanel8Layout.setHorizontalGroup(jPanel8Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 386,
				Short.MAX_VALUE));
		jPanel8Layout.setVerticalGroup(jPanel8Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 14,
				Short.MAX_VALUE));

		imgListPanel.add(jPanel8);

		jPanel9.setMaximumSize(new java.awt.Dimension(32767, 14));
		jPanel9.setPreferredSize(new java.awt.Dimension(100, 14));

		javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(
				jPanel9);
		jPanel9.setLayout(jPanel9Layout);
		jPanel9Layout.setHorizontalGroup(jPanel9Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 386,
				Short.MAX_VALUE));
		jPanel9Layout.setVerticalGroup(jPanel9Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 14,
				Short.MAX_VALUE));

		imgListPanel.add(jPanel9);

		jScrollPane1.setViewportView(imgListPanel);

		jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

		jTabbedPane1.addTab(Vovo.getMyContext().getViewManager().getUIString(
				"ChangeHeadImgDialog.local.image"), jPanel4);

		jPanel6.setOpaque(false);
		jPanel6.setLayout(new java.awt.BorderLayout());

		jPanel10.setOpaque(false);
		jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

		jButton3.setText(Vovo.getMyContext().getViewManager().getUIString(
				"ChangeHeadImgDialog.local.image"));
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		jPanel10.add(jButton3);

		jPanel6.add(jPanel10, java.awt.BorderLayout.NORTH);

		customerImgPanel.setMinimumSize(new java.awt.Dimension(300, 250));
		customerImgPanel.setPreferredSize(new java.awt.Dimension(300, 250));
		customerImgPanel.setLayout(new java.awt.BorderLayout());
		jPanel6.add(customerImgPanel, java.awt.BorderLayout.CENTER);

		jTabbedPane1.addTab(Vovo.getMyContext().getViewManager().getUIString(
				"ChangeHeadImgDialog.customer.headimg"), jPanel6);

		jPanel2.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 1.0;
		backgroundXPanel.add(jPanel2, gridBagConstraints);

		jPanel3.setMaximumSize(new java.awt.Dimension(32767, 30));
		jPanel3.setMinimumSize(new java.awt.Dimension(100, 30));
		jPanel3.setOpaque(false);
		jPanel3.setPreferredSize(new java.awt.Dimension(100, 30));
		jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT,
				15, 5));

		jButton1.setText(Vovo.getMyContext().getViewManager().getUIString(
				"UserSettingDialog.okButton"));
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jPanel3.add(jButton1);

		jButton2.setText(Vovo.getMyContext().getViewManager().getUIString(
				"UserSettingDialog.cancelButton"));
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		jPanel3.add(jButton2);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		backgroundXPanel.add(jPanel3, gridBagConstraints);

		jXPanel1.add(backgroundXPanel, java.awt.BorderLayout.CENTER);

		getContentPane().add(jXPanel1, java.awt.BorderLayout.PAGE_START);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void formWindowClosing(java.awt.event.WindowEvent evt) {
		isChageFlag = false;
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		JFileChooser chooser = new JFileChooser();
		chooser.setFileFilter(new javax.swing.filechooser.FileFilter() {
			public boolean accept(File f) {
				String suffix = f.getName().toLowerCase();
				return suffix.endsWith(".png") || suffix.endsWith(".gif")
						|| suffix.endsWith(".jpg") || suffix.endsWith(".bmp")
						|| f.isDirectory();
			}

			public String getDescription() {
				return ".png,.gif,.jpg,.bmp";
			}
		});
		int showOpenDialog = chooser.showOpenDialog(null);
		if (showOpenDialog == JFileChooser.APPROVE_OPTION) {
			File f = chooser.getSelectedFile();
			String suffix = f.getName().toLowerCase();
			if (suffix.endsWith(".png") || suffix.endsWith(".gif")
					|| suffix.endsWith(".jpg") || suffix.endsWith(".bmp")) {
				this.customerImgPanel.removeAll();
				this.jTabbedPane1.revalidate();
				this.jTabbedPane1.repaint();
				final CustomHeadOperatePanel customHeadOperatePanel = new CustomHeadOperatePanel(
						f.getAbsolutePath(),
						this.customerImgPanel.getSize().width,
						this.customerImgPanel.getSize().height);
				customHeadOperatePanel
						.addMouseRelease(new MouseReleaseListener() {

							@Override
							public void doAction() {
								isChageFlag = true;
								resultImage = customHeadOperatePanel
										.getResultImage();
								ImageUtil.adjustLabelIcon(previewLabel,
										resultImage);
								previewLabel.revalidate();
								previewLabel.repaint();
								imgName = null;
							}
						});
				this.customerImgPanel.add(customHeadOperatePanel);
				this.jTabbedPane1.revalidate();
				this.jTabbedPane1.repaint();
				this.validate();
				this.repaint();
			}
		}
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		if (this.imgName != null && this.imgName.trim().length() > 3) {
			Vovo.exeC("main", "changeHeadImg", imgName, 0, null);
			if (this.settingDialog != null) {
				this.settingDialog.setIconLabelForChange(imgName);
			}
		} else {
			Vovo.exeC("main", "changeHeadImg", null, 1, ImageUtil
					.convertBufferedImage2ByteArray(PicScale.getInstance()
							.resizeImage(resultImage, 100, 100)));
			if (this.settingDialog != null) {
				this.settingDialog.setIconLabelForChange(resultImage);
			}
		}
		this.dispose();
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				ChangeHeadImgDialog dialog = new ChangeHeadImgDialog(
						new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private org.jdesktop.swingx.JXPanel backgroundXPanel;
	private javax.swing.JPanel customerImgPanel;
	private javax.swing.JPanel imgListPanel;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel10;
	private javax.swing.JPanel jPanel11;
	private javax.swing.JPanel jPanel12;
	private javax.swing.JPanel jPanel13;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JPanel jPanel9;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTabbedPane jTabbedPane1;
	private org.jdesktop.swingx.JXPanel jXPanel1;
	private javax.swing.JLabel previewLabel;
	// End of variables declaration//GEN-END:variables

	private String imgName;
	private boolean isChageFlag = false;

	public void setPreviewLabelImg(String imgName) {
		isChageFlag = true;
		this.imgName = imgName;
		ImageUtil.adjustLabelIcon(previewLabel,
				Constants.SYSTEM_HEAD_IMAGE_PATH_SYS + imgName);
	}
}