/*
 * ConferenceDescShowDialog.java
 *
 * Created on __DATE__, __TIME__
 */

package com.lorent.vovo.ui;

import java.awt.image.BufferedImage;

import javax.imageio.ImageIO;

import org.apache.log4j.Logger;
import org.jdesktop.swingx.painter.ImagePainter;
import org.jdesktop.swingx.painter.ImagePainter.ScaleType;

import com.lorent.vovo.Vovo;
import com.lorent.vovo.util.Constants;

/**
 *
 * @author  __USER__
 */
public class ConferenceDescShowDialog extends javax.swing.JDialog {

	private static Logger log = Logger
			.getLogger(ConferenceDescShowDialog.class);

	/** Creates new form ConferenceDescShowDialog */
	public ConferenceDescShowDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		jScrollPane1.getViewport().setOpaque(false);
		try {

			BufferedImage resultImage = Vovo.getMyContext().getDataManager()
					.getValue(
							Constants.DataKey.BACKGROUND_GAUSSIAN_IMAGE
									.toString());

			ImagePainter ip = new ImagePainter(resultImage);
			//			ip.setScaleToFit(true);
			ip.setScaleType(ScaleType.Distort);

			backgroundXPanel.setBackgroundPainter(ip);

			BufferedImage whiteimg = ImageIO.read(getClass().getResource(
					"/com/lorent/vovo/resource/images/whitealpha.png"));
			ImagePainter imagePainter = new ImagePainter(whiteimg);
			imagePainter.setScaleType(ScaleType.Distort);
			imagePainter.setScaleToFit(true);
			jXPanel1.setBackgroundPainter(imagePainter);

		} catch (Exception e) {
			log.error("ConferenceEditDialog()", e);
			e.printStackTrace();
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		backgroundXPanel = new org.jdesktop.swingx.JXPanel();
		jPanel2 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jXPanel1 = new org.jdesktop.swingx.JXPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setMinimumSize(new java.awt.Dimension(320, 290));

		backgroundXPanel.setLayout(new java.awt.BorderLayout());

		jPanel2.setOpaque(false);
		jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

		jButton1.setText("\u5173\u95ed");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jPanel2.add(jButton1);

		backgroundXPanel.add(jPanel2, java.awt.BorderLayout.SOUTH);

		jXPanel1.setOpaque(false);

		jScrollPane1
				.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

		jTextArea1.setColumns(20);
		jTextArea1.setEditable(false);
		jTextArea1.setLineWrap(true);
		jTextArea1.setRows(5);
		jTextArea1.setOpaque(false);
		jScrollPane1.setViewportView(jTextArea1);

		javax.swing.GroupLayout jXPanel1Layout = new javax.swing.GroupLayout(
				jXPanel1);
		jXPanel1.setLayout(jXPanel1Layout);
		jXPanel1Layout.setHorizontalGroup(jXPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jXPanel1Layout.createSequentialGroup().addGap(29, 29, 29)
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 342,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(39, Short.MAX_VALUE)));
		jXPanel1Layout.setVerticalGroup(jXPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jXPanel1Layout.createSequentialGroup().addGap(25, 25, 25)
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 232,
								Short.MAX_VALUE).addContainerGap()));

		backgroundXPanel.add(jXPanel1, java.awt.BorderLayout.CENTER);

		getContentPane().add(backgroundXPanel, java.awt.BorderLayout.CENTER);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				ConferenceDescShowDialog dialog = new ConferenceDescShowDialog(
						new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private org.jdesktop.swingx.JXPanel backgroundXPanel;
	private javax.swing.JButton jButton1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1;
	private org.jdesktop.swingx.JXPanel jXPanel1;

	// End of variables declaration//GEN-END:variables

	public void setContent(String str) {
		this.jTextArea1.setText(str);
	}
}