/*
 * ConferencePanel.java
 *
 * Created on __DATE__, __TIME__
 */

package com.lorent.vovo.ui;

import java.awt.AWTException;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;

import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ListModel;
import javax.swing.UIManager;
import javax.swing.plaf.basic.BasicToolBarUI;

import org.apache.log4j.Logger;
import org.jdesktop.swingx.painter.ImagePainter;
import org.jdesktop.swingx.painter.ImagePainter.ScaleType;

import com.jtattoo.plaf.UIUtil;
import com.jtattoo.plaf.vovoglass.VoVoBasicListUI;
import com.lorent.vovo.Vovo;
import com.lorent.vovo.util.Constants;
import com.lorent.vovo.util.Constants.DataKey;

/**
 *
 * @author  __USER__
 */
public class ConferencePanel extends javax.swing.JPanel {

	private static Logger log = Logger.getLogger(ConferencePanel.class);

	private class MyListCellRenderer extends DefaultListCellRenderer {

		@Override
		public Component getListCellRendererComponent(JList list, Object value,
				int index, boolean isSelected, boolean cellHasFocus) {
			ConferenceListItem node = (ConferenceListItem) value;
			//			node.setTextForeground(UIManager.getColor("List.foreground"));
			if (isSelected || cellHasFocus) {
				//				node.setBorder(BorderFactory.createEtchedBorder());
			} else {
				node.setBorder(null);
			}
			return node;
		}

	}

	private ConferenceListItem selectedConferenceListItem;
	private int mouseMoveSelectedIndex = -1;

	/** Creates new form ConferencePanel */
	public ConferencePanel() {
		initComponents();
		jToolBar1.setUI(new BasicToolBarUI());
		jScrollPane1.getViewport().setOpaque(false);
		conferenceList.setCellRenderer(new MyListCellRenderer());
		conferenceList.setUI(new VoVoBasicListUI());
		BufferedImage whiteimg;
		try {
			whiteimg = Vovo.getMyContext().getDataManager().getValue(
					DataKey.WHITE_IMAGE.toString());
			ImagePainter ip = new ImagePainter(whiteimg);
			ip.setScaleToFit(true);
			ip.setScaleType(ScaleType.Distort);
			//			this.bannerPanel.setBackgroundPainter(ip);
			backgroundXPanel.setBackgroundPainter(ip);
		} catch (Exception e) {
			log.error("ConferencePanel()", e);
			e.printStackTrace();
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		cardInfoPopupMenu = new javax.swing.JPopupMenu();
		jToolBar1 = new javax.swing.JToolBar();
		createConferenceButton = new javax.swing.JButton();
		deleteConferenceButton = new javax.swing.JButton();
		modifyConferenceButton = new javax.swing.JButton();
		reflashConferenceButton = new javax.swing.JButton();
		backgroundXPanel = new org.jdesktop.swingx.JXPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		conferenceList = new javax.swing.JList();

		cardInfoPopupMenu.setOpaque(false);

		setOpaque(false);
		setLayout(new java.awt.BorderLayout());

		jToolBar1.setFloatable(false);
		jToolBar1.setRollover(true);
		jToolBar1.setOpaque(false);

		createConferenceButton
				.setIcon(new javax.swing.ImageIcon(getClass().getResource(
						"/com/lorent/vovo/resource/images/edit-add-2.png"))); // NOI18N
		createConferenceButton.setText("\u521b\u5efa\u4f1a\u8bae");
		createConferenceButton.setContentAreaFilled(false);
		createConferenceButton.setFocusable(false);
		createConferenceButton
				.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		createConferenceButton.setMaximumSize(new java.awt.Dimension(60, 47));
		createConferenceButton.setMinimumSize(new java.awt.Dimension(60, 47));
		createConferenceButton.setPreferredSize(new java.awt.Dimension(60, 47));
		createConferenceButton
				.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		createConferenceButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						createConferenceButtonActionPerformed(evt);
					}
				});
		jToolBar1.add(createConferenceButton);

		deleteConferenceButton.setIcon(new javax.swing.ImageIcon(
				getClass().getResource(
						"/com/lorent/vovo/resource/images/dialog-no-2.png"))); // NOI18N
		deleteConferenceButton.setText("\u5220\u9664\u4f1a\u8bae");
		deleteConferenceButton.setContentAreaFilled(false);
		deleteConferenceButton.setEnabled(false);
		deleteConferenceButton.setFocusable(false);
		deleteConferenceButton
				.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		deleteConferenceButton.setMaximumSize(new java.awt.Dimension(60, 47));
		deleteConferenceButton.setMinimumSize(new java.awt.Dimension(60, 47));
		deleteConferenceButton.setPreferredSize(new java.awt.Dimension(60, 47));
		deleteConferenceButton
				.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		deleteConferenceButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						deleteConferenceButtonActionPerformed(evt);
					}
				});
		jToolBar1.add(deleteConferenceButton);

		modifyConferenceButton.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/com/lorent/vovo/resource/images/edit-3.png"))); // NOI18N
		modifyConferenceButton.setText("\u4fee\u6539\u4f1a\u8bae");
		modifyConferenceButton.setContentAreaFilled(false);
		modifyConferenceButton.setEnabled(false);
		modifyConferenceButton.setFocusable(false);
		modifyConferenceButton
				.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		modifyConferenceButton.setMaximumSize(new java.awt.Dimension(60, 47));
		modifyConferenceButton.setMinimumSize(new java.awt.Dimension(60, 47));
		modifyConferenceButton.setPreferredSize(new java.awt.Dimension(60, 47));
		modifyConferenceButton
				.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		modifyConferenceButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						modifyConferenceButtonActionPerformed(evt);
					}
				});
		jToolBar1.add(modifyConferenceButton);

		reflashConferenceButton.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/com/lorent/vovo/resource/images/reflash.png"))); // NOI18N
		reflashConferenceButton.setText("\u5237\u65b0");
		reflashConferenceButton.setContentAreaFilled(false);
		reflashConferenceButton.setFocusable(false);
		reflashConferenceButton
				.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		reflashConferenceButton.setMaximumSize(new java.awt.Dimension(60, 47));
		reflashConferenceButton.setMinimumSize(new java.awt.Dimension(60, 47));
		reflashConferenceButton
				.setPreferredSize(new java.awt.Dimension(60, 47));
		reflashConferenceButton
				.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		reflashConferenceButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						reflashConferenceButtonActionPerformed(evt);
					}
				});
		jToolBar1.add(reflashConferenceButton);

		add(jToolBar1, java.awt.BorderLayout.PAGE_START);

		backgroundXPanel.setOpaque(false);
		backgroundXPanel.setLayout(new java.awt.BorderLayout());

		jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1,
				1, 1, 1));
		jScrollPane1.setOpaque(false);

		conferenceList.setComponentPopupMenu(cardInfoPopupMenu);
		conferenceList.setModel(new DefaultListModel());
		conferenceList
				.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		conferenceList.setOpaque(false);
		conferenceList.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				conferenceListMouseClicked(evt);
			}

			public void mouseEntered(java.awt.event.MouseEvent evt) {
				conferenceListMouseEntered(evt);
			}

			public void mouseExited(java.awt.event.MouseEvent evt) {
				conferenceListMouseExited(evt);
			}
		});
		conferenceList
				.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
					public void valueChanged(
							javax.swing.event.ListSelectionEvent evt) {
						conferenceListValueChanged(evt);
					}
				});
		conferenceList
				.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
					public void mouseMoved(java.awt.event.MouseEvent evt) {
						conferenceListMouseMoved(evt);
					}
				});
		jScrollPane1.setViewportView(conferenceList);

		backgroundXPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

		add(backgroundXPanel, java.awt.BorderLayout.CENTER);
	}// </editor-fold>
	//GEN-END:initComponents

	private void conferenceListMouseClicked(java.awt.event.MouseEvent evt) {
		if (evt.getButton() == MouseEvent.BUTTON1 && evt.getClickCount() == 2) {
			Vovo.exeC("conference", "showJoinConfConfirmDialog",
					selectedConferenceListItem);
		}
	}

	private void reflashConferenceButtonActionPerformed(
			java.awt.event.ActionEvent evt) {
		Vovo.exeC("conference", "getConferenceList", this);
	}

	private void deleteConferenceButtonActionPerformed(
			java.awt.event.ActionEvent evt) {
		Vovo.exeC("conference", "doDeleteConference",
				selectedConferenceListItem, this);
	}

	private void modifyConferenceButtonActionPerformed(
			java.awt.event.ActionEvent evt) {
		Vovo.exeC("conference", "showConferenceModifyDialog",this,
				selectedConferenceListItem);
	}

	private void createConferenceButtonActionPerformed(
			java.awt.event.ActionEvent evt) {
		//		Vovo.exeC("conference", "getConferenceList");
		Vovo.exeC("conference", "showConferenceCreateDialog", this);
	}

	private void conferenceListMouseExited(java.awt.event.MouseEvent evt) {
				cardInfoPopupMenu.setVisible(false);
	}

	private void conferenceListMouseMoved(java.awt.event.MouseEvent evt) {

		int locationToIndex = conferenceList.locationToIndex(evt.getPoint());
		if (locationToIndex != -1) {
			if (locationToIndex != mouseMoveSelectedIndex) {
				try {
					DefaultListModel model = (DefaultListModel) conferenceList
							.getModel();
					ConferenceListItem item1 = (ConferenceListItem) model
							.get(locationToIndex);
					this.repaint();
					Vovo.exeC("conference", "showConferenceCardInfoPanel",
							this, item1, evt);
				} catch (Exception e) {
					log.error("conferenceListMouseMoved", e);
					e.printStackTrace();
				}
			}
		}
		mouseMoveSelectedIndex = locationToIndex;
	}

	private void conferenceListValueChanged(
			javax.swing.event.ListSelectionEvent evt) {

		if (evt.getValueIsAdjusting()) {
			return;
		}
		//		log.debug("fileListValueChanged");
		Object selectedValue = conferenceList.getSelectedValue();
		if (selectedValue instanceof ConferenceListItem) {
			selectedConferenceListItem = (ConferenceListItem) selectedValue;
			deleteConferenceButton.setEnabled(true);
			modifyConferenceButton.setEnabled(true);
		} else {
			selectedConferenceListItem = null;
			deleteConferenceButton.setEnabled(false);
			modifyConferenceButton.setEnabled(false);
		}

	}

	private void conferenceListMouseEntered(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:

		//		System.out.println(evt);
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Vovo.exeC("conference", "getConferenceList");
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private org.jdesktop.swingx.JXPanel backgroundXPanel;
	private javax.swing.JPopupMenu cardInfoPopupMenu;
	private javax.swing.JList conferenceList;
	private javax.swing.JButton createConferenceButton;
	private javax.swing.JButton deleteConferenceButton;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JToolBar jToolBar1;
	private javax.swing.JButton modifyConferenceButton;
	private javax.swing.JButton reflashConferenceButton;

	// End of variables declaration//GEN-END:variables
	public javax.swing.JList getConferenceList() {
		return conferenceList;
	}

	public javax.swing.JPopupMenu getCardInfoPopupMenu() {
		return cardInfoPopupMenu;
	}

}