/*
 * GroupChatInviteDialog.java
 *
 * Created on __DATE__, __TIME__
 */

package com.lorent.vovo.ui;

import com.lorent.vovo.Vovo;
import com.lorent.vovo.util.VovoStringUtil;

/**
 *
 * @author  __USER__
 */
public class GroupChatInviteDialog extends javax.swing.JDialog {

	/** Creates new form GroupChatInviteDialog */
	public GroupChatInviteDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		this.tipLabel.setVisible(false);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		accountTextField = new javax.swing.JTextField();
		tipLabel = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("\u9080\u8bf7\u52a0\u5165\u7fa4\u7ec4");
		setResizable(false);

		jLabel1.setText(VovoStringUtil
				.getUIString("GroupChatInviteDialog.inviteLabel.text"));

		accountTextField.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyReleased(java.awt.event.KeyEvent evt) {
				accountTextFieldKeyReleased(evt);
			}
		});

		tipLabel.setForeground(new java.awt.Color(255, 51, 51));
		tipLabel.setText("jLabel2");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(42, 42, 42)
										.addComponent(jLabel1)
										.addGap(18, 18, 18)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(tipLabel)
														.addComponent(
																accountTextField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																156,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(52, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(29, 29, 29)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																accountTextField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																22,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(tipLabel)
										.addContainerGap(24, Short.MAX_VALUE)));

		getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

		jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER,
				20, 5));

		jButton1.setText(VovoStringUtil
				.getUIString("groupchatcreatedialog.okbutton"));
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jPanel2.add(jButton1);

		jButton2.setText(VovoStringUtil
				.getUIString("groupchatcreatedialog.cancelbutton"));
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		jPanel2.add(jButton2);

		getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void accountTextFieldKeyReleased(java.awt.event.KeyEvent evt) {
		if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
			inviteOneToGroupChat();
		}
	}
	
	private void inviteOneToGroupChat(){
		boolean flag = (Boolean) Vovo.exeC("groupChat", "inviteOneToGroupChat",
				this.getRoomJid(), this.accountTextField.getText(), this);
		if (flag) {
			this.accountTextField.setText("");
			this.dispose();
		}
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		this.accountTextField.setText("");
		this.dispose();
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		inviteOneToGroupChat();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				GroupChatInviteDialog dialog = new GroupChatInviteDialog(
						new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTextField accountTextField;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JLabel tipLabel;
	// End of variables declaration//GEN-END:variables

	private String roomJid;

	public void setRoomJid(String roomJid) {
		this.roomJid = roomJid;
	}

	public String getRoomJid() {
		return this.roomJid;
	}

	public javax.swing.JLabel getTipLabel() {
		return tipLabel;
	}

	public void setTipLabel(javax.swing.JLabel tipLabel) {
		this.tipLabel = tipLabel;
	}

	public void setTipContent(String content) {
		if (content == null || content.trim().length() < 1) {
			this.tipLabel.setVisible(false);
		} else {
			this.tipLabel.setText(content);
			this.tipLabel.setVisible(true);
		}
	}
}