/*
 * GroupListPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package com.lorent.vovo.ui;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;

import javax.imageio.ImageIO;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.plaf.basic.BasicToolBarUI;

import org.jdesktop.swingx.painter.ImagePainter;
import org.jdesktop.swingx.painter.ImagePainter.ScaleType;

import com.jtattoo.plaf.vovoglass.VoVoBasicListUI;
import com.lorent.vovo.Vovo;
import com.lorent.vovo.util.Constants;
import com.lorent.vovo.util.VovoStringUtil;

/**
 *
 * @author  __USER__
 */
public class GroupListPanel extends javax.swing.JPanel {

	private class MyListCellRenderer extends DefaultListCellRenderer {

		@Override
		public Component getListCellRendererComponent(JList list, Object value,
				int index, boolean isSelected, boolean cellHasFocus) {
			GroupListItem node = (GroupListItem) value;
			//			node.setTextForeground(UIManager.getColor("List.foreground"));
			if (isSelected || cellHasFocus) {
				node.setBackground(new Color(0xC3E2F8));
			} else {
				node.setBackground(Color.WHITE);
			}
			return node;
		}

	}

	public void updateItem(String roomJid, String topic, String desc) {
		DefaultListModel model = (DefaultListModel) groupList.getModel();
		Enumeration<GroupListItem> e = (Enumeration<GroupListItem>) model
				.elements();
		while (e.hasMoreElements()) {
			GroupListItem item = e.nextElement();
			if (item != null && item.getRoomJid() != null
					&& item.getRoomJid().equals(roomJid)) {
				item.setGroupName(topic);
				item.setGroupDesc(desc);
				break;
			}
		}
		this.repaint();
	}

	public JList getGroupList() {
		return groupList;
	}

	public GroupListItem removeItem(String roomJid) {
		DefaultListModel model = (DefaultListModel) groupList.getModel();
		Enumeration<GroupListItem> e = (Enumeration<GroupListItem>) model
				.elements();
		GroupListItem targetItem = null;
		int i = -1;
		while (e.hasMoreElements()) {
			i++;
			GroupListItem item = e.nextElement();
			if (item != null && item.getRoomJid() != null
					&& item.getRoomJid().equals(roomJid)) {
				break;
			}
		}
		targetItem = (GroupListItem) model.remove(i);
		this.repaint();
		return targetItem;
	}
	
	
	public GroupListItem findItemByRoomJid(String roomJid){
		DefaultListModel model = (DefaultListModel) groupList.getModel();
		Enumeration<GroupListItem> e = (Enumeration<GroupListItem>) model
				.elements();
		GroupListItem targetItem = null;
		int i = -1;
		while (e.hasMoreElements()) {
			i++;
			GroupListItem item = e.nextElement();
			if (item != null && item.getRoomJid() != null
					&& item.getRoomJid().equals(roomJid)) {
				targetItem = item;
				break;
			}
		}
		return targetItem;
	} 
	

	public void addItem(GroupListItem item) {
		DefaultListModel model = (DefaultListModel) groupList.getModel();
		model.addElement(item);
		this.repaint();
	}

	/** Creates new form GroupListPanel */
	public GroupListPanel() {
		initComponents();
		jToolBar1.setUI(new BasicToolBarUI());
		this.deleteButton.setVisible(false);
		groupScrollPane.getViewport().setOpaque(false);
		groupList.removeAll();
		groupList.setModel(new DefaultListModel());
		groupList.setCellRenderer(new MyListCellRenderer());
		groupList.setUI(new VoVoBasicListUI());
		BufferedImage whiteimg;
		try {
			whiteimg = ImageIO.read(getClass().getResource(
					"/com/lorent/vovo/resource/images/whitealpha.png"));
			ImagePainter ip = new ImagePainter(whiteimg);
			ip.setScaleToFit(true);
			ip.setScaleType(ScaleType.Distort);
			//			this.bannerPanel.setBackgroundPainter(ip);
			backgroundPanel.setBackgroundPainter(ip);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		backgroundPanel = new org.jdesktop.swingx.JXPanel();
		groupScrollPane = new javax.swing.JScrollPane();
		groupList = new javax.swing.JList();
		jToolBar1 = new javax.swing.JToolBar();
		createButton = new javax.swing.JButton();
		quitButton = new javax.swing.JButton();
		joinButton = new javax.swing.JButton();
		deleteButton = new javax.swing.JButton();

		setOpaque(false);
		setLayout(new java.awt.BorderLayout());

		backgroundPanel.setOpaque(false);
		backgroundPanel.setLayout(new java.awt.BorderLayout());

		groupScrollPane.setOpaque(false);

		groupList.setOpaque(false);
		groupList.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				groupListMouseClicked(evt);
			}
		});
		groupScrollPane.setViewportView(groupList);

		backgroundPanel.add(groupScrollPane, java.awt.BorderLayout.CENTER);

		jToolBar1.setFloatable(false);
		jToolBar1.setRollover(true);
		jToolBar1.setOpaque(false);

		createButton.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/com/lorent/vovo/resource/images/group_add.png"))); // NOI18N
		createButton.setText(VovoStringUtil
				.getUIString("grouplistpanel.create"));
		createButton.setContentAreaFilled(false);
		createButton.setFocusable(false);
		createButton
				.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		createButton.setMaximumSize(new java.awt.Dimension(60, 47));
		createButton.setMinimumSize(new java.awt.Dimension(60, 47));
		createButton.setPreferredSize(new java.awt.Dimension(60, 47));
		createButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		createButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				createButtonActionPerformed(evt);
			}
		});
		jToolBar1.add(createButton);

		quitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/com/lorent/vovo/resource/images/group_out.png"))); // NOI18N
		quitButton.setText(VovoStringUtil.getUIString("grouplistpanel.quit"));
		quitButton.setFocusable(false);
		quitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		quitButton.setMaximumSize(new java.awt.Dimension(60, 47));
		quitButton.setMinimumSize(new java.awt.Dimension(60, 47));
		quitButton.setPreferredSize(new java.awt.Dimension(60, 47));
		quitButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		quitButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				quitButtonActionPerformed(evt);
			}
		});
		jToolBar1.add(quitButton);

		joinButton.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/com/lorent/vovo/resource/images/group_join.png"))); // NOI18N
		joinButton.setText(VovoStringUtil.getUIString("grouplistpanel.join"));
		joinButton.setFocusable(false);
		joinButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		joinButton.setMaximumSize(new java.awt.Dimension(60, 47));
		joinButton.setMinimumSize(new java.awt.Dimension(60, 47));
		joinButton.setPreferredSize(new java.awt.Dimension(60, 47));
		joinButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		joinButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				joinButtonActionPerformed(evt);
			}
		});
		jToolBar1.add(joinButton);

		deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/com/lorent/vovo/resource/images/group_remove.png"))); // NOI18N
		deleteButton.setText(VovoStringUtil
				.getUIString("grouplistpanel.remove"));
		deleteButton.setFocusable(false);
		deleteButton
				.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		deleteButton.setMaximumSize(new java.awt.Dimension(60, 47));
		deleteButton.setMinimumSize(new java.awt.Dimension(60, 47));
		deleteButton.setPreferredSize(new java.awt.Dimension(60, 47));
		deleteButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jToolBar1.add(deleteButton);

		backgroundPanel.add(jToolBar1, java.awt.BorderLayout.NORTH);

		add(backgroundPanel, java.awt.BorderLayout.CENTER);
	}// </editor-fold>
	//GEN-END:initComponents

	private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {
		Vovo.exeC("groupChat", "quitGroupChat");
	}

	private void joinButtonActionPerformed(java.awt.event.ActionEvent evt) {

		Vovo.exeC("groupChat", "searchGroupChat", "");
	}

	private void groupListMouseClicked(java.awt.event.MouseEvent evt) {
		if (evt.getButton() == java.awt.event.MouseEvent.BUTTON1
				&& evt.getClickCount() == 2) {
			int locationToIndex = groupList.locationToIndex(evt.getPoint());
			groupList.setSelectedIndex(locationToIndex);
			Object selectedValue = groupList.getSelectedValue();
			GroupListItem item = (GroupListItem) selectedValue;
			String roomJid = item.getRoomJid();

			Vovo.exeC("groupChat", "fetchOneGroupChatAuthority", roomJid);
//						Vovo.exeC("groupChat", "showGroupMemberListPanel", roomJid);
			Vovo.exeC("groupChat", "showGroupChat", item.getInfo());
		}
	}

	private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {
		GroupChatCreateDialog groupChatCreateDialog = Vovo.getViewManager()
				.getView(Constants.ViewKey.groupChatCreateDialog.toString());
		if (groupChatCreateDialog == null || !groupChatCreateDialog.isVisible()) {
			try {
				groupChatCreateDialog = Vovo.getViewManager().createView(
						GroupChatCreateDialog.class,
						new Class[] { java.awt.Frame.class, boolean.class },
						new Object[] { null, false },
						Constants.ViewKey.groupChatCreateDialog.toString());
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
		try {
			Vovo.getViewManager()
					.setWindowCenterLocation(groupChatCreateDialog);
		} catch (Exception e) {
			e.printStackTrace();
		}
		groupChatCreateDialog.setVisible(true);
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private org.jdesktop.swingx.JXPanel backgroundPanel;
	private javax.swing.JButton createButton;
	private javax.swing.JButton deleteButton;
	private javax.swing.JList groupList;
	private javax.swing.JScrollPane groupScrollPane;
	private javax.swing.JToolBar jToolBar1;
	private javax.swing.JButton joinButton;
	private javax.swing.JButton quitButton;
	// End of variables declaration//GEN-END:variables

}