/*
 * GroupSearchPanelItem.java
 *
 * Created on __DATE__, __TIME__
 */

package com.lorent.vovo.ui;

/**
 *
 * @author  __USER__
 */
public class GroupSearchPanelItem extends javax.swing.JPanel {

	/** Creates new form GroupSearchPanelItem */
	public GroupSearchPanelItem() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();

		setMaximumSize(new java.awt.Dimension(234567878, 75));
		setMinimumSize(new java.awt.Dimension(300, 75));
		setOpaque(false);
		setPreferredSize(new java.awt.Dimension(300, 75));
		setLayout(new java.awt.GridLayout(1, 2, 5, 5));

		jPanel1.setMaximumSize(new java.awt.Dimension(213131231, 15));
		jPanel1.setOpaque(false);
		jPanel1.setPreferredSize(new java.awt.Dimension(132, 15));
		jPanel1.setLayout(new java.awt.BorderLayout());
		add(jPanel1);

		jPanel2.setOpaque(false);
		jPanel2.setLayout(new java.awt.BorderLayout());
		add(jPanel2);
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	// End of variables declaration//GEN-END:variables

	private boolean isFillFir = false;
	private boolean isFillSec = false;

	public boolean addItem(GroupListItem item) {
		if (!isFillFir) {
			item.setApplyInLabelVisible(true);
			jPanel1.add(item, java.awt.BorderLayout.CENTER);
			isFillFir = true;
			return true;
		} else if (!isFillSec) {
			item.setApplyInLabelVisible(true);
			jPanel2.add(item, java.awt.BorderLayout.CENTER);
			isFillSec = true;
			return true;
		}
		return false;
	}
}