/*
 * GroupChatSetFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package com.lorent.vovo.ui;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.util.Enumeration;

import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JList;

import org.jdesktop.swingx.painter.ImagePainter;
import org.jdesktop.swingx.painter.ImagePainter.ScaleType;

import com.jtattoo.plaf.vovoglass.VoVoBasicListUI;
import com.lorent.common.tree.MemberBean;
import com.lorent.vovo.Vovo;
import com.lorent.vovo.util.Constants;
import com.lorent.vovo.util.DataUtil;
import com.lorent.vovo.util.VovoStringUtil;

/**
 *
 * @author  __USER__
 */
public class GroupChatSetFrame extends javax.swing.JFrame {

	private class MyListCellRenderer extends DefaultListCellRenderer {

		@Override
		public Component getListCellRendererComponent(JList list, Object value,
				int index, boolean isSelected, boolean cellHasFocus) {
			GroupMemberListItem node = (GroupMemberListItem) value;
			node.setMemberBean(node.getMemberBean());
			if (isSelected || cellHasFocus) {
				//				node.setBorder(BorderFactory.createEtchedBorder());
				node.setBackground(new Color(0xC3E2F8));
			} else {
				//				node.setBorder(null);
				node.setBackground(Color.WHITE);
			}
			return node;
		}

	}

	public JList getGroupList() {
		return memberList;
	}

	public void initMemberList(GroupMemberListPanel panel) {
		this.setRoomJid(panel.getRoomJid());
		DefaultListModel model = (DefaultListModel) memberList.getModel();
		model.removeAllElements();
		java.util.Set<GroupMemberListItem> col = panel.getMemberListItems()
				.keySet();
		for (GroupMemberListItem n : col) {
			addItem(n);
		}
	}

	public GroupMemberListItem getItem(String userJid) {
		DefaultListModel model = (DefaultListModel) memberList.getModel();
		Enumeration<GroupMemberListItem> e = (Enumeration<GroupMemberListItem>) model
				.elements();
		GroupMemberListItem targetItem = null;
		int i = -1;
		while (e.hasMoreElements()) {
			i++;
			GroupMemberListItem item = e.nextElement();
			if (item != null && item.getMemberBean() != null
					&& item.getMemberBean().getLccAccount().equals(userJid)) {
				targetItem = item;
				break;
			}
		}
		if (targetItem != null) {
			targetItem.setIdx(i);
		}
		return targetItem;
	}

	public void reflashItemByStatus(String userJid, int status) {
		GroupMemberListItem item = getItem(userJid);
		if (item != null) {
			DefaultListModel model = (DefaultListModel) memberList.getModel();
			model.remove(item.getIdx());
			item.getMemberBean().setState(status);
			model.insertElementAt(item, item.getIdx());
		}
	}
	
	public void reflashItem(MemberBean bean){
		GroupMemberListItem item = getItem(bean.getLccAccount());
		if (item != null) {
			DefaultListModel model = (DefaultListModel) memberList.getModel();
			model.remove(item.getIdx());
			item.setMemberBean(bean);
			model.insertElementAt(item, item.getIdx());
		}
	}

	public void addItem(GroupMemberListItem item) {
		DefaultListModel model = (DefaultListModel) memberList.getModel();
		item.setOpaque(false);
		model.addElement(item);
	}

	/** Creates new form GroupChatSetFrame */
	public GroupChatSetFrame() {
		initComponents();
		setIconImage(Toolkit
				.getDefaultToolkit()
				.createImage(
						getClass()
								.getResource(
										Constants.TRAYICON_PATH)));
		jScrollPane1.getViewport().setOpaque(false);
		jScrollPane2.getViewport().setOpaque(false);
		memberList.removeAll();
		memberList.setModel(new DefaultListModel());
		memberList.setCellRenderer(new MyListCellRenderer());
		memberList.setUI(new VoVoBasicListUI());
		try {
			BufferedImage backgroundimg = Vovo.getMyContext().getDataManager()
					.getValue(
							Constants.DataKey.BACKGROUND_GAUSSIAN_IMAGE
									.toString());
			ImagePainter ip = new ImagePainter(backgroundimg);
			//			ip.setScaleToFit(true);
			ip.setScaleType(ScaleType.Distort);
			backgroundXPanel.setBackgroundPainter(ip);
			BufferedImage whiteImage = Vovo.getMyContext().getDataManager()
					.getValue(Constants.DataKey.WHITE_IMAGE.toString());
			ImagePainter ip2 = new ImagePainter(whiteImage);
			ip2.setScaleToFit(true);
			ip2.setScaleType(ScaleType.Distort);
			jPanel2.setBackgroundPainter(ip2);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		this.jButton5.setVisible(false);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		backgroundXPanel = new org.jdesktop.swingx.JXPanel();
		jPanel1 = new javax.swing.JPanel();
		jPanel3 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jPanel4 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jPanel2 = new org.jdesktop.swingx.JXPanel();
		memberPanel = new javax.swing.JPanel();
		operateButtonPanel = new javax.swing.JPanel();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		listPanel = new javax.swing.JPanel();
		jScrollPane2 = new javax.swing.JScrollPane();
		memberList = new javax.swing.JList();
		infoPanel = new javax.swing.JPanel();
		jPanel5 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jPanel6 = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jPanel7 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);

		backgroundXPanel.setOpaque(false);
		backgroundXPanel.setLayout(new java.awt.GridBagLayout());

		jPanel1.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(204, 204, 204)));
		jPanel1.setMinimumSize(new java.awt.Dimension(100, 155));
		jPanel1.setOpaque(false);
		jPanel1.setPreferredSize(new java.awt.Dimension(100, 100));
		jPanel1.setLayout(new java.awt.GridBagLayout());

		jPanel3.setOpaque(false);
		jPanel3.setLayout(new java.awt.BorderLayout(10, 10));

		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/com/lorent/vovo/resource/images/emesene-48.png"))); // NOI18N
		jLabel1.setMaximumSize(new java.awt.Dimension(48, 80));
		jLabel1.setMinimumSize(new java.awt.Dimension(48, 80));
		jLabel1.setPreferredSize(new java.awt.Dimension(48, 80));
		jPanel3.add(jLabel1, java.awt.BorderLayout.CENTER);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		jPanel1.add(jPanel3, gridBagConstraints);

		jPanel4.setOpaque(false);
		jPanel4.setLayout(new java.awt.GridLayout(4, 1, 5, 5));

		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel2.setText(VovoStringUtil
				.getUIString("GroupChatSetFrame.infoLabel.text"));
		jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel2MouseClicked(evt);
			}
		});
		jPanel4.add(jLabel2);

		jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel3.setText(VovoStringUtil
				.getUIString("GroupChatSetFrame.memberLabel.text"));
		jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel3MouseClicked(evt);
			}
		});
		jPanel4.add(jLabel3);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 0.9;
		jPanel1.add(jPanel4, gridBagConstraints);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
		gridBagConstraints.weighty = 1.0;
		backgroundXPanel.add(jPanel1, gridBagConstraints);

		jPanel2.setOpaque(false);
		jPanel2.setLayout(new java.awt.CardLayout());

		memberPanel.setOpaque(false);
		memberPanel.setLayout(new java.awt.GridBagLayout());

		operateButtonPanel.setOpaque(false);
		operateButtonPanel.setLayout(new java.awt.FlowLayout(
				java.awt.FlowLayout.LEFT));

		jButton3.setText("\u9080\u8bf7");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		operateButtonPanel.add(jButton3);

		jButton4.setText("\u8e22\u51fa");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});
		operateButtonPanel.add(jButton4);

		jButton5.setText("\u8bbe\u7f6e\u6743\u9650");
		operateButtonPanel.add(jButton5);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		memberPanel.add(operateButtonPanel, gridBagConstraints);

		listPanel.setOpaque(false);
		listPanel.setLayout(new java.awt.BorderLayout(5, 5));

		jScrollPane2.setOpaque(false);

		memberList.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4",
					"Item 5" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		memberList
				.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		memberList.setOpaque(false);
		jScrollPane2.setViewportView(memberList);

		listPanel.add(jScrollPane2, java.awt.BorderLayout.CENTER);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 0.9;
		memberPanel.add(listPanel, gridBagConstraints);

		jPanel2.add(memberPanel, "card3");

		infoPanel.setOpaque(false);
		infoPanel.setLayout(new java.awt.GridBagLayout());

		jPanel5.setOpaque(false);

		jLabel4.setText(VovoStringUtil
				.getUIString("groupchatcreatedialog.groupname"));

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(
				jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel5Layout.createSequentialGroup().addGap(27, 27, 27)
						.addComponent(jLabel4).addGap(18, 18, 18).addComponent(
								jTextField1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 299,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(18, Short.MAX_VALUE)));
		jPanel5Layout
				.setVerticalGroup(jPanel5Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel5Layout
										.createSequentialGroup()
										.addContainerGap(48, Short.MAX_VALUE)
										.addGroup(
												jPanel5Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																31,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(20, 20, 20)));

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 0.33;
		infoPanel.add(jPanel5, gridBagConstraints);

		jPanel6.setOpaque(false);

		jLabel5.setText(VovoStringUtil
				.getUIString("groupchatcreatedialog.groupdescription"));

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(
				jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout.setHorizontalGroup(jPanel6Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel6Layout.createSequentialGroup().addGap(25, 25, 25)
						.addComponent(jLabel5).addGap(18, 18, 18).addComponent(
								jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 302,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(17, Short.MAX_VALUE)));
		jPanel6Layout
				.setVerticalGroup(jPanel6Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel6Layout
										.createSequentialGroup()
										.addGap(38, 38, 38)
										.addGroup(
												jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel5))
										.addContainerGap(48, Short.MAX_VALUE)));

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 0.33;
		infoPanel.add(jPanel6, gridBagConstraints);

		jPanel7.setOpaque(false);

		jButton1.setText(VovoStringUtil
				.getUIString("groupchatcreatedialog.okbutton"));
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText(VovoStringUtil
				.getUIString("groupchatcreatedialog.cancelbutton"));
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(
				jPanel7);
		jPanel7.setLayout(jPanel7Layout);
		jPanel7Layout.setHorizontalGroup(jPanel7Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel7Layout.createSequentialGroup().addGap(190, 190, 190)
						.addComponent(jButton1).addGap(18, 18, 18)
						.addComponent(jButton2).addContainerGap(22,
								Short.MAX_VALUE)));
		jPanel7Layout.setVerticalGroup(jPanel7Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel7Layout.createSequentialGroup().addGap(5, 5, 5).addGroup(
						jPanel7Layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jButton1).addComponent(jButton2))
						.addContainerGap(48, Short.MAX_VALUE)));

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 0.33;
		infoPanel.add(jPanel7, gridBagConstraints);

		jPanel2.add(infoPanel, "card2");

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 0.9;
		gridBagConstraints.weighty = 1.0;
		backgroundXPanel.add(jPanel2, gridBagConstraints);

		getContentPane().add(backgroundXPanel, java.awt.BorderLayout.CENTER);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		Vovo.exeC("groupChat", "showInviteDialog", getRoomJid());
	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		GroupMemberListItem selectedValue = (GroupMemberListItem) memberList
				.getSelectedValue();
		if (selectedValue == null) {
			return;
		}
		//		System.out.println(selectedValue.getMemberBean().getRealName());
		if (selectedValue.getMemberBean().getLccAccount().equals(
				DataUtil.getUserName())) {
			Vovo.exeC("groupChat", "forbidKickMyself");
			return;
		}
		//		DefaultListModel model = (DefaultListModel) memberList.getModel();
		//		model.removeElement(selectedValue);
		Vovo.exeC("groupChat", "kickOneFromGroupChat", selectedValue
				.getMemberBean(), roomJid);
	}

	public void removeItem(String userJid) {
		DefaultListModel model = (DefaultListModel) memberList.getModel();
		Enumeration<GroupMemberListItem> e = (Enumeration<GroupMemberListItem>) model
				.elements();
		GroupMemberListItem targetItem = null;
		while (e.hasMoreElements()) {
			GroupMemberListItem item = e.nextElement();
			if (item != null && item.getMemberBean() != null
					&& item.getMemberBean().getLccAccount().equals(userJid)) {
				targetItem = item;
				break;
			}
		}
		if (targetItem != null) {
			model.removeElement(targetItem);
		}

	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		//		this.setTitle(VovoStringUtil.getUIString("GroupChatSetFrame.title")
		//				+ jTextField1.getText());
		Vovo.exeC("groupChat", "changeGroupChatTopicAndDesc",
				this.getRoomJid(), jTextField1.getText(), jTextArea1.getText());
	}

	private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {
		java.awt.CardLayout layout = (CardLayout) jPanel2.getLayout();
		layout.show(jPanel2, "card3");
	}

	private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {
		java.awt.CardLayout layout = (CardLayout) jPanel2.getLayout();
		layout.show(jPanel2, "card2");
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new GroupChatSetFrame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private org.jdesktop.swingx.JXPanel backgroundXPanel;
	private javax.swing.JPanel infoPanel;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel jPanel1;
	private org.jdesktop.swingx.JXPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JPanel listPanel;
	private javax.swing.JList memberList;
	private javax.swing.JPanel memberPanel;
	private javax.swing.JPanel operateButtonPanel;
	// End of variables declaration//GEN-END:variables

	private String roomJid;

	public void setRoomJid(String roomJid) {
		this.roomJid = roomJid;
	}

	public String getRoomJid() {
		return roomJid;
	}

	public void setTopic(String topic) {
		jTextField1.setText(topic);
	}

	public void setDesc(String desc) {
		jTextArea1.setText(desc);
	}

}