/*
 * GroupChatCreateDialog.java
 *
 * Created on __DATE__, __TIME__
 */

package com.lorent.vovo.ui;

import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.List;

import org.jdesktop.swingx.painter.ImagePainter;
import org.jdesktop.swingx.painter.ImagePainter.ScaleType;

import com.lorent.common.tree.DepartmentBean;
import com.lorent.common.tree.MemberBean;
import com.lorent.vovo.Vovo;
import com.lorent.vovo.VovoContext;
import com.lorent.vovo.util.Constants;
import com.lorent.vovo.util.DataUtil;
import com.lorent.vovo.util.DateUtil;
import com.lorent.vovo.util.MyOpenfireUtil;
import com.lorent.vovo.util.VovoStringUtil;

/**
 *
 * @author  __USER__
 */
public class GroupChatCreateDialog extends javax.swing.JDialog {

	private SelectedUserList selectedUserList = new SelectedUserList();
	private GroupChatCreateTree tree = null;

	public GroupChatCreateTree getTree() {
		return tree;
	}

	public SelectedUserList getSelectedUserList() {
		return selectedUserList;
	}

	/** Creates new form GroupChatCreateDialog */
	public GroupChatCreateDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		//		DefaultMutableTreeNode top = DepartmentTreeUI.createNodes(DepartmentTreeNodePanel.class);
		//		tree = new GroupChatCreateTree(DepartmentTreeNodePanel.class);
		tree = (GroupChatCreateTree) TreeManager.createTree(this.getClass(),
				GroupChatCreateTree.class, DepartmentTreeNodePanel.class);
		this.jScrollPane1.remove(jTree1);
		this.jScrollPane1.setViewportView(tree);
		this.jScrollPane2.remove(jList1);
		this.jScrollPane2.setViewportView(selectedUserList);
		this.jButton1.setVisible(false);
		this.jButton2.setVisible(false);
		this.jButton3.setVisible(false);
		try {
			BufferedImage backgroundImage = Vovo.getMyContext()
					.getDataManager().getValue(
							Constants.DataKey.BACKGROUND_GAUSSIAN_IMAGE
									.toString());
			ImagePainter ip = new ImagePainter(backgroundImage);
//			ip.setScaleToFit(true);
			ip.setScaleType(ScaleType.Distort);
			//			this.bannerPanel.setBackgroundPainter(ip);
			backgroundXPanel.setBackgroundPainter(ip);

			BufferedImage whiteImage = Vovo.getMyContext().getDataManager()
					.getValue(Constants.DataKey.WHITE_IMAGE.toString());
			ImagePainter ip1 = new ImagePainter(whiteImage);
			ip1.setScaleToFit(true);
			ip1.setScaleType(ScaleType.Distort);
			//			this.bannerPanel.setBackgroundPainter(ip);
			jXPanel1.setBackgroundPainter(ip1);

		} catch (Exception e) {
			e.printStackTrace();
		}
		jScrollPane1.getViewport().setOpaque(false);
		jScrollPane2.getViewport().setOpaque(false);
		tree.setOpaque(false);
		selectedUserList.setOpaque(false);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		backgroundXPanel = new org.jdesktop.swingx.JXPanel();
		jXPanel1 = new org.jdesktop.swingx.JXPanel();
		jPanel1 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jPanel2 = new javax.swing.JPanel();
		jPanel4 = new javax.swing.JPanel();
		jPanel5 = new javax.swing.JPanel();
		jPanel6 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jPanel8 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTree1 = new javax.swing.JTree();
		jPanel7 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jList1 = new javax.swing.JList();
		jPanel3 = new javax.swing.JPanel();
		jButton3 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton1 = new javax.swing.JButton();
		okButton = new javax.swing.JButton();
		cancelButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle(VovoStringUtil.getUIString("groupchatcreatedialog.title"));
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				formWindowClosing(evt);
			}
		});

		backgroundXPanel.setLayout(new java.awt.BorderLayout());

		jXPanel1.setOpaque(false);
		jXPanel1.setLayout(new java.awt.GridBagLayout());

		jPanel1.setOpaque(false);

		jLabel3.setText(VovoStringUtil
				.getUIString("groupchatcreatedialog.groupname"));

		jLabel4.setText(VovoStringUtil
				.getUIString("groupchatcreatedialog.groupdescription"));

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane3.setViewportView(jTextArea1);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(34, 34, 34)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel4)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jScrollPane3,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				0,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel3)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jTextField1,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				391,
																				Short.MAX_VALUE)))
										.addGap(44, 44, 44)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel4)
														.addComponent(
																jScrollPane3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																42,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		jXPanel1.add(jPanel1, gridBagConstraints);

		jPanel2.setOpaque(false);
		jPanel2.setLayout(new java.awt.GridBagLayout());

		jPanel4.setOpaque(false);

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 0,
				Short.MAX_VALUE));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 0,
				Short.MAX_VALUE));

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		jPanel2.add(jPanel4, gridBagConstraints);

		jPanel5.setOpaque(false);
		jPanel5.setLayout(new java.awt.GridBagLayout());

		jPanel6.setOpaque(false);

		jLabel1.setText(Vovo.getMyContext().getViewManager().getUIString(
				"grouplistpanel.organlist.label"));

		jPanel8.setOpaque(false);
		jPanel8.setLayout(new java.awt.BorderLayout());

		jScrollPane1.setOpaque(false);

		jTree1.setOpaque(false);
		jScrollPane1.setViewportView(jTree1);

		jPanel8.add(jScrollPane1, java.awt.BorderLayout.CENTER);

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(
				jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout
				.setHorizontalGroup(jPanel6Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel6Layout
										.createSequentialGroup()
										.addGap(29, 29, 29)
										.addGroup(
												jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel1)
														.addComponent(
																jPanel8,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																227,
																Short.MAX_VALUE))));
		jPanel6Layout
				.setVerticalGroup(jPanel6Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel6Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanel8,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												206, Short.MAX_VALUE)
										.addContainerGap()));

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 0.5;
		gridBagConstraints.weighty = 1.0;
		jPanel5.add(jPanel6, gridBagConstraints);

		jPanel7.setOpaque(false);

		jLabel2.setText(Vovo.getMyContext().getViewManager().getUIString(
				"grouplistpanel.selectlist.label"));

		jScrollPane2.setOpaque(false);

		jList1.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4",
					"Item 5" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jList1.setOpaque(false);
		jScrollPane2.setViewportView(jList1);

		javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(
				jPanel7);
		jPanel7.setLayout(jPanel7Layout);
		jPanel7Layout
				.setHorizontalGroup(jPanel7Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel7Layout
										.createSequentialGroup()
										.addGap(32, 32, 32)
										.addGroup(
												jPanel7Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jScrollPane2,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																235,
																Short.MAX_VALUE)
														.addComponent(jLabel2))
										.addGap(30, 30, 30)));
		jPanel7Layout
				.setVerticalGroup(jPanel7Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel7Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jLabel2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												15,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jScrollPane2,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												206, Short.MAX_VALUE)
										.addContainerGap()));

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 0.5;
		gridBagConstraints.weighty = 1.0;
		jPanel5.add(jPanel7, gridBagConstraints);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 0.9;
		jPanel2.add(jPanel5, gridBagConstraints);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 1.0;
		jXPanel1.add(jPanel2, gridBagConstraints);

		backgroundXPanel.add(jXPanel1, java.awt.BorderLayout.CENTER);

		jPanel3.setOpaque(false);
		jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT,
				15, 5));

		jButton3.setText("delete");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		jPanel3.add(jButton3);

		jButton2.setText("add");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		jPanel3.add(jButton2);

		jButton1.setText("reflash");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jPanel3.add(jButton1);

		okButton.setText(VovoStringUtil
				.getUIString("groupchatcreatedialog.okbutton"));
		okButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				okButtonActionPerformed(evt);
			}
		});
		jPanel3.add(okButton);

		cancelButton.setText(VovoStringUtil
				.getUIString("groupchatcreatedialog.cancelbutton"));
		cancelButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cancelButtonActionPerformed(evt);
			}
		});
		jPanel3.add(cancelButton);

		backgroundXPanel.add(jPanel3, java.awt.BorderLayout.SOUTH);

		getContentPane().add(backgroundXPanel, java.awt.BorderLayout.CENTER);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void formWindowClosing(java.awt.event.WindowEvent evt) {
		clearTrace();
	}

	private void clearTrace() {
		TreeManager.removeTree(this.getClass());
		Vovo.getViewManager().removeView(
				Constants.ViewKey.groupChatCreateDialog.toString());
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		if (tree instanceof DepartmentTreeUI) {
			//			TreeManager.removeMemberNode("dd");
			TreeManager.removeDepartmentNode(2);
		}
	}

	private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {
		//		try {
		//			MyOpenfireUtil.init("10.168.250.12", 5222);
		//			MyOpenfireUtil.login("85167", "123456");//, "10.168.250.12", 5222
		//		} catch (Exception e) {
		//			e.printStackTrace();
		//		}
		SelectedUserList list = getSelectedUserList();
		List<String> members = list.getMembers();
		GroupListItem item = (GroupListItem) Vovo.exeC("groupChat", "createGroupChat",
				this.jTextField1.getText(), this.jTextArea1.getText(), members, this.isCreateTempGroupChat());
		if (item!=null) {
			this.clearTrace();
			this.dispose();
			String roomJid = item.getRoomJid();
			Vovo.exeC("groupChat", "fetchOneGroupChatAuthority", roomJid);
			Vovo.exeC("groupChat", "showGroupChat", item.getInfo());
		}
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		if (tree instanceof DepartmentTreeUI) {

			//			MemberBean bean = new MemberBean(5,"gg","gg",-1,null,"gg",null,null,"sun");
			//			List<Integer> departments = new ArrayList<Integer>();
			//			departments.add(2);
			//			bean.setDepartments(departments);
			//			TreeManager.addMemberNode(bean);

			DepartmentBean bean = new DepartmentBean(3, "研发2部", 44, 222);
			TreeManager.addDeparmentNode(bean);
		}
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		if (tree instanceof DepartmentTreeUI) {
			//int id,String jid,String desc,int state,String post,String lccAccount,String defaultImg,ImageIcon icon,String realName
			//			TreeManager.reflashMemberNode(new MemberBean(1,"dd","dd",-1,null,"dd",null,null,"zhangsan333333333333"));
			TreeManager.reflashDepartmentNode(new DepartmentBean(2, "研发111",
					44, 222));
		}
	}

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
		this.clearTrace();
		this.dispose();
	}

	//	static{
	//		try {
	//			Vovo instance = new Vovo();
	//			instance.setContext(new VovoContext());
	//			instance.execute();
	//			String userName = "85323";
	//			MyOpenfireUtil.init("10.168.250.12", 5222);
	//			MyOpenfireUtil.login(userName, "123456");
	//			DataUtil.setValue(DataUtil.Key.userName, userName);
	//		} catch (Exception e) {
	//			// TODO Auto-generated catch block
	//			e.printStackTrace();
	//		}
	//		
	//	}
	//	private static GroupChatCreateDialog groupChatCreateDialog = new GroupChatCreateDialog(
	//			new javax.swing.JFrame(), true);

	//	public static GroupChatCreateDialog getInstance() {
	//		return groupChatCreateDialog;
	//	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {

		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {

					//					GroupChatCreateDialog dialog = Vovo.getMyContext().getViewManager().createView(GroupChatCreateDialog.class, new Class[]{javax.swing.JFrame.class,Boolean.class}, new Object[]{new javax.swing.JFrame(), Boolean.TRUE}, null);
					GroupChatCreateDialog dialog = null;//groupChatCreateDialog;
					dialog
							.addWindowListener(new java.awt.event.WindowAdapter() {
								public void windowClosing(
										java.awt.event.WindowEvent e) {
									System.exit(0);
								}
							});
					dialog.setVisible(true);
				} catch (Exception ex) {
					ex.printStackTrace();
				}

			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private org.jdesktop.swingx.JXPanel backgroundXPanel;
	private javax.swing.JButton cancelButton;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JList jList1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTree jTree1;
	private org.jdesktop.swingx.JXPanel jXPanel1;
	private javax.swing.JButton okButton;
	// End of variables declaration//GEN-END:variables

	private boolean tempFlag = false;
	
	public boolean isCreateTempGroupChat(){
		return tempFlag;
	}
	
	public void hiddenTopicAndDesc(){
		this.jTextField1.setText("多人聊天");
//		this.jTextArea1.setText("于" + DateUtil.getStringByDate(new java.util.Date()) + "创建");
		this.tempFlag = true;
		this.jPanel1.setVisible(false);
	}
}