/*
 * HeadSampleImgPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package com.lorent.vovo.ui;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;

import javax.swing.BorderFactory;
import javax.swing.ImageIcon;

import com.lorent.vovo.util.Constants;
import com.lorent.vovo.util.ImageUtil;

/**
 *
 * @author  __USER__
 */
public class HeadSampleImgPanel extends javax.swing.JPanel {

	private ChangeHeadImgDialog dialog;
	private String fileName;
	private ImageIcon icon;

	/** Creates new form HeadSampleImgPanel */
	public HeadSampleImgPanel() {
		initComponents();
	}

	public HeadSampleImgPanel(String fileName, ChangeHeadImgDialog dialog) {
		this();
		this.dialog = dialog;
		this.fileName = fileName;
		ImageUtil.adjustLabelIcon(jLabel1, Constants.SYSTEM_HEAD_IMAGE_PATH_SYS + this.fileName);
//		Image temp = icon.getImage().getScaledInstance(60, 60,
//				icon.getImage().SCALE_DEFAULT);
//		this.jLabel1.setIcon(new ImageIcon(temp));
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();

		setOpaque(false);
		addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				formMouseClicked(evt);
			}
		});
		setLayout(new java.awt.BorderLayout());

		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jLabel1.setMaximumSize(new java.awt.Dimension(60, 60));
		jLabel1.setMinimumSize(new java.awt.Dimension(60, 60));
		jLabel1.setPreferredSize(new java.awt.Dimension(60, 60));
		jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel1MouseClicked(evt);
			}

			public void mouseEntered(java.awt.event.MouseEvent evt) {
				jLabel1MouseEntered(evt);
			}

			public void mouseExited(java.awt.event.MouseEvent evt) {
				jLabel1MouseExited(evt);
			}
		});
		add(jLabel1, java.awt.BorderLayout.CENTER);
	}// </editor-fold>
	//GEN-END:initComponents

	private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {
//		jLabel1.setBorder(BorderFactory.createLineBorder(new Color(255, 255,
//				255), 1));
		
	}

	private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {
		jLabel1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
//		jLabel1.setBorder(BorderFactory.createLineBorder(
//				new Color(0, 127, 255), 1));
	}

	private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {
		if (evt.getClickCount() == 1 && evt.getButton() == evt.BUTTON1) {
			this.dialog.setPreviewLabelImg(fileName);
		}
	}

	private void formMouseClicked(java.awt.event.MouseEvent evt) {
		if (evt.getClickCount() == 1 && evt.getButton() == evt.BUTTON1) {

		}
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	// End of variables declaration//GEN-END:variables

}