/*
 * joinConfConfirmDialog.java
 *
 * Created on __DATE__, __TIME__
 */

package com.lorent.vovo.ui;

import com.lorent.vovo.Vovo;
import com.lorent.vovo.ui.ConferenceListItem;

/**
 *
 * @author  __USER__
 */
public class JoinConfConfirmDialog extends javax.swing.JDialog {

	private ConferenceListItem selectedItem;

	public void setSelectedItem(ConferenceListItem selectedItem) {
		this.selectedItem = selectedItem;
	}

	/** Creates new form joinConfConfirmDialog */
	public JoinConfConfirmDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		textLabel = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		confPasswordField = new javax.swing.JPasswordField();
		jPanel2 = new javax.swing.JPanel();
		okButton = new javax.swing.JButton();
		cancelButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setAlwaysOnTop(true);

		textLabel.setText("jLabel1");

		jLabel2.setText(Vovo.getMyContext().getViewManager().getUIString(
				"ConferenceBubbleDialog.joinConference.label2"));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel2)
																		.addGap(
																				31,
																				31,
																				31)
																		.addComponent(
																				confPasswordField,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				301,
																				Short.MAX_VALUE)
																		.addGap(
																				8,
																				8,
																				8))
														.addComponent(
																textLabel,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																406,
																Short.MAX_VALUE))
										.addContainerGap()));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												textLabel,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												38, Short.MAX_VALUE)
										.addGap(9, 9, 9)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				3,
																				3,
																				3)
																		.addComponent(
																				jLabel2,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				21,
																				Short.MAX_VALUE))
														.addComponent(
																confPasswordField,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																24,
																Short.MAX_VALUE))
										.addGap(11, 11, 11)));

		getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

		jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER,
				20, 5));

		okButton.setText(Vovo.getMyContext().getViewManager().getUIString(
				"ConferenceBubbleDialog.joinConference.yesButtom"));
		okButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				okButtonActionPerformed(evt);
			}
		});
		jPanel2.add(okButton);

		cancelButton.setText(Vovo.getMyContext().getViewManager().getUIString(
				"ConferenceBubbleDialog.joinConference.noButtom"));
		cancelButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cancelButtonActionPerformed(evt);
			}
		});
		jPanel2.add(cancelButton);

		getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
	}

	private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
		Vovo.exeC("conference", "joinConference", selectedItem,
				confPasswordField.getText());
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				JoinConfConfirmDialog dialog = new JoinConfConfirmDialog(
						new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton cancelButton;
	private javax.swing.JPasswordField confPasswordField;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JButton okButton;
	private javax.swing.JLabel textLabel;

	// End of variables declaration//GEN-END:variables

	public ConferenceListItem getSelectedItem() {
		return selectedItem;
	}

	public javax.swing.JLabel getTextLabel() {
		return textLabel;
	}

	public javax.swing.JPasswordField getConfPasswordField() {
		return confPasswordField;
	}

}