/*
 * MainFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package com.lorent.vovo.ui;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;

import javax.swing.BorderFactory;
import javax.swing.ImageIcon;

import org.jdesktop.swingx.painter.ImagePainter;
import org.jdesktop.swingx.painter.ImagePainter.ScaleType;

import com.jtattoo.plaf.vovoglass.VoVoTabbedPaneUI;
import com.lorent.common.dto.VovoMyInfo;
import com.lorent.common.tree.MemberBean;
import com.lorent.vovo.Vovo;
import com.lorent.vovo.util.Constants;
import com.lorent.vovo.util.ImageUtil;

/**
 *
 * @author  Jack
 */
public class MainFrame extends javax.swing.JFrame {

	/** Creates new form MainFrame */
	public MainFrame() {
		initComponents();
		setIconImage(Toolkit.getDefaultToolkit().createImage(
				getClass().getResource(Constants.TRAYICON_PATH)));
		BufferedImage bi = Vovo.getValue(Constants.DataKey.BACKGROUND_IMAGE
				.toString());
		ImagePainter ip = new ImagePainter(bi);
		ip.setScaleToFit(true);
		ip.setScaleType(ScaleType.Distort);
		bgPanel.setBackgroundPainter(ip);
		mainTab.setUI(new VoVoTabbedPaneUI());
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		bgPanel = new org.jdesktop.swingx.JXPanel();
		jPanel1 = new javax.swing.JPanel();
		myHead = new javax.swing.JLabel();
		nameLbl = new javax.swing.JLabel();
		signlbl = new javax.swing.JLabel();
		statusCombobox = new com.lorent.vovo.ui.StatusCombobox();
		phoneButton = new javax.swing.JButton();
		phoneButton.setContentAreaFilled(false);
		phoneButton.setBorderPainted(false);
		phoneButton.setFocusable(false);
		phoneButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
		    	PhoneFrame f = Vovo.getMyContext().getViewManager().getView(Constants.ViewKey.PhoneFrame.toString());
					f.setVisible(true);
				}
			});
		phoneButton.setPreferredSize(new Dimension(16, 16));
		phoneButton.setMinimumSize(new Dimension(16, 16));
		phoneButton.setMaximumSize(new Dimension(16, 16));
		toolPanel = new javax.swing.JPanel();
		//jLabel1 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		mainTab = new javax.swing.JTabbedPane();

		setTitle("VOVO");
		setMinimumSize(new java.awt.Dimension(300, 600));
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				formWindowClosing(evt);
			}
		});

		bgPanel.setLayout(new java.awt.GridBagLayout());

		jPanel1.setOpaque(false);
		jPanel1.setLayout(new java.awt.GridBagLayout());

		myHead.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/com/lorent/vovo/resource/images/systemheads/default60.png"))); // NOI18N
		myHead.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(255, 255, 255)));
		myHead.setMaximumSize(new java.awt.Dimension(64, 64));
		myHead.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				myHeadMouseClicked(evt);
			}

			public void mouseEntered(java.awt.event.MouseEvent evt) {
				myHeadMouseEntered(evt);
			}

			public void mouseExited(java.awt.event.MouseEvent evt) {
				myHeadMouseExited(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.gridheight = 3;
		gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
		jPanel1.add(myHead, gridBagConstraints);

		nameLbl.setText("Jack");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
		jPanel1.add(nameLbl, gridBagConstraints);

		signlbl.setText("  ");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
		jPanel1.add(signlbl, gridBagConstraints);

		statusCombobox.setPreferredSize(new java.awt.Dimension(80, 21));
		statusCombobox.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				statusComboboxItemStateChanged(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
		jPanel1.add(statusCombobox, gridBagConstraints);

		toolPanel.setOpaque(false);
		toolPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT,
				5, 1));
		phoneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/com/lorent/vovo/resource/images/phone.png"))); // NOI18N
		toolPanel.add(phoneButton);
		//toolPanel.add(jLabel1);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		jPanel1.add(toolPanel, gridBagConstraints);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
		bgPanel.add(jPanel1, gridBagConstraints);

		jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(
				255, 255, 255), 3, true));
		jPanel2.setOpaque(false);
		jPanel2.setLayout(new java.awt.BorderLayout());

		mainTab.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
		jPanel2.add(mainTab, java.awt.BorderLayout.CENTER);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 1.0;
		bgPanel.add(jPanel2, gridBagConstraints);

		getContentPane().add(bgPanel, java.awt.BorderLayout.CENTER);

		java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit()
				.getScreenSize();
		setBounds((screenSize.width - 328) / 2, (screenSize.height - 646) / 2,
				328, 646);
	}// </editor-fold>
	//GEN-END:initComponents

	private void formWindowClosing(java.awt.event.WindowEvent evt) {
		//		Vovo.exeC("main", "confirmExit");
		//		this.setVisible(false);
	}

	private void myHeadMouseClicked(java.awt.event.MouseEvent evt) {
		Vovo.exeC("main", "showUserSettingDialog");
	}

	private void statusComboboxItemStateChanged(java.awt.event.ItemEvent evt) {
		if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {//执行一次
			Vovo.exeC("main", "changePresence", statusCombobox
					.getSelectStatus());
		}
	}

	private void myHeadMouseExited(java.awt.event.MouseEvent evt) {
		//		myHead.setBorder(BorderFactory.createEmptyBorder());
		myHead.setBorder(BorderFactory.createLineBorder(
				new Color(255, 255, 255), 1));
	}

	private void myHeadMouseEntered(java.awt.event.MouseEvent evt) {
		myHead.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
		myHead.setBorder(BorderFactory.createLineBorder(new Color(0, 127, 255),
				1));
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainFrame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private org.jdesktop.swingx.JXPanel bgPanel;
	private javax.swing.JButton phoneButton;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JTabbedPane mainTab;
	private javax.swing.JLabel myHead;
	private javax.swing.JLabel nameLbl;
	private javax.swing.JLabel signlbl;
	private com.lorent.vovo.ui.StatusCombobox statusCombobox;
	private javax.swing.JPanel toolPanel;

	// End of variables declaration//GEN-END:variables

	public javax.swing.JTabbedPane getMainTab() {
		return mainTab;
	}

	public com.lorent.vovo.ui.StatusCombobox getStatusCombobox() {
		return statusCombobox;
	}

	public void setMyInfo(MemberBean info) {
		this.nameLbl.setText(info.getRealName() + "(" + info.getLccAccount()
				+ ")");
		if (info.getSign() != null) {
			this.signlbl.setText(info.getSign());
		}

		if (info.getDefaultImg() != null) {
			try {
				//				this.myHead.setIcon(new ImageIcon(getClass().getResource("/com/lorent/vovo/resource/images/systemheads/sys/" + info.getDefaultImg())));
				ImageUtil.adjustLabelIcon(myHead,
						Constants.SYSTEM_HEAD_IMAGE_PATH_SYS
								+ info.getDefaultImg());
			} catch (Exception ex) {

			}
		}
	}

	public void setRealName(String realName) {
		this.nameLbl.setText(realName);
	}

	public void setSignlbl(String str) {
		this.signlbl.setText(str);
	}
}