/*
 * MemberInfoPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package com.lorent.vovo.ui;

import com.lorent.common.tree.MemberBean;

/**
 *
 * @author  Jack
 */
public class MemberInfoPanel extends javax.swing.JPanel {

	/** Creates new form MemberInfoPanel */
	public MemberInfoPanel() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		nameLbl = new javax.swing.JLabel();
		genderLbl = new javax.swing.JLabel();
		positionLbl = new javax.swing.JLabel();
		mobileLbl = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		emailLbl = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		signArea = new javax.swing.JTextArea();

		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("\u4e2a\u4eba\u5f62\u8c61");
		jLabel1.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel2.setText("\u59d3\u540d\uff1a");

		jLabel3.setText("\u6027\u522b\uff1a");

		jLabel4.setText("\u804c\u4f4d\uff1a");

		jLabel5.setText("\u624b\u673a\uff1a");

		jLabel6.setText("\u4e2a\u6027\u7b7e\u540d\uff1a");

		nameLbl.setText("Jack");

		genderLbl.setText("\u7537");

		positionLbl.setText("\u5de5\u7a0b\u5e08");

		mobileLbl.setText("112");

		jLabel12.setText("email\uff1a");

		emailLbl.setText("r@1.cn");

		signArea.setColumns(20);
		signArea.setEditable(false);
		signArea.setLineWrap(true);
		signArea.setRows(5);
		jScrollPane1.setViewportView(signArea);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jLabel1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												127,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																206,
																Short.MAX_VALUE)
														.addComponent(jLabel6)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel2)
																						.addComponent(
																								jLabel3)
																						.addComponent(
																								jLabel4)
																						.addComponent(
																								jLabel5)
																						.addComponent(
																								jLabel12))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								genderLbl,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								85,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								positionLbl,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								85,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								mobileLbl,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								85,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								emailLbl,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								85,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								nameLbl,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								151,
																								javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addContainerGap()));

		layout.linkSize(javax.swing.SwingConstants.HORIZONTAL,
				new java.awt.Component[] { emailLbl, genderLbl, mobileLbl,
						nameLbl, positionLbl });

		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.CENTER)
																						.addComponent(
																								jLabel2)
																						.addComponent(
																								nameLbl))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.CENTER)
																						.addComponent(
																								jLabel3)
																						.addComponent(
																								genderLbl))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.CENTER)
																						.addComponent(
																								jLabel4)
																						.addComponent(
																								positionLbl))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.CENTER)
																						.addComponent(
																								jLabel5)
																						.addComponent(
																								mobileLbl))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.CENTER)
																						.addComponent(
																								jLabel12)
																						.addComponent(
																								emailLbl))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				jLabel6)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jScrollPane1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				56,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addComponent(
																jLabel1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																206,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel emailLbl;
	private javax.swing.JLabel genderLbl;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel mobileLbl;
	private javax.swing.JLabel nameLbl;
	private javax.swing.JLabel positionLbl;
	private javax.swing.JTextArea signArea;

	// End of variables declaration//GEN-END:variables

	public void setInfo(MemberBean info) {
		nameLbl.setText(info.getRealName());
		genderLbl.setText(info.getGender());
		positionLbl.setText(info.getPost());
		mobileLbl.setText(info.getMobile());
		emailLbl.setText(info.getEmail());
		signArea.setText(info.getSign());
	}
}