/*
 * OrganListPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package com.lorent.vovo.ui;

import java.awt.image.BufferedImage;

import org.jdesktop.swingx.painter.ImagePainter;
import org.jdesktop.swingx.painter.ImagePainter.ScaleType;

import com.lorent.vovo.Vovo;
import com.lorent.vovo.util.Constants;

/**
 *
 * @author  jack
 */
public class OrganListPanel extends javax.swing.JPanel {

	private OrgTree tree;

	/** Creates new form OrganListPanel */
	public OrganListPanel() {
		initComponents();
		tree = (OrgTree) TreeManager.createTree(this.getClass(), OrgTree.class,
				TreeNodeInfoPanel.class);
		tree.setOpaque(false);
		jScrollPane1.setViewportView(tree);
		jScrollPane1.getViewport().setOpaque(false);

		BufferedImage whiteImage = Vovo.getMyContext().getDataManager()
				.getValue(Constants.DataKey.WHITE_IMAGE.toString());
		ImagePainter ip1 = new ImagePainter(whiteImage);
		ip1.setScaleToFit(true);
		ip1.setScaleType(ScaleType.Distort);
		jXPanel1.setBackgroundPainter(ip1);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jXPanel1 = new org.jdesktop.swingx.JXPanel();
		jScrollPane1 = new javax.swing.JScrollPane();

		setOpaque(false);
		setLayout(new java.awt.BorderLayout());

		jXPanel1.setOpaque(false);
		jXPanel1.setLayout(new java.awt.BorderLayout());

		jScrollPane1.setOpaque(false);
		jXPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

		add(jXPanel1, java.awt.BorderLayout.CENTER);
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JScrollPane jScrollPane1;
	private org.jdesktop.swingx.JXPanel jXPanel1;
	// End of variables declaration//GEN-END:variables

}