/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PhoneFrame.java
 *
 * Created on 2011-9-16, 11:32:16
 */
package com.lorent.vovo.ui;

import java.awt.AWTEvent;
import java.awt.Color;
import java.awt.Component;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.WindowEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JSlider;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import javax.swing.ListCellRenderer;
import javax.swing.UIManager;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import sun.swing.DefaultLookup;

import com.lorent.vovo.Vovo;
import com.lorent.vovo.util.CallHistory;
import com.lorent.vovo.util.CallHistory.CallHistoryItem;
import com.lorent.vovo.util.Constants;

/**
 *
 * @author Administrator
 */
public class PhoneFrame extends BaseFrame {

    private static Logger log = LoggerFactory.getLogger(PhoneFrame.class);
    private int sindex = 0;
    
    class MyListCellRander implements ListCellRenderer {

        @Override
        public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            if (value instanceof CallHistoryNodePanel) {
                CallHistoryNodePanel temp = (CallHistoryNodePanel) value;
                if (isSelected) {
                    temp.setOpaque(true);
                    Color dg = DefaultLookup.getColor(list, list.getUI(), "List.selectionBackground");
//                    Color fg = DefaultLookup.getColor(list, list.getUI(), "List.dropCellForeground");
                    dg =  UIManager.getColor("List.selectionBackground");
                    //log.info("sssss11"+temp.getCallHistoryTime());
//                    temp.getTextLabel().setBackground(Color.RED);
                    temp.getBottumJPanel().setBackground(dg);
                    temp.getTopJPanel().setBackground(dg);
                    temp.setBackground(dg);
                    //temp.paintSelectedComponent();
                    temp.repaint();
//                    temp.setForeground(fg);
                } else {
                    temp.getBottumJPanel().setBackground(Color.WHITE);
                    temp.getTopJPanel().setBackground(Color.WHITE);
                    temp.setBackground(Color.WHITE);
                    temp.setOpaque(false);
                }
                return temp;
            } else {
                return new JLabel(value.toString());
            }
        }
    }

    /** Creates new form PhoneFrame */
    public PhoneFrame() {
        initComponents();
        screenPanel.setImg(Toolkit.getDefaultToolkit().createImage(getClass().getResource("/com/lorent/vovo/resource/images/dial/screen.png")));
//        mainLeftPanel.repaint();
        screenPanel.DrawImage();
        enableEvents(AWTEvent.WINDOW_EVENT_MASK);
        setLocationRelativeTo(null);
        
        try {
			List<CallHistoryItem> list = CallHistory.getInstance().init();
			for(CallHistoryItem item:list){
				CallHistoryNodePanel callHistoryNodePanel = new CallHistoryNodePanel();
				SimpleDateFormat tempDate = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
				String date=tempDate.format(new Date(item.getDate()));
				callHistoryNodePanel.setInfo(item.getInfo(), item.getPhone(),date,0);
				DefaultListModel model = (DefaultListModel) callHistoryList.getModel();
				model.addElement(callHistoryNodePanel);
			}
		} catch (IOException e) {
			log.error(e.getMessage(),e);
		}
    }

    @Override
    protected void processWindowEvent(WindowEvent e) {
        if (e.getID() == WindowEvent.WINDOW_CLOSING) {
            setVisible(false);
        }
        else{
            super.processWindowEvent(e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        cameraButtonGroup = new javax.swing.ButtonGroup();
        mainLeftPanel = new javax.swing.JPanel();
        leftCenterPanel = new javax.swing.JPanel();
        screenPanel = new ImageAwtPanel();
        leftButtomPanel = new javax.swing.JPanel();
        cameraOpenToggleButton = new javax.swing.JToggleButton();
        cameraCloseToggleButton = new javax.swing.JToggleButton();
        volumeSlider = new javax.swing.JSlider();
        volumeSlider.setValue(100);
        volumeSlider.addChangeListener(new ChangeListener() {
        	public void stateChanged(ChangeEvent e) {
        		javax.swing.JSlider s = (JSlider) e.getSource();
        		if(!s.getValueIsAdjusting()){
        			Vovo.exeC("phone", "setPlaybackVolume", s.getValue());
        		}
        	}
        });
        stateInfoPanel = new javax.swing.JPanel();
        statusIconLabel = new javax.swing.JLabel();
        statusInfoLabel = new javax.swing.JLabel();
        mainRightPanel = new javax.swing.JPanel();
        mainRightTabbedPane = new javax.swing.JTabbedPane();
        dialPanel = new javax.swing.JPanel();
        dialNumberPanel = new javax.swing.JPanel();
        number1Button = new javax.swing.JButton();
        number2Button = new javax.swing.JButton();
        number3Button = new javax.swing.JButton();
        number4Button = new javax.swing.JButton();
        number5Button = new javax.swing.JButton();
        number6Button = new javax.swing.JButton();
        number7Button = new javax.swing.JButton();
        number8Button = new javax.swing.JButton();
        number9Button = new javax.swing.JButton();
        numberStarButton = new javax.swing.JButton();
        number0Button = new javax.swing.JButton();
        numberSharpButton = new javax.swing.JButton();
        dialCallButtonPanel = new javax.swing.JPanel();
        acceptButton = new javax.swing.JButton();
        callButton = new javax.swing.JButton();
        handupButton = new javax.swing.JButton();
        handupButton.addPropertyChangeListener(new PropertyChangeListener() {
        	public void propertyChange(PropertyChangeEvent evt) {
        		String propertyName = evt.getPropertyName();
        		if("enabled".equals(propertyName)){
        			Boolean newValue = (Boolean) evt.getNewValue();
					if(!evt.getOldValue().equals(newValue)){
        				volumeSlider.setEnabled(newValue);
        				if(!newValue){
        					volumeSlider.setValue(100);
        				}
        			}
        		}
        	}
        });
        phoneNumberPanel = new javax.swing.JPanel();
        phoneNumberTextField = new javax.swing.JTextField();
        undoButton = new javax.swing.JButton();
        phoneCallHistoryPanel = new javax.swing.JPanel();
        searchPanel = new javax.swing.JPanel();
        dateInput = new DateInput();
        callHistoryScrollPanel = new javax.swing.JScrollPane();
        callHistoryList = new javax.swing.JList(new DefaultListModel());

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/lorent/vovo/resource/i18n/PhoneFrame"); // NOI18N
        setTitle(bundle.getString("PhoneFrame.title")); // NOI18N
        setMinimumSize(new java.awt.Dimension(484, 362));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        mainLeftPanel.setMinimumSize(new java.awt.Dimension(600, 500));
        mainLeftPanel.setPreferredSize(new java.awt.Dimension(600, 500));
        mainLeftPanel.setLayout(new java.awt.GridBagLayout());

        leftCenterPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        leftCenterPanel.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout screenPanelLayout = new javax.swing.GroupLayout(screenPanel);
        screenPanel.setLayout(screenPanelLayout);
        screenPanelLayout.setHorizontalGroup(
            screenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );
        screenPanelLayout.setVerticalGroup(
            screenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        leftCenterPanel.add(screenPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        mainLeftPanel.add(leftCenterPanel, gridBagConstraints);

        leftButtomPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        leftButtomPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5));

        cameraButtonGroup.add(cameraOpenToggleButton);
        cameraOpenToggleButton.setText(bundle.getString("PhoneFrame.cameraOPenToggleButton.text")); // NOI18N
        cameraOpenToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cameraOpenToggleButtonActionPerformed(evt);
            }
        });
        leftButtomPanel.add(cameraOpenToggleButton);

        cameraButtonGroup.add(cameraCloseToggleButton);
        cameraCloseToggleButton.setSelected(true);
        cameraCloseToggleButton.setText(bundle.getString("PhoneFrame.cameraCloseToggleButton.text")); // NOI18N
        cameraCloseToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cameraCloseToggleButtonActionPerformed(evt);
            }
        });
        leftButtomPanel.add(cameraCloseToggleButton);

        volumeSlider.setPaintLabels(true);
        volumeSlider.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("PhoneFrame.volume.title"))); // NOI18N
        leftButtomPanel.add(volumeSlider);
        volumeSlider.getAccessibleContext().setAccessibleName(bundle.getString("PhoneFrame.volumeSlider.title")); // NOI18N

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        mainLeftPanel.add(leftButtomPanel, gridBagConstraints);

        stateInfoPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        stateInfoPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        statusIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lorent/vovo/resource/images/dial/full.png"))); // NOI18N
        stateInfoPanel.add(statusIconLabel);
        stateInfoPanel.add(statusInfoLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        mainLeftPanel.add(stateInfoPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(mainLeftPanel, gridBagConstraints);

        mainRightPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mainRightPanel.setMinimumSize(new java.awt.Dimension(300, 126));
        mainRightPanel.setPreferredSize(new java.awt.Dimension(300, 342));
        mainRightPanel.setLayout(new java.awt.BorderLayout());

        dialPanel.setLayout(new java.awt.BorderLayout());

        dialNumberPanel.setLayout(new java.awt.GridLayout(4, 3));

        number1Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lorent/vovo/resource/images/dial/number1.png"))); // NOI18N
        number1Button.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        number1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number1ButtonActionPerformed(evt);
            }
        });
        dialNumberPanel.add(number1Button);

        number2Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lorent/vovo/resource/images/dial/number2.png"))); // NOI18N
        number2Button.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        number2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number2ButtonActionPerformed(evt);
            }
        });
        dialNumberPanel.add(number2Button);

        number3Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lorent/vovo/resource/images/dial/number3.png"))); // NOI18N
        number3Button.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        number3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number3ButtonActionPerformed(evt);
            }
        });
        dialNumberPanel.add(number3Button);

        number4Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lorent/vovo/resource/images/dial/number4.png"))); // NOI18N
        number4Button.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        number4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number4ButtonActionPerformed(evt);
            }
        });
        dialNumberPanel.add(number4Button);

        number5Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lorent/vovo/resource/images/dial/number5.png"))); // NOI18N
        number5Button.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        number5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number5ButtonActionPerformed(evt);
            }
        });
        dialNumberPanel.add(number5Button);

        number6Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lorent/vovo/resource/images/dial/number6.png"))); // NOI18N
        number6Button.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        number6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number6ButtonActionPerformed(evt);
            }
        });
        dialNumberPanel.add(number6Button);

        number7Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lorent/vovo/resource/images/dial/number7.png"))); // NOI18N
        number7Button.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        number7Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number7ButtonActionPerformed(evt);
            }
        });
        dialNumberPanel.add(number7Button);

        number8Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lorent/vovo/resource/images/dial/number8.png"))); // NOI18N
        number8Button.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        number8Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number8ButtonActionPerformed(evt);
            }
        });
        dialNumberPanel.add(number8Button);

        number9Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lorent/vovo/resource/images/dial/number9.png"))); // NOI18N
        number9Button.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        number9Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number9ButtonActionPerformed(evt);
            }
        });
        dialNumberPanel.add(number9Button);

        numberStarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lorent/vovo/resource/images/dial/number_star.png"))); // NOI18N
        numberStarButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        numberStarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberStarButtonActionPerformed(evt);
            }
        });
        dialNumberPanel.add(numberStarButton);

        number0Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lorent/vovo/resource/images/dial/number0.png"))); // NOI18N
        number0Button.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        number0Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number0ButtonActionPerformed(evt);
            }
        });
        dialNumberPanel.add(number0Button);

        numberSharpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lorent/vovo/resource/images/dial/number_sharp.png"))); // NOI18N
        numberSharpButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        numberSharpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberSharpButtonActionPerformed(evt);
            }
        });
        dialNumberPanel.add(numberSharpButton);

        dialPanel.add(dialNumberPanel, java.awt.BorderLayout.CENTER);

        dialCallButtonPanel.setLayout(new java.awt.GridLayout(1, 2));

        acceptButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lorent/vovo/resource/images/dial/call_comein.png"))); // NOI18N
        acceptButton.setText(bundle.getString("PhoneFrame.acceptButton.text")); // NOI18N
        acceptButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        acceptButton.setEnabled(false);
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });
        dialCallButtonPanel.add(acceptButton);

        callButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lorent/vovo/resource/images/dial/call-start.png"))); // NOI18N
        callButton.setText(bundle.getString("PhoneFrame.callButton.text")); // NOI18N
        callButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        callButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                callButtonActionPerformed(evt);
            }
        });
        dialCallButtonPanel.add(callButton);

        handupButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lorent/vovo/resource/images/dial/call-stop.png"))); // NOI18N
        handupButton.setText(bundle.getString("PhoneFrame.handupButton.text")); // NOI18N
        handupButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        handupButton.setEnabled(false);
        handupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handupButtonActionPerformed(evt);
            }
        });
        dialCallButtonPanel.add(handupButton);

        dialPanel.add(dialCallButtonPanel, java.awt.BorderLayout.SOUTH);

        phoneNumberPanel.setLayout(new java.awt.BorderLayout());

        phoneNumberTextField.setFont(new java.awt.Font("宋体", 1, 24));
        phoneNumberTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneNumberTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneNumberTextFieldFocusLost(evt);
            }
        });
        phoneNumberPanel.add(phoneNumberTextField, java.awt.BorderLayout.CENTER);

        undoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/lorent/vovo/resource/images/dial/edit-undo.png"))); // NOI18N
        undoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoButtonActionPerformed(evt);
            }
        });
        phoneNumberPanel.add(undoButton, java.awt.BorderLayout.EAST);

        dialPanel.add(phoneNumberPanel, java.awt.BorderLayout.NORTH);

        mainRightTabbedPane.addTab(bundle.getString("PhoneFrame.mainRightTab.dialTitle"), new javax.swing.ImageIcon(getClass().getResource("/com/lorent/vovo/resource/images/dial/telephone.png")), dialPanel); // NOI18N

        phoneCallHistoryPanel.setLayout(new java.awt.BorderLayout());

        dateInput.setLabel(bundle.getString("PhoneFrame.mainRightTab.callHistory.selectDate")); // NOI18N

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        //phoneCallHistoryPanel.add(searchPanel, java.awt.BorderLayout.PAGE_START);

        callHistoryScrollPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        callHistoryList.setCellRenderer(new MyListCellRander());
        callHistoryList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                callHistoryListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                callHistoryListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                callHistoryListMouseExited(evt);
            }
        });
        callHistoryScrollPanel.setViewportView(callHistoryList);

        phoneCallHistoryPanel.add(callHistoryScrollPanel, java.awt.BorderLayout.CENTER);

        mainRightTabbedPane.addTab(bundle.getString("PhoneFrame.mainRightTab.callHistoryTitle"), new javax.swing.ImageIcon(getClass().getResource("/com/lorent/vovo/resource/images/dial/telephone_history.png")), phoneCallHistoryPanel); // NOI18N

        mainRightPanel.add(mainRightTabbedPane, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(mainRightPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void number1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number1ButtonActionPerformed
        // TODO add your handling code here:
        //phoneNumberTextField.setText(phoneNumberTextField.getText()   + "1");
        setPhoneNumberTextFieldContent("1");
    }//GEN-LAST:event_number1ButtonActionPerformed

    private void number2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number2ButtonActionPerformed
        // TODO add your handling code here:
        //phoneNumberTextField.setText(phoneNumberTextField.getText ( ) + "2");
        setPhoneNumberTextFieldContent("2");
    }//GEN-LAST:event_number2ButtonActionPerformed

    private void number3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number3ButtonActionPerformed
        // TODO add your handling code here:
        //phoneNumberTextField.setText(phoneNumberTextField.getText() + "3");
        setPhoneNumberTextFieldContent("3");
    }//GEN-LAST:event_number3ButtonActionPerformed

    private void number4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number4ButtonActionPerformed
        // TODO add your handling code here:
        //phoneNumberTextField.setText(phoneNumberTextField.getText() + "4");
        setPhoneNumberTextFieldContent("4");
    }//GEN-LAST:event_number4ButtonActionPerformed

    private void number5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number5ButtonActionPerformed
        // TODO add your handling code here:
        //phoneNumberTextField.setText(phoneNumberTextField.getText() + "5");
        setPhoneNumberTextFieldContent("5");
    }//GEN-LAST:event_number5ButtonActionPerformed

    private void number6ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number6ButtonActionPerformed
        // TODO add your handling code here:
        //phoneNumberTextField.setText(phoneNumberTextField.getText() + "6");
        setPhoneNumberTextFieldContent("6");
    }//GEN-LAST:event_number6ButtonActionPerformed

    private void number7ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number7ButtonActionPerformed
        // TODO add your handling code here:
        //phoneNumberTextField.setText(phoneNumberTextField.getText() + "7");
        setPhoneNumberTextFieldContent("7");
    }//GEN-LAST:event_number7ButtonActionPerformed

    private void number8ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number8ButtonActionPerformed
        // TODO add your handling code here:
        //phoneNumberTextField.setText(phoneNumberTextField.getText() + "8");
        setPhoneNumberTextFieldContent("8");
    }//GEN-LAST:event_number8ButtonActionPerformed

    private void number9ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number9ButtonActionPerformed
        // TODO add your handling code here:
        //phoneNumberTextField.setText(phoneNumberTextField.getText() + "9");
        setPhoneNumberTextFieldContent("9");
    }//GEN-LAST:event_number9ButtonActionPerformed

    private void numberStarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberStarButtonActionPerformed
        // TODO add your handling code here:
        //phoneNumberTextField.setText(phoneNumberTextField.getText() + "*");
        setPhoneNumberTextFieldContent("*");
    }//GEN-LAST:event_numberStarButtonActionPerformed

    private void number0ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number0ButtonActionPerformed
        // TODO add your handling code here:
        //phoneNumberTextField.setText(phoneNumberTextField.getText() + "0");
        setPhoneNumberTextFieldContent("0");
    }//GEN-LAST:event_number0ButtonActionPerformed

    private void numberSharpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberSharpButtonActionPerformed
        // TODO add your handling code here:
        //phoneNumberTextField.setText(phoneNumberTextField.getText() + "#");
        setPhoneNumberTextFieldContent("#");
    }//GEN-LAST:event_numberSharpButtonActionPerformed

    private void setPhoneNumberTextFieldContent(String str){
        phoneNumberTextField.replaceSelection(str);
        phoneNumberTextField.requestFocus();
        sindex = phoneNumberTextField.getCaretPosition();
        System.out.println(sindex);
    }
    
    private void undoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoButtonActionPerformed
        // TODO add your handling code here:
        String text = phoneNumberTextField.getText();
//        if (text.length() > 0) {
//            if(text.length() == sindex){
//                text = text.substring(0, sindex-1);
//            }else if(text.length() > sindex){
//                text = text.substring(0, sindex-1) + text.substring(sindex);
//            }
//            
////            phoneNumberTextField.setText(text);
//        }
        if(sindex == 0){
            phoneNumberTextField.setSelectionStart(0);
        }else{
            phoneNumberTextField.setSelectionStart(sindex-1);
        }
        phoneNumberTextField.setSelectionEnd(sindex);
        phoneNumberTextField.replaceSelection("");
        phoneNumberTextField.requestFocus();
    }//GEN-LAST:event_undoButtonActionPerformed

    private void callButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callButtonActionPerformed
        // TODO add your handling code here:
//        Commander commander = new Commander();
//        commander.setClassName("PhoneController");
//        commander.setMethodName("call");
//        commander.setParamter("callNumber", phoneNumberTextField.getText());
//        ControllerFacade.execute(commander);
    	Vovo.exeC("phone", "makeCallInvite", phoneNumberTextField.getText(),null,cameraCloseToggleButton.isSelected());
    }//GEN-LAST:event_callButtonActionPerformed

    private void handupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handupButtonActionPerformed
        // TODO add your handling code here:
//        Commander commander = new Commander();
//        commander.setClassName("PhoneController");
//        commander.setMethodName("handup");
//        ControllerFacade.execute(commander);
    	Vovo.exeC("phone", "hangupCallByPhone");
    }//GEN-LAST:event_handupButtonActionPerformed

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        // TODO add your handling code here:
//        Commander commander = new Commander();
//        commander.setClassName("PhoneController");
//        commander.setMethodName("answer");
//        ControllerFacade.execute(commander);
    	Vovo.exeC("phone", "acceptCallInviteByPhone");
    }//GEN-LAST:event_acceptButtonActionPerformed

    private void cameraOpenToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cameraOpenToggleButtonActionPerformed
        // TODO add your handling code here:
//        Commander commander = new Commander();
//        commander.setClassName("PhoneController");
//        commander.setMethodName("openCamera");
//        ControllerFacade.execute(commander);
    }//GEN-LAST:event_cameraOpenToggleButtonActionPerformed

    private void cameraCloseToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cameraCloseToggleButtonActionPerformed
        // TODO add your handling code here:
//        Commander commander = new Commander();
//        commander.setClassName("PhoneController");
//        commander.setMethodName("closeCamera");
//        ControllerFacade.execute(commander);
    }//GEN-LAST:event_cameraCloseToggleButtonActionPerformed

    private void callHistoryListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_callHistoryListMouseClicked
    	Point point = evt.getPoint();
    	Rectangle cellBounds = callHistoryList.getCellBounds(0, callHistoryList.getLastVisibleIndex());
    	if(!cellBounds.contains(point)){
    		return;
    	}
		int index = callHistoryList.locationToIndex(point);
    	final CallHistoryNodePanel panel = (CallHistoryNodePanel)callHistoryList.getModel().getElementAt(index);
    	callHistoryList.setSelectedIndex(index);
        if(evt.getButton()==MouseEvent.BUTTON3){
            
            JPopupMenu popupMenu = new JPopupMenu("VOVO");
            JMenuItem copyItem = new JMenuItem("复制");
            ActionListener copyListener = new ActionListener() {
            	
            	public void actionPerformed(ActionEvent e) {
            		String callBackPhone = panel.getCallHistoryText();
					StringSelection phone = new StringSelection(
							callBackPhone);
					Clipboard clipboard = Toolkit.getDefaultToolkit()
							.getSystemClipboard();
					clipboard.setContents(phone, null);
            	}
            };
            copyItem.addActionListener(copyListener);
            popupMenu.add(copyItem);
            JMenuItem callItem = new JMenuItem("呼叫");
            ActionListener callListener = new ActionListener() {

                public void actionPerformed(ActionEvent e) {
                	PhoneFrame frame = Vovo.getMyContext().getViewManager().getView(
            				Constants.ViewKey.PhoneFrame.toString());
                    String callBackPhone = panel.getCallHistoryText();
                    phoneNumberTextField.setText(callBackPhone);
                    Vovo.exeC("phone", "makeCallInvite", callBackPhone,null,frame.getCameraCloseToggleButton().isSelected());
                    mainRightTabbedPane.setSelectedIndex(0);
                }
            };
            callItem.addActionListener(callListener);
            popupMenu.add(callItem);
            popupMenu.show(evt.getComponent(), point.x, point.y);
        }else if(evt.getButton()==MouseEvent.BUTTON1&&evt.getClickCount()==2){
            PhoneFrame frame = Vovo.getMyContext().getViewManager().getView(
    				Constants.ViewKey.PhoneFrame.toString());
            String callBackPhone = panel.getCallHistoryText();
            phoneNumberTextField.setText(callBackPhone);
            Vovo.exeC("phone", "makeCallInvite", callBackPhone,null,frame.getCameraCloseToggleButton().isSelected());
            mainRightTabbedPane.setSelectedIndex(0);
        }
    }//GEN-LAST:event_callHistoryListMouseClicked

    private void callHistoryListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_callHistoryListMouseEntered
//        int index = callHistoryList.locationToIndex(evt.getPoint());   
//        callHistoryList.setSelectedIndex(index);
//        callHistoryList.setSelectionBackground(Color.BLUE);
    }//GEN-LAST:event_callHistoryListMouseEntered

    private void callHistoryListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_callHistoryListMouseExited
//        int index = callHistoryList.locationToIndex(evt.getPoint());   
//        callHistoryList.setSelectedIndex(index);
//        callHistoryList.setSelectionBackground(Color.white);
    }//GEN-LAST:event_callHistoryListMouseExited

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
//        Commander commander = new Commander();
//        commander.setClassName("PhoneController");
//        commander.setMethodName("phoneFrameClosed");
//        ControllerFacade.execute(commander);
    }//GEN-LAST:event_formWindowClosed

    private void phoneNumberTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneNumberTextFieldFocusGained
        
        
    }//GEN-LAST:event_phoneNumberTextFieldFocusGained

    private void phoneNumberTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneNumberTextFieldFocusLost
        sindex = phoneNumberTextField.getCaretPosition();
    }//GEN-LAST:event_phoneNumberTextFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PhoneFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PhoneFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PhoneFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PhoneFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PhoneFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JButton callButton;
    private javax.swing.JList callHistoryList;
    private javax.swing.JScrollPane callHistoryScrollPanel;
    private javax.swing.ButtonGroup cameraButtonGroup;
    private javax.swing.JToggleButton cameraCloseToggleButton;
    private javax.swing.JToggleButton cameraOpenToggleButton;
    private DateInput dateInput;
    private javax.swing.JPanel dialCallButtonPanel;
    private javax.swing.JPanel dialNumberPanel;
    private javax.swing.JPanel dialPanel;
    private javax.swing.JButton handupButton;
    private javax.swing.JPanel leftButtomPanel;
    private javax.swing.JPanel leftCenterPanel;
    private javax.swing.JPanel mainLeftPanel;
    private javax.swing.JPanel mainRightPanel;
    private javax.swing.JTabbedPane mainRightTabbedPane;
    private javax.swing.JButton number0Button;
    private javax.swing.JButton number1Button;
    private javax.swing.JButton number2Button;
    private javax.swing.JButton number3Button;
    private javax.swing.JButton number4Button;
    private javax.swing.JButton number5Button;
    private javax.swing.JButton number6Button;
    private javax.swing.JButton number7Button;
    private javax.swing.JButton number8Button;
    private javax.swing.JButton number9Button;
    private javax.swing.JButton numberSharpButton;
    private javax.swing.JButton numberStarButton;
    private javax.swing.JPanel phoneCallHistoryPanel;
    private javax.swing.JPanel phoneNumberPanel;
    private javax.swing.JTextField phoneNumberTextField;
    private ImageAwtPanel screenPanel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JPanel stateInfoPanel;
    private javax.swing.JLabel statusIconLabel;
    private javax.swing.JLabel statusInfoLabel;
    private javax.swing.JButton undoButton;
    private javax.swing.JSlider volumeSlider;
    // End of variables declaration//GEN-END:variables

    public JToggleButton getCameraCloseToggleButton() {
        return cameraCloseToggleButton;
    }

    public JToggleButton getCameraOpenToggleButton() {
        return cameraOpenToggleButton;
    }

    public ImageAwtPanel getScreenPanel() {
        return screenPanel;
    }

    public JLabel getStatusIconLabel() {
        return statusIconLabel;
    }

    public JButton getAcceptButton() {
        return acceptButton;
    }

    public JButton getCallButton() {
        return callButton;
    }

    public JButton getHandupButton() {
        return handupButton;
    }

    public JLabel getStatusInfoLabel() {
        return statusInfoLabel;
    }

    public JTabbedPane getMainRightTabbedPane() {
        return mainRightTabbedPane;
    }

    public JTextField getPhoneNumberTextField() {
        return phoneNumberTextField;
    }

    public JList getCallHistoryList() {
        return callHistoryList;
    }
}
