/*
 * UploadVideoClipDialog.java
 *
 * Created on __DATE__, __TIME__
 */

package com.lorent.vovo.ui;

import java.io.File;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

import com.lorent.vovo.Vovo;
import com.lorent.vovo.util.VovoStringUtil;

/**
 *
 * @author  __USER__
 */
public class UploadVideoClipDialog extends javax.swing.JDialog {

	private String thumbnailImageFilePath;
	private String selectedVideoFilePath;
	private String currentTime;

	public String getVideoDescrption() {
		return videoDescrption;
	}

	public void setVideoDescrption(String videoDescrption) {
		this.videoDescrption = videoDescrption;
	}

	private String videoDescrption;

	public String getCurrentTime() {
		return currentTime;
	}

	public void setCurrentTime(String currentTime) {
		this.currentTime = currentTime;
	}

	public String getSelectedVideoFilePath() {
		return selectedVideoFilePath;
	}

	public void setSelectedVideoFilePath(String selectedVideoFilePath) {
		this.selectedVideoFilePath = selectedVideoFilePath;
	}

	public String getThumbnailImageFilePath() {
		return thumbnailImageFilePath;
	}

	public void setThumbnailImageFilePath(String thumbnailImageFilePath) {
		this.thumbnailImageFilePath = thumbnailImageFilePath;
	}

	/** Creates new form UploadVideoClipDialog */
	public UploadVideoClipDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		selectFileButton = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		filePathTextField = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		titleTextField = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		descriptionTextArea = new javax.swing.JTextArea();
		resultProgressBar = new javax.swing.JProgressBar();
		thumbnailXPanel1 = new org.jdesktop.swingx.JXPanel();
		jPanel2 = new javax.swing.JPanel();
		uploadButton = new javax.swing.JButton();
		cancelButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setAlwaysOnTop(true);
		setResizable(false);

		selectFileButton.setText(VovoStringUtil
				.getUIString("UploadVideoClipDialog.browserfile"));
		selectFileButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				selectFileButtonActionPerformed(evt);
			}
		});

		jLabel1.setText(VovoStringUtil
				.getUIString("UploadVideoClipDialog.uploadfile"));

		filePathTextField.setEnabled(false);

		jLabel2.setText(VovoStringUtil
				.getUIString("UploadVideoClipDialog.title"));

		jLabel3.setText(VovoStringUtil
				.getUIString("UploadVideoClipDialog.description"));

		descriptionTextArea.setColumns(20);
		descriptionTextArea.setRows(5);
		jScrollPane1.setViewportView(descriptionTextArea);

		resultProgressBar.setStringPainted(true);

		thumbnailXPanel1.setBackground(new java.awt.Color(204, 204, 204));
		thumbnailXPanel1.setBorder(new javax.swing.border.LineBorder(
				new java.awt.Color(0, 0, 0), 1, true));

		javax.swing.GroupLayout thumbnailXPanel1Layout = new javax.swing.GroupLayout(
				thumbnailXPanel1);
		thumbnailXPanel1.setLayout(thumbnailXPanel1Layout);
		thumbnailXPanel1Layout.setHorizontalGroup(thumbnailXPanel1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 227, Short.MAX_VALUE));
		thumbnailXPanel1Layout.setVerticalGroup(thumbnailXPanel1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 186, Short.MAX_VALUE));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												thumbnailXPanel1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel1)
														.addComponent(jLabel2)
														.addComponent(jLabel3))
										.addGap(12, 12, 12)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																309,
																Short.MAX_VALUE)
														.addComponent(
																titleTextField,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																309,
																Short.MAX_VALUE)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				filePathTextField,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				189,
																				Short.MAX_VALUE)
																		.addGap(
																				7,
																				7,
																				7)
																		.addComponent(
																				selectFileButton)))
										.addGap(35, 35, 35)).addComponent(
								resultProgressBar,
								javax.swing.GroupLayout.DEFAULT_SIZE, 682,
								Short.MAX_VALUE));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGap(
																												2,
																												2,
																												2)
																										.addComponent(
																												filePathTextField,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								jPanel1Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.BASELINE)
																										.addComponent(
																												jLabel1)
																										.addComponent(
																												selectFileButton)))
																		.addGap(
																				18,
																				18,
																				18)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel2)
																						.addComponent(
																								titleTextField,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel3)
																						.addComponent(
																								jScrollPane1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								127,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addComponent(
																thumbnailXPanel1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												resultProgressBar,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												22,
												javax.swing.GroupLayout.PREFERRED_SIZE)));

		getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

		jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER,
				50, 5));

		uploadButton.setText(VovoStringUtil
				.getUIString("UploadVideoClipDialog.upload"));
		uploadButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				uploadButtonActionPerformed(evt);
			}
		});
		jPanel2.add(uploadButton);

		cancelButton.setText(VovoStringUtil
				.getUIString("UploadVideoClipDialog.cancel"));
		jPanel2.add(cancelButton);

		getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void uploadButtonActionPerformed(java.awt.event.ActionEvent evt) {
		Vovo.exeC("videoclip", "uploadVideoClip", this);
	}

	private void selectFileButtonActionPerformed(java.awt.event.ActionEvent evt) {
		Vovo.exeC("videoclip", "selectedVideoClipFile", this);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				UploadVideoClipDialog dialog = new UploadVideoClipDialog(
						new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton cancelButton;
	private javax.swing.JTextArea descriptionTextArea;
	private javax.swing.JTextField filePathTextField;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JProgressBar resultProgressBar;
	private javax.swing.JButton selectFileButton;
	private org.jdesktop.swingx.JXPanel thumbnailXPanel1;
	private javax.swing.JTextField titleTextField;
	private javax.swing.JButton uploadButton;

	// End of variables declaration//GEN-END:variables
	public javax.swing.JTextField getFilePathTextField() {
		return filePathTextField;
	}

	public org.jdesktop.swingx.JXPanel getThumbnailXPanel1() {
		return thumbnailXPanel1;
	}

	public javax.swing.JProgressBar getResultProgressBar() {
		return resultProgressBar;
	}

	public javax.swing.JTextArea getDescriptionTextArea() {
		return descriptionTextArea;
	}

	public javax.swing.JTextField getTitleTextField() {
		return titleTextField;
	}

}