/*
 * UploadYunLianVideoClipDialog.java
 *
 * Created on __DATE__, __TIME__
 */

package com.lorent.vovo.ui;

import java.awt.Cursor;

import com.lorent.vovo.Vovo;
import com.lorent.vovo.util.Constants;
import com.lorent.vovo.util.VovoStringUtil;

/**
 *
 * @author  __USER__
 */
public class UploadYunLianVideoClipDialog extends javax.swing.JDialog {

	public void setUIEnable(){
		this.getTitleTextField().setEnabled(true);
		this.getDescriptionTextArea().setEnabled(true);
		this.getUploadButton().setEnabled(true);
		this.getSelectFileHyperButton().setEnabled(true);
		this.getCategoryComboBox().setEnabled(true);
	}
	
	public void setUIDisable(){
		this.getTitleTextField().setEnabled(false);
		this.getDescriptionTextArea().setEnabled(false);
		this.getUploadButton().setEnabled(false);
		this.getSelectFileHyperButton().setEnabled(false);
		this.getCategoryComboBox().setEnabled(false);
	}
	
	private String thumbnailImageFilePath;
	private String selectedHighVideoFilePath;
	private String currentTime;
	private String duration;
	private String videoDescrption;
	
	public String getDuration() {
		return duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	public String getVideoDescrption() {
		return videoDescrption;
	}

	public void setVideoDescrption(String videoDescrption) {
		this.videoDescrption = videoDescrption;
	}
	
	public String getCurrentTime() {
		return currentTime;
	}

	public void setCurrentTime(String currentTime) {
		this.currentTime = currentTime;
	}

	public String getSelectedHighVideoFilePath() {
		return selectedHighVideoFilePath;
	}

	public void setSelectedHighVideoFilePath(String selectedHighVideoFilePath) {
		this.selectedHighVideoFilePath = selectedHighVideoFilePath;
	}

	public String getThumbnailImageFilePath() {
		return thumbnailImageFilePath;
	}

	public void setThumbnailImageFilePath(String thumbnailImageFilePath) {
		this.thumbnailImageFilePath = thumbnailImageFilePath;
	}
	
	/** Creates new form UploadYunLianVideoClipDialog */
	public UploadYunLianVideoClipDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		resultProgressBar = new javax.swing.JProgressBar();
		jPanel4 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		titleTextField = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		descriptionTextArea = new javax.swing.JTextArea();
		jLabel5 = new javax.swing.JLabel();
		hyperFilePathTextField = new javax.swing.JTextField();
		selectFileHyperButton = new javax.swing.JButton();
		jLabel6 = new javax.swing.JLabel();
		categoryComboBox = new javax.swing.JComboBox();
		jPanel3 = new javax.swing.JPanel();
		thumbnailXPanel1 = new org.jdesktop.swingx.JXPanel();
		durationLabel = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		uploadButton = new javax.swing.JButton();
		cancelButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jPanel1.setLayout(new java.awt.BorderLayout());

		resultProgressBar.setStringPainted(true);
		jPanel1.add(resultProgressBar, java.awt.BorderLayout.SOUTH);

		jLabel2.setText("*\u6807\u9898");

		jLabel3.setText("*\u63cf\u8ff0");

		descriptionTextArea.setColumns(20);
		descriptionTextArea.setRows(5);
		jScrollPane1.setViewportView(descriptionTextArea);

		jLabel5.setText("*\u89c6\u9891\u6587\u4ef6");

		hyperFilePathTextField.setEnabled(false);

		selectFileHyperButton.setText(VovoStringUtil
				.getUIString("UploadVideoClipDialog.browserfile"));
		selectFileHyperButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						selectFileHyperButtonActionPerformed(evt);
					}
				});

		jLabel6.setText("*\u89c6\u9891\u5206\u7c7b");

		categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel(
				Constants.VIDEO_CATEGORY));

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel5)
																		.addGap(
																				12,
																				12,
																				12)
																		.addComponent(
																				hyperFilePathTextField,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				303,
																				Short.MAX_VALUE)
																		.addGap(
																				7,
																				7,
																				7)
																		.addComponent(
																				selectFileHyperButton))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel6)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				categoryComboBox,
																				0,
																				419,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel2)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				titleTextField,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				443,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel3)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jScrollPane1,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				443,
																				Short.MAX_VALUE)))
										.addContainerGap()));
		jPanel4Layout
				.setVerticalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addGap(
																				2,
																				2,
																				2)
																		.addComponent(
																				hyperFilePathTextField,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel4Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jLabel5)
																		.addComponent(
																				selectFileHyperButton)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel6)
														.addComponent(
																categoryComboBox,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(
																titleTextField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel3)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																127,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(38, Short.MAX_VALUE)));

		jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

		thumbnailXPanel1.setBackground(new java.awt.Color(204, 204, 204));
		thumbnailXPanel1.setBorder(new javax.swing.border.LineBorder(
				new java.awt.Color(0, 0, 0), 1, true));
		thumbnailXPanel1.setToolTipText("300 x 420");
		thumbnailXPanel1.setMaximumSize(new java.awt.Dimension(300, 420));
		thumbnailXPanel1.setMinimumSize(new java.awt.Dimension(300, 420));
		thumbnailXPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				thumbnailXPanel1MouseClicked(evt);
			}

			public void mouseEntered(java.awt.event.MouseEvent evt) {
				thumbnailXPanel1MouseEntered(evt);
			}

			public void mouseExited(java.awt.event.MouseEvent evt) {
				thumbnailXPanel1MouseExited(evt);
			}
		});

		javax.swing.GroupLayout thumbnailXPanel1Layout = new javax.swing.GroupLayout(
				thumbnailXPanel1);
		thumbnailXPanel1.setLayout(thumbnailXPanel1Layout);
		thumbnailXPanel1Layout.setHorizontalGroup(thumbnailXPanel1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 162, Short.MAX_VALUE));
		thumbnailXPanel1Layout.setVerticalGroup(thumbnailXPanel1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 186, Short.MAX_VALUE));

		durationLabel.setText("\u65f6\u957f\uff1a");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addComponent(
																durationLabel,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																thumbnailXPanel1,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																164,
																Short.MAX_VALUE))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												thumbnailXPanel1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												188,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(durationLabel)
										.addContainerGap(47, Short.MAX_VALUE)));

		jPanel1.add(jPanel3, java.awt.BorderLayout.WEST);

		getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

		jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER,
				50, 5));

		uploadButton.setText(VovoStringUtil
				.getUIString("UploadVideoClipDialog.upload"));
		uploadButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				uploadButtonActionPerformed(evt);
			}
		});
		jPanel2.add(uploadButton);

		cancelButton.setText(VovoStringUtil
				.getUIString("UploadVideoClipDialog.cancel"));
		cancelButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cancelButtonActionPerformed(evt);
			}
		});
		jPanel2.add(cancelButton);

		getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
		//		Vovo.exeC("videoclip", "cancelUpLoadVideoClip", this);
		this.dispose();
	}

	private void uploadButtonActionPerformed(java.awt.event.ActionEvent evt) {
		Vovo.exeC("videoclip", "uploadYunLianVideoClip", this);
	}

	private void thumbnailXPanel1MouseExited(java.awt.event.MouseEvent evt) {
		setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
	}

	private void thumbnailXPanel1MouseEntered(java.awt.event.MouseEvent evt) {
		setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
	}

	private void thumbnailXPanel1MouseClicked(java.awt.event.MouseEvent evt) {
		Vovo.exeC("videoclip", "selectedYunLianVideoClipPicture", this);
	}

	private void selectFileHyperButtonActionPerformed(
			java.awt.event.ActionEvent evt) {
		Vovo.exeC("videoclip", "selectedYunLianVideoClipFile", this);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				UploadYunLianVideoClipDialog dialog = new UploadYunLianVideoClipDialog(
						new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton cancelButton;
	private javax.swing.JComboBox categoryComboBox;
	private javax.swing.JTextArea descriptionTextArea;
	private javax.swing.JLabel durationLabel;
	private javax.swing.JTextField hyperFilePathTextField;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JProgressBar resultProgressBar;
	private javax.swing.JButton selectFileHyperButton;
	private org.jdesktop.swingx.JXPanel thumbnailXPanel1;
	private javax.swing.JTextField titleTextField;
	private javax.swing.JButton uploadButton;
	// End of variables declaration//GEN-END:variables

	public org.jdesktop.swingx.JXPanel getThumbnailXPanel1() {
		return thumbnailXPanel1;
	}

	public javax.swing.JProgressBar getResultProgressBar() {
		return resultProgressBar;
	}

	public javax.swing.JTextArea getDescriptionTextArea() {
		return descriptionTextArea;
	}

	public javax.swing.JTextField getTitleTextField() {
		return titleTextField;
	}


	public javax.swing.JButton getUploadButton() {
		return uploadButton;
	}

	public javax.swing.JTextField getHyperFilePathTextField() {
		return hyperFilePathTextField;
	}

	public javax.swing.JButton getSelectFileHyperButton() {
		return selectFileHyperButton;
	}

	public javax.swing.JComboBox getCategoryComboBox() {
		return categoryComboBox;
	}

	public javax.swing.JLabel getDurationLabel() {
		return durationLabel;
	}
}