/*
 * UserSettingDialog.java
 *
 * Created on __DATE__, __TIME__
 */

package com.lorent.vovo.ui;

import java.awt.CardLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;

import javax.swing.ImageIcon;

import org.jdesktop.swingx.painter.ImagePainter;
import org.jdesktop.swingx.painter.ImagePainter.ScaleType;

import com.lorent.common.tree.MemberBean;
import com.lorent.vovo.Vovo;
import com.lorent.vovo.util.Constants;
import com.lorent.vovo.util.DataUtil;
import com.lorent.vovo.util.ImageUtil;

/**
 *
 * @author  __USER__
 */
public class UserSettingDialog extends javax.swing.JDialog {

	/** Creates new form UserSettingDialog */
	public UserSettingDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		try {
			BufferedImage image = Vovo.getMyContext().getDataManager()
					.getValue(
							Constants.DataKey.BACKGROUND_GAUSSIAN_IMAGE
									.toString());
			ImagePainter ip = new ImagePainter(image);
			//			ip.setScaleToFit(true);
			ip.setScaleType(ScaleType.Distort);
			//			this.bannerPanel.setBackgroundPainter(ip);
			backgroundXPanel.setBackgroundPainter(ip);

			BufferedImage whiteImage = Vovo.getMyContext().getDataManager()
					.getValue(Constants.DataKey.WHITE_IMAGE.toString());
			ImagePainter ip1 = new ImagePainter(whiteImage);
			ip1.setScaleToFit(true);
			ip1.setScaleType(ScaleType.Distort);
			baseInfoXPanel.setBackgroundPainter(ip1);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public void setInfo(MemberBean bean) {
		nameTextField.setText(bean.getUsername());
		realNameTextField.setText(bean.getRealName());
		lccnoTextField.setText(bean.getLccAccount());
		departmentTextField.setText(bean.getDeptName());
		postTextField.setText(bean.getPost());
		phoneTextField.setText(bean.getMobile());
		emailTextField.setText(bean.getEmail());
		signTextArea.setText(bean.getSign());
		int sexindex = bean.getGender().equals("male") ? 0 : 1;
		sexComboBox.setSelectedIndex(sexindex);
		ImageUtil.adjustLabelIcon(iconLabel,bean);
		
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		buttonGroup1 = new javax.swing.ButtonGroup();
		backgroundXPanel = new org.jdesktop.swingx.JXPanel();
		leftPanel = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		iconLabel = new javax.swing.JLabel();
		changeLogoButton = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		baseInfoToggleButton = new javax.swing.JToggleButton();
		jPanel4 = new javax.swing.JPanel();
		changePswInfoToggleButton = new javax.swing.JToggleButton();
		jPanel5 = new javax.swing.JPanel();
		baseInfoXPanel = new org.jdesktop.swingx.JXPanel();
		cardPanel = new javax.swing.JPanel();
		baseInfoPanel = new javax.swing.JPanel();
		usernameLabel = new javax.swing.JLabel();
		nameTextField = new javax.swing.JTextField();
		lccnoLabel = new javax.swing.JLabel();
		lccnoTextField = new javax.swing.JTextField();
		departmentLabel = new javax.swing.JLabel();
		departmentTextField = new javax.swing.JTextField();
		phoneLabel = new javax.swing.JLabel();
		phoneTextField = new javax.swing.JTextField();
		emailLabel = new javax.swing.JLabel();
		emailTextField = new javax.swing.JTextField();
		realnameLabel = new javax.swing.JLabel();
		realNameTextField = new javax.swing.JTextField();
		sexLabel = new javax.swing.JLabel();
		postTextField = new javax.swing.JTextField();
		positionLabel = new javax.swing.JLabel();
		signatureLabel = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		signTextArea = new javax.swing.JTextArea();
		sexComboBox = new javax.swing.JComboBox();
		changePswInfoPanel = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		oldPasswordField = new javax.swing.JPasswordField();
		newPasswordField = new javax.swing.JPasswordField();
		jLabel3 = new javax.swing.JLabel();
		confirmPasswordField = new javax.swing.JPasswordField();
		jPanel8 = new javax.swing.JPanel();
		okButton = new javax.swing.JButton();
		cancelButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);

		backgroundXPanel.setLayout(new java.awt.BorderLayout());

		leftPanel.setOpaque(false);
		leftPanel.setLayout(new java.awt.GridBagLayout());

		jPanel2.setOpaque(false);

		iconLabel
				.setIcon(new javax.swing.ImageIcon(
						getClass()
								.getResource(
										"/com/lorent/vovo/resource/images/systemheads/default100.png"))); // NOI18N
		iconLabel.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));
		iconLabel.setMaximumSize(new java.awt.Dimension(100, 100));
		iconLabel.setMinimumSize(new java.awt.Dimension(100, 100));
		iconLabel.setPreferredSize(new java.awt.Dimension(100, 100));

		changeLogoButton.setText(Vovo.getMyContext().getViewManager()
				.getUIString("UserSettingDialog.changeUserLogo"));
		changeLogoButton.setMaximumSize(new java.awt.Dimension(75, 25));
		changeLogoButton.setMinimumSize(new java.awt.Dimension(75, 25));
		changeLogoButton.setPreferredSize(new java.awt.Dimension(75, 25));
		changeLogoButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				changeLogoButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																changeLogoButton,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																101,
																Short.MAX_VALUE)
														.addComponent(
																iconLabel,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																101,
																Short.MAX_VALUE))
										.addContainerGap()));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												iconLabel,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												changeLogoButton,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												25, Short.MAX_VALUE)
										.addContainerGap()));

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		leftPanel.add(jPanel2, gridBagConstraints);

		jPanel3.setLayout(new java.awt.BorderLayout());

		buttonGroup1.add(baseInfoToggleButton);
		baseInfoToggleButton.setSelected(true);
		baseInfoToggleButton.setText(Vovo.getMyContext().getViewManager()
				.getUIString("UserSettingDialog.baseInfo"));
		baseInfoToggleButton.setMaximumSize(new java.awt.Dimension(105, 30));
		baseInfoToggleButton.setMinimumSize(new java.awt.Dimension(105, 30));
		baseInfoToggleButton.setPreferredSize(new java.awt.Dimension(105, 30));
		baseInfoToggleButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						baseInfoToggleButtonActionPerformed(evt);
					}
				});
		jPanel3.add(baseInfoToggleButton, java.awt.BorderLayout.CENTER);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		leftPanel.add(jPanel3, gridBagConstraints);

		jPanel4.setLayout(new java.awt.BorderLayout());

		buttonGroup1.add(changePswInfoToggleButton);
		changePswInfoToggleButton.setText(Vovo.getMyContext().getViewManager()
				.getUIString("UserSettingDialog.changePswInfo"));
		changePswInfoToggleButton
				.setMaximumSize(new java.awt.Dimension(105, 30));
		changePswInfoToggleButton
				.setMinimumSize(new java.awt.Dimension(105, 30));
		changePswInfoToggleButton.setPreferredSize(new java.awt.Dimension(105,
				30));
		changePswInfoToggleButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						changePswInfoToggleButtonActionPerformed(evt);
					}
				});
		jPanel4.add(changePswInfoToggleButton, java.awt.BorderLayout.CENTER);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		leftPanel.add(jPanel4, gridBagConstraints);

		jPanel5.setOpaque(false);

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(
				jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 121,
				Short.MAX_VALUE));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 128,
				Short.MAX_VALUE));

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 1.0;
		leftPanel.add(jPanel5, gridBagConstraints);

		backgroundXPanel.add(leftPanel, java.awt.BorderLayout.WEST);

		baseInfoXPanel.setOpaque(false);
		baseInfoXPanel.setLayout(new java.awt.BorderLayout());

		cardLayout = new java.awt.CardLayout();
		cardPanel.setOpaque(false);
		cardPanel.setLayout(new java.awt.CardLayout());
		cardPanel.setLayout(cardLayout);

		baseInfoPanel.setOpaque(false);

		usernameLabel.setText(Vovo.getMyContext().getViewManager().getUIString(
				"UserSettingDialog.UserName"));

		nameTextField.setText("jTextField1");
		nameTextField.setEnabled(false);

		lccnoLabel.setText(Vovo.getMyContext().getViewManager().getUIString(
				"UserSettingDialog.LccNo"));

		lccnoTextField.setText("jTextField1");
		lccnoTextField.setEnabled(false);

		departmentLabel.setText(Vovo.getMyContext().getViewManager()
				.getUIString("UserSettingDialog.Department"));

		departmentTextField.setText("jTextField1");
		departmentTextField.setEnabled(false);

		phoneLabel.setText(Vovo.getMyContext().getViewManager().getUIString(
				"UserSettingDialog.Phone"));

		phoneTextField.setText("jTextField1");

		emailLabel.setText(Vovo.getMyContext().getViewManager().getUIString(
				"UserSettingDialog.Email"));

		emailTextField.setText("jTextField1");

		realnameLabel.setText(Vovo.getMyContext().getViewManager().getUIString(
				"UserSettingDialog.RealName"));

		realNameTextField.setText("jTextField1");

		sexLabel.setText(Vovo.getMyContext().getViewManager().getUIString(
				"UserSettingDialog.Sex"));

		postTextField.setText("jTextField1");

		positionLabel.setText(Vovo.getMyContext().getViewManager().getUIString(
				"UserSettingDialog.Position"));

		signatureLabel.setText(Vovo.getMyContext().getViewManager()
				.getUIString("UserSettingDialog.signature"));

		signTextArea.setColumns(20);
		signTextArea.setRows(5);
		jScrollPane1.setViewportView(signTextArea);

		sexComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"男", "女" }));

		javax.swing.GroupLayout baseInfoPanelLayout = new javax.swing.GroupLayout(
				baseInfoPanel);
		baseInfoPanel.setLayout(baseInfoPanelLayout);
		baseInfoPanelLayout
				.setHorizontalGroup(baseInfoPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								baseInfoPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												baseInfoPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																signatureLabel)
														.addGroup(
																baseInfoPanelLayout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				false)
																		.addComponent(
																				jScrollPane1,
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				baseInfoPanelLayout
																						.createSequentialGroup()
																						.addGroup(
																								baseInfoPanelLayout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																										.addComponent(
																												usernameLabel)
																										.addComponent(
																												lccnoLabel)
																										.addComponent(
																												departmentLabel)
																										.addComponent(
																												phoneLabel)
																										.addComponent(
																												emailLabel))
																						.addGap(
																								24,
																								24,
																								24)
																						.addGroup(
																								baseInfoPanelLayout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING,
																												false)
																										.addGroup(
																												baseInfoPanelLayout
																														.createSequentialGroup()
																														.addGroup(
																																baseInfoPanelLayout
																																		.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING,
																																				false)
																																		.addComponent(
																																				departmentTextField)
																																		.addComponent(
																																				lccnoTextField)
																																		.addComponent(
																																				nameTextField,
																																				javax.swing.GroupLayout.DEFAULT_SIZE,
																																				138,
																																				Short.MAX_VALUE))
																														.addGap(
																																18,
																																18,
																																18)
																														.addGroup(
																																baseInfoPanelLayout
																																		.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING)
																																		.addGroup(
																																				baseInfoPanelLayout
																																						.createSequentialGroup()
																																						.addComponent(
																																								realnameLabel)
																																						.addGap(
																																								18,
																																								18,
																																								18)
																																						.addComponent(
																																								realNameTextField,
																																								javax.swing.GroupLayout.DEFAULT_SIZE,
																																								160,
																																								Short.MAX_VALUE))
																																		.addGroup(
																																				baseInfoPanelLayout
																																						.createSequentialGroup()
																																						.addGroup(
																																								baseInfoPanelLayout
																																										.createParallelGroup(
																																												javax.swing.GroupLayout.Alignment.TRAILING)
																																										.addComponent(
																																												positionLabel)
																																										.addComponent(
																																												sexLabel))
																																						.addGap(
																																								18,
																																								18,
																																								18)
																																						.addGroup(
																																								baseInfoPanelLayout
																																										.createParallelGroup(
																																												javax.swing.GroupLayout.Alignment.LEADING)
																																										.addGroup(
																																												baseInfoPanelLayout
																																														.createSequentialGroup()
																																														.addComponent(
																																																sexComboBox,
																																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																																javax.swing.GroupLayout.PREFERRED_SIZE)
																																														.addGap(
																																																2,
																																																2,
																																																2))
																																										.addComponent(
																																												postTextField,
																																												javax.swing.GroupLayout.DEFAULT_SIZE,
																																												151,
																																												Short.MAX_VALUE)))))
																										.addComponent(
																												phoneTextField)
																										.addComponent(
																												emailTextField)))))
										.addContainerGap(15, Short.MAX_VALUE)));
		baseInfoPanelLayout
				.setVerticalGroup(baseInfoPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								baseInfoPanelLayout
										.createSequentialGroup()
										.addGroup(
												baseInfoPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																baseInfoPanelLayout
																		.createSequentialGroup()
																		.addGap(
																				12,
																				12,
																				12)
																		.addGroup(
																				baseInfoPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								usernameLabel)
																						.addComponent(
																								realnameLabel)
																						.addComponent(
																								nameTextField,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								realNameTextField,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(
																				18,
																				18,
																				18)
																		.addGroup(
																				baseInfoPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								lccnoLabel)
																						.addComponent(
																								lccnoTextField,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								sexLabel)
																						.addComponent(
																								sexComboBox,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(
																				baseInfoPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								baseInfoPanelLayout
																										.createSequentialGroup()
																										.addGap(
																												56,
																												56,
																												56)
																										.addGroup(
																												baseInfoPanelLayout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.BASELINE)
																														.addComponent(
																																phoneLabel)
																														.addComponent(
																																phoneTextField,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																javax.swing.GroupLayout.PREFERRED_SIZE))
																										.addGap(
																												16,
																												16,
																												16)
																										.addGroup(
																												baseInfoPanelLayout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.BASELINE)
																														.addComponent(
																																emailLabel)
																														.addComponent(
																																emailTextField,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																javax.swing.GroupLayout.PREFERRED_SIZE)))
																						.addGroup(
																								baseInfoPanelLayout
																										.createSequentialGroup()
																										.addGap(
																												18,
																												18,
																												18)
																										.addGroup(
																												baseInfoPanelLayout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.BASELINE)
																														.addComponent(
																																positionLabel)
																														.addComponent(
																																postTextField,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																javax.swing.GroupLayout.PREFERRED_SIZE)))))
														.addGroup(
																baseInfoPanelLayout
																		.createSequentialGroup()
																		.addGap(
																				90,
																				90,
																				90)
																		.addGroup(
																				baseInfoPanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								departmentLabel)
																						.addComponent(
																								departmentTextField,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addGap(18, 18, 18)
										.addComponent(signatureLabel)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												73,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(12, Short.MAX_VALUE)));

		cardPanel.add(baseInfoPanel, "card2");

		changePswInfoPanel.setOpaque(false);

		jLabel1.setText(Vovo.getMyContext().getViewManager().getUIString(
				"UserSettingDialog.oldPassWord"));

		jLabel2.setText(Vovo.getMyContext().getViewManager().getUIString(
				"UserSettingDialog.newPassWord"));

		jLabel3.setText(Vovo.getMyContext().getViewManager().getUIString(
				"UserSettingDialog.confirmPassWord"));

		javax.swing.GroupLayout changePswInfoPanelLayout = new javax.swing.GroupLayout(
				changePswInfoPanel);
		changePswInfoPanel.setLayout(changePswInfoPanelLayout);
		changePswInfoPanelLayout
				.setHorizontalGroup(changePswInfoPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								changePswInfoPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												changePswInfoPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel1)
														.addComponent(jLabel2)
														.addComponent(jLabel3))
										.addGap(42, 42, 42)
										.addGroup(
												changePswInfoPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																confirmPasswordField)
														.addComponent(
																newPasswordField)
														.addComponent(
																oldPasswordField,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																183,
																Short.MAX_VALUE))
										.addContainerGap(214, Short.MAX_VALUE)));
		changePswInfoPanelLayout
				.setVerticalGroup(changePswInfoPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								changePswInfoPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												changePswInfoPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																oldPasswordField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												changePswInfoPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(
																newPasswordField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												changePswInfoPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(
																confirmPasswordField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(201, Short.MAX_VALUE)));

		cardPanel.add(changePswInfoPanel, "card3");

		baseInfoXPanel.add(cardPanel, java.awt.BorderLayout.CENTER);

		jPanel8.setOpaque(false);
		jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

		okButton.setText(Vovo.getMyContext().getViewManager().getUIString(
				"UserSettingDialog.okButton"));
		okButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				okButtonActionPerformed(evt);
			}
		});
		jPanel8.add(okButton);

		cancelButton.setText(Vovo.getMyContext().getViewManager().getUIString(
				"UserSettingDialog.cancelButton"));
		cancelButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cancelButtonActionPerformed(evt);
			}
		});
		jPanel8.add(cancelButton);

		baseInfoXPanel.add(jPanel8, java.awt.BorderLayout.SOUTH);

		backgroundXPanel.add(baseInfoXPanel, java.awt.BorderLayout.CENTER);

		getContentPane().add(backgroundXPanel, java.awt.BorderLayout.CENTER);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void changeLogoButtonActionPerformed(java.awt.event.ActionEvent evt) {
		Vovo.exeC("main", "showChangeHeadImgDialog", this);
	}

	private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {
		Vovo.exeC("main", "doEditUserSetting", this);
	}

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
	}

	private void baseInfoToggleButtonActionPerformed(
			java.awt.event.ActionEvent evt) {
		//		cardLayout.next(baseInfoPanel);
		cardLayout.show(cardPanel, "card2");
	}

	private void changePswInfoToggleButtonActionPerformed(
			java.awt.event.ActionEvent evt) {
		//		cardLayout.next(changePswInfoPanel);
		cardLayout.show(cardPanel, "card3");
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				UserSettingDialog dialog = new UserSettingDialog(
						new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private org.jdesktop.swingx.JXPanel backgroundXPanel;
	private javax.swing.JPanel baseInfoPanel;
	private javax.swing.JToggleButton baseInfoToggleButton;
	private org.jdesktop.swingx.JXPanel baseInfoXPanel;
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.JButton cancelButton;
	private javax.swing.JPanel cardPanel;
	private javax.swing.JButton changeLogoButton;
	private javax.swing.JPanel changePswInfoPanel;
	private javax.swing.JToggleButton changePswInfoToggleButton;
	private javax.swing.JPasswordField confirmPasswordField;
	private javax.swing.JLabel departmentLabel;
	private javax.swing.JTextField departmentTextField;
	private javax.swing.JLabel emailLabel;
	private javax.swing.JTextField emailTextField;
	private javax.swing.JLabel iconLabel;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel lccnoLabel;
	private javax.swing.JTextField lccnoTextField;
	private javax.swing.JPanel leftPanel;
	private javax.swing.JTextField nameTextField;
	private javax.swing.JPasswordField newPasswordField;
	private javax.swing.JButton okButton;
	private javax.swing.JPasswordField oldPasswordField;
	private javax.swing.JLabel phoneLabel;
	private javax.swing.JTextField phoneTextField;
	private javax.swing.JLabel positionLabel;
	private javax.swing.JTextField postTextField;
	private javax.swing.JTextField realNameTextField;
	private javax.swing.JLabel realnameLabel;
	private javax.swing.JComboBox sexComboBox;
	private javax.swing.JLabel sexLabel;
	private javax.swing.JTextArea signTextArea;
	private javax.swing.JLabel signatureLabel;
	private javax.swing.JLabel usernameLabel;
	// End of variables declaration//GEN-END:variables
	private CardLayout cardLayout;

	public javax.swing.JPasswordField getConfirmPasswordField() {
		return confirmPasswordField;
	}

	public javax.swing.JTextField getEmailTextField() {
		return emailTextField;
	}

	public javax.swing.JPasswordField getNewPasswordField() {
		return newPasswordField;
	}

	public javax.swing.JPasswordField getOldPasswordField() {
		return oldPasswordField;
	}

	public javax.swing.JTextField getPhoneTextField() {
		return phoneTextField;
	}

	public javax.swing.JTextField getPostTextField() {
		return postTextField;
	}

	public javax.swing.JTextField getRealNameTextField() {
		return realNameTextField;
	}

	public javax.swing.JComboBox getSexComboBox() {
		return sexComboBox;
	}

	public javax.swing.JTextArea getSignTextArea() {
		return signTextArea;
	}

	public void setIconLabelForChange(String imgName) {
		ImageUtil.adjustLabelIcon(this.iconLabel,
				Constants.SYSTEM_HEAD_IMAGE_PATH_SYS + imgName);
		this.repaint();
	}
	
	public void setIconLabelForChange(BufferedImage resultImage) {
		ImageUtil.adjustLabelIcon(this.iconLabel, resultImage);
		this.repaint();
	}
}