/*
 * VideoCallPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package com.lorent.vovo.ui;

import java.awt.CardLayout;

import com.lorent.vovo.Vovo;
import com.lorent.vovo.util.CountTime;

/**
 *
 * @author  Jack
 */
public class VideoCallPanel extends javax.swing.JPanel {

	public static final String TYPE_CALLER = "caller";
	public static final String TYPE_CALLEE = "callee";
	public static final String TYPE_INCALL = "incall";

	/** Creates new form VideoCallPanel */
	public VideoCallPanel() {
		initComponents();
		calleeInfoLbl.setText(Vovo.getViewManager().getUIString(
				"phone.otherVideoInviting"));
		callerInfoLbl.setText(Vovo.getViewManager().getUIString(
				"phone.waitingOtherAcceptVideoInviting"));
		cancelBtn.setText(Vovo.getViewManager().getUIString(
				"phone.cancel"));
		acceptBtn.setText(Vovo.getViewManager().getUIString(
				"phone.accept"));
		rejectBtn.setText(Vovo.getViewManager().getUIString(
				"phone.reject"));
		hangupBtn.setText(Vovo.getViewManager().getUIString("phone.hangup"));
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		videoPanel = new java.awt.Panel();
		bottomPanel = new javax.swing.JPanel();
		inCallPanel = new javax.swing.JPanel();
		hangupBtn = new javax.swing.JButton();
		controlPanel = new javax.swing.JPanel();
		timeLbl = new javax.swing.JLabel();
		soundControlBtn = new javax.swing.JButton();
		micControlBtn = new javax.swing.JButton();
		videoControlBtn = new javax.swing.JButton();
		fullScreenControlBtn = new javax.swing.JButton();
		exchangeBtn = new javax.swing.JButton();
		calleePanel = new javax.swing.JPanel();
		calleeInfoLbl = new javax.swing.JLabel();
		acceptBtn = new javax.swing.JButton();
		rejectBtn = new javax.swing.JButton();
		callerPanel = new javax.swing.JPanel();
		callerInfoLbl = new javax.swing.JLabel();
		cancelBtn = new javax.swing.JButton();

		setLayout(new java.awt.GridBagLayout());

		videoPanel.setBackground(new java.awt.Color(0, 0, 0));

		javax.swing.GroupLayout videoPanelLayout = new javax.swing.GroupLayout(
				videoPanel);
		videoPanel.setLayout(videoPanelLayout);
		videoPanelLayout.setHorizontalGroup(videoPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 509, Short.MAX_VALUE));
		videoPanelLayout.setVerticalGroup(videoPanelLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 401,
				Short.MAX_VALUE));

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 1.0;
		add(videoPanel, gridBagConstraints);

		bottomPanel.setLayout(new java.awt.CardLayout());

		inCallPanel.setLayout(new java.awt.GridBagLayout());

		hangupBtn.setText("hangup");
		hangupBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				hangupBtnActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		inCallPanel.add(hangupBtn, gridBagConstraints);

		controlPanel
				.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

		timeLbl.setText("03:30");
		controlPanel.add(timeLbl);

		soundControlBtn.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/com/lorent/vovo/resource/images/sound.png"))); // NOI18N
		soundControlBtn.setContentAreaFilled(false);
		soundControlBtn.setMaximumSize(new java.awt.Dimension(16, 16));
		soundControlBtn.setMinimumSize(new java.awt.Dimension(16, 16));
		soundControlBtn.setPreferredSize(new java.awt.Dimension(16, 16));
		controlPanel.add(soundControlBtn);

		micControlBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/com/lorent/vovo/resource/images/mic.png"))); // NOI18N
		micControlBtn.setContentAreaFilled(false);
		micControlBtn.setMaximumSize(new java.awt.Dimension(16, 16));
		micControlBtn.setMinimumSize(new java.awt.Dimension(16, 16));
		micControlBtn.setPreferredSize(new java.awt.Dimension(16, 16));
		controlPanel.add(micControlBtn);

		videoControlBtn.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource(
						"/com/lorent/vovo/resource/images/camera-webcam.png"))); // NOI18N
		videoControlBtn.setContentAreaFilled(false);
		videoControlBtn.setMaximumSize(new java.awt.Dimension(16, 16));
		videoControlBtn.setMinimumSize(new java.awt.Dimension(16, 16));
		videoControlBtn.setPreferredSize(new java.awt.Dimension(16, 16));
		controlPanel.add(videoControlBtn);

		fullScreenControlBtn
				.setIcon(new javax.swing.ImageIcon(getClass().getResource(
						"/com/lorent/vovo/resource/images/fullscreen.png"))); // NOI18N
		fullScreenControlBtn.setContentAreaFilled(false);
		fullScreenControlBtn.setMaximumSize(new java.awt.Dimension(16, 16));
		fullScreenControlBtn.setMinimumSize(new java.awt.Dimension(16, 16));
		fullScreenControlBtn.setPreferredSize(new java.awt.Dimension(16, 16));
		controlPanel.add(fullScreenControlBtn);

		exchangeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/com/lorent/vovo/resource/images/refresh.png"))); // NOI18N
		exchangeBtn.setContentAreaFilled(false);
		exchangeBtn.setMaximumSize(new java.awt.Dimension(16, 16));
		exchangeBtn.setMinimumSize(new java.awt.Dimension(16, 16));
		exchangeBtn.setPreferredSize(new java.awt.Dimension(16, 16));
		controlPanel.add(exchangeBtn);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		inCallPanel.add(controlPanel, gridBagConstraints);

		bottomPanel.add(inCallPanel, "incall");

		calleePanel.setLayout(new java.awt.GridBagLayout());

		calleeInfoLbl.setText("In coming");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		calleePanel.add(calleeInfoLbl, gridBagConstraints);

		acceptBtn.setText("accept");
		acceptBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				acceptBtnActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		calleePanel.add(acceptBtn, gridBagConstraints);

		rejectBtn.setText("reject");
		rejectBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				rejectBtnActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 0;
		calleePanel.add(rejectBtn, gridBagConstraints);

		bottomPanel.add(calleePanel, "callee");

		callerPanel.setLayout(new java.awt.GridBagLayout());

		callerInfoLbl.setText("Waiting");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
		callerPanel.add(callerInfoLbl, gridBagConstraints);

		cancelBtn.setText("cancel");
		cancelBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cancelBtnActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
		callerPanel.add(cancelBtn, gridBagConstraints);

		bottomPanel.add(callerPanel, "caller");

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		add(bottomPanel, gridBagConstraints);
	}// </editor-fold>
	//GEN-END:initComponents

	private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {
		if (listener != null) {
			listener.cancelCallInvite();
		}
	}

	private void rejectBtnActionPerformed(java.awt.event.ActionEvent evt) {
		if (listener != null) {
			listener.rejectCallInvite();
		}
	}

	private void acceptBtnActionPerformed(java.awt.event.ActionEvent evt) {
		if (listener != null) {
			listener.acceptCallInvite();
		}
	}

	private void hangupBtnActionPerformed(java.awt.event.ActionEvent evt) {
		if (listener != null) {
			listener.hangupCall();
		}
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton acceptBtn;
	private javax.swing.JPanel bottomPanel;
	private javax.swing.JLabel calleeInfoLbl;
	private javax.swing.JPanel calleePanel;
	private javax.swing.JLabel callerInfoLbl;
	private javax.swing.JPanel callerPanel;
	private javax.swing.JButton cancelBtn;
	private javax.swing.JPanel controlPanel;
	private javax.swing.JButton exchangeBtn;
	private javax.swing.JButton fullScreenControlBtn;
	private javax.swing.JButton hangupBtn;
	private javax.swing.JPanel inCallPanel;
	private javax.swing.JButton micControlBtn;
	private javax.swing.JButton rejectBtn;
	private javax.swing.JButton soundControlBtn;
	private javax.swing.JLabel timeLbl;
	private javax.swing.JButton videoControlBtn;
	private java.awt.Panel videoPanel;
	// End of variables declaration//GEN-END:variables

	private CountTime countTime;

	public void showPanel(String type) {
		CardLayout layout = (CardLayout) bottomPanel.getLayout();
		layout.show(bottomPanel, type);
		if (TYPE_INCALL.equals(type)) {
			startCountTime();
		}
	}

	private EventListener listener;

	public interface EventListener {
		void rejectCallInvite();

		void acceptCallInvite();

		void cancelCallInvite();

		void hangupCall();
	}

	public void setEventListener(EventListener listener) {
		this.listener = listener;
	}

	public void startCountTime() {
		countTime = new CountTime(timeLbl);
		countTime.start();
	}

	public String stopCountTime() {
		if (countTime != null) {
			countTime.cancel();
			return this.timeLbl.getText();
		}else{
			return null;
		}
	}

	public java.awt.Panel getVideoPanel() {
		return videoPanel;
	}
	
	
}