/*
 * VodFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package com.lorent.vovo.ui;

import java.awt.Toolkit;

import com.lorent.vovo.VovoVod;
import com.lorent.vovo.util.Constants;

/**
 *
 * @author  __USER__
 */
public class VodFrame extends javax.swing.JFrame {

	private int pageIndex = 0;
	private int maxPageIndex = -1;

	public void setMaxPageIndex(int maxPageIndex) {
		this.maxPageIndex = maxPageIndex;
	}

	/** Creates new form VodFrame */
	public VodFrame() {
		initComponents();
		setIconImage(Toolkit.getDefaultToolkit().createImage(
				getClass().getResource(Constants.TRAYICON_PATH)));
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		buttomPanel = new javax.swing.JPanel();
		topVodListPanel = new javax.swing.JPanel();
		navigatePagePanel = new javax.swing.JPanel();
		lastPageButton = new javax.swing.JButton();
		navigateNumberPanel = new javax.swing.JPanel();
		nextPageButton = new javax.swing.JButton();
		vodListPanel = new javax.swing.JPanel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);

		javax.swing.GroupLayout buttomPanelLayout = new javax.swing.GroupLayout(
				buttomPanel);
		buttomPanel.setLayout(buttomPanelLayout);
		buttomPanelLayout.setHorizontalGroup(buttomPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 688, Short.MAX_VALUE));
		buttomPanelLayout.setVerticalGroup(buttomPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 31, Short.MAX_VALUE));

		getContentPane().add(buttomPanel, java.awt.BorderLayout.PAGE_END);

		topVodListPanel.setLayout(new java.awt.BorderLayout());

		lastPageButton.setText("\u4e0a\u4e00\u9875");
		lastPageButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				lastPageButtonActionPerformed(evt);
			}
		});
		navigatePagePanel.add(lastPageButton);

		navigateNumberPanel.setLayout(new java.awt.FlowLayout(
				java.awt.FlowLayout.CENTER, 5, 0));
		navigatePagePanel.add(navigateNumberPanel);

		nextPageButton.setText("\u4e0b\u4e00\u9875");
		nextPageButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				nextPageButtonActionPerformed(evt);
			}
		});
		navigatePagePanel.add(nextPageButton);

		topVodListPanel.add(navigatePagePanel, java.awt.BorderLayout.PAGE_END);

		vodListPanel.setLayout(new java.awt.GridLayout(0, 4));
		topVodListPanel.add(vodListPanel, java.awt.BorderLayout.CENTER);

		getContentPane().add(topVodListPanel, java.awt.BorderLayout.CENTER);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void nextPageButtonActionPerformed(java.awt.event.ActionEvent evt) {
		pageIndex++;
		if (pageIndex > maxPageIndex) {
			pageIndex =  maxPageIndex;
		}
		VovoVod.exeC("vod", "nextVodListPage", this,pageIndex);
	}

	private void lastPageButtonActionPerformed(java.awt.event.ActionEvent evt) {
		pageIndex--;
		if (pageIndex < 0) {
			pageIndex = 0;
		}
		VovoVod.exeC("vod", "lastVodListPage", this,pageIndex);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new VodFrame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JPanel buttomPanel;
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.JButton lastPageButton;
	private javax.swing.JPanel navigateNumberPanel;
	private javax.swing.JPanel navigatePagePanel;
	private javax.swing.JButton nextPageButton;
	private javax.swing.JPanel topVodListPanel;
	private javax.swing.JPanel vodListPanel;

	// End of variables declaration//GEN-END:variables
	public javax.swing.JPanel getVodListPanel() {
		return vodListPanel;
	}

	public javax.swing.JPanel getNavigateNumberPanel() {
		return navigateNumberPanel;
	}
}