/*
 * BackgroundPanel.java
 *
 * Created on __DATE__, __TIME__
 */

package com.lorent.lvmc.ui;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.TexturePaint;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;

import javax.swing.ImageIcon;

import com.lorent.lvmc.util.ConfigUtil;


/**
 *
 * @author  __USER__
 */
public class BackgroundPanel extends javax.swing.JPanel {

	ImageIcon backImg = null;
	
	public void setBackImg(ImageIcon image){
		backImg = image;
		this.revalidate();
		this.repaint();
	}
	
	/** Creates new form BackgroundPanel */
	public BackgroundPanel() {
		backImg = new ImageIcon(Toolkit.getDefaultToolkit().createImage(getClass().getResource(ConfigUtil.getProperty("background_img_path"))));
		initComponents();
	}
	
	public void paintComponent(Graphics g) {
//		loadPic(strPicName, g);
		loadPic(backImg, g);
	}
	
	public void loadPic(ImageIcon icon, Graphics g){
		if (icon != null) {
			final Image image = icon.getImage();
			final int imgWidth = image.getWidth(null);
			final int imgHeight = image.getHeight(null);
			if (imgWidth > 0 && imgHeight > 0) {
				final BufferedImage bufImage = new BufferedImage(imgWidth, imgHeight, BufferedImage.TYPE_INT_RGB);
				bufImage.createGraphics().drawImage(image, 0, 0, null);
				final TexturePaint texturePaint = new TexturePaint(bufImage, 
						new Rectangle(0, 0, bufImage.getWidth(), bufImage.getHeight()));
				final Graphics2D g2 = (Graphics2D)g.create();
				g2.setPaint(texturePaint);
				g2.fill(g2.getClip());
			}
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 300,
				Short.MAX_VALUE));
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	// End of variables declaration//GEN-END:variables

}