/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DefaultLayoutMeetingPanel.java
 *
 * Created on 2011-12-9, 15:46:22
 */
package com.lorent.lvmc.ui;

import java.awt.BorderLayout;
import javax.swing.JFrame;

/**
 *
 * @author Administrator
 */
public class DefaultLayoutMeetingPanel extends javax.swing.JPanel {

    /** Creates new form DefaultLayoutMeetingPanel */
    public DefaultLayoutMeetingPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainSplitPane = new javax.swing.JSplitPane();
        rightSplitPane = new javax.swing.JSplitPane();
        centerSplitPane = new javax.swing.JSplitPane();
        charPanel = new javax.swing.JPanel();
        mainTabbedPane = new javax.swing.JTabbedPane();
        whiteBoradPanel = new javax.swing.JPanel();
        vedioLayoutPanel = new javax.swing.JPanel();
        leftTabbedPane = new javax.swing.JTabbedPane();
        userPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        mainSplitPane.setDividerLocation(200);
        mainSplitPane.setOneTouchExpandable(true);

        rightSplitPane.setDividerLocation(400);
        rightSplitPane.setOneTouchExpandable(true);

        centerSplitPane.setDividerLocation(400);
        centerSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        centerSplitPane.setOneTouchExpandable(true);

        javax.swing.GroupLayout charPanelLayout = new javax.swing.GroupLayout(charPanel);
        charPanel.setLayout(charPanelLayout);
        charPanelLayout.setHorizontalGroup(
            charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );
        charPanelLayout.setVerticalGroup(
            charPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 136, Short.MAX_VALUE)
        );

        centerSplitPane.setRightComponent(charPanel);

        javax.swing.GroupLayout whiteBoradPanelLayout = new javax.swing.GroupLayout(whiteBoradPanel);
        whiteBoradPanel.setLayout(whiteBoradPanelLayout);
        whiteBoradPanelLayout.setHorizontalGroup(
            whiteBoradPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );
        whiteBoradPanelLayout.setVerticalGroup(
            whiteBoradPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 373, Short.MAX_VALUE)
        );

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/lorent/lvmc/resource/i18n/view"); // NOI18N
        mainTabbedPane.addTab(bundle.getString("com.lorent.lvmc.ui.DefaultLayoutMeetingPanel.whiteBoradPanel.tabTitle"), whiteBoradPanel); // NOI18N

        centerSplitPane.setLeftComponent(mainTabbedPane);

        rightSplitPane.setLeftComponent(centerSplitPane);

        javax.swing.GroupLayout vedioLayoutPanelLayout = new javax.swing.GroupLayout(vedioLayoutPanel);
        vedioLayoutPanel.setLayout(vedioLayoutPanelLayout);
        vedioLayoutPanelLayout.setHorizontalGroup(
            vedioLayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 179, Short.MAX_VALUE)
        );
        vedioLayoutPanelLayout.setVerticalGroup(
            vedioLayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );

        rightSplitPane.setRightComponent(vedioLayoutPanel);

        mainSplitPane.setRightComponent(rightSplitPane);

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );

        leftTabbedPane.addTab(bundle.getString("com.lorent.lvmc.ui.DefaultLayoutMeetingPanel.userPanel.tabTitle"), userPanel); // NOI18N

        mainSplitPane.setLeftComponent(leftTabbedPane);

        add(mainSplitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane centerSplitPane;
    private javax.swing.JPanel charPanel;
    private javax.swing.JTabbedPane leftTabbedPane;
    private javax.swing.JSplitPane mainSplitPane;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JSplitPane rightSplitPane;
    private javax.swing.JPanel userPanel;
    private javax.swing.JPanel vedioLayoutPanel;
    private javax.swing.JPanel whiteBoradPanel;
    // End of variables declaration//GEN-END:variables
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JFrame jFrame = new JFrame();
                jFrame.setSize(400, 300);
                jFrame.getContentPane().add(new DefaultLayoutMeetingPanel(),BorderLayout.CENTER);
                jFrame.setVisible(true);
            }
        });
    }
}
