/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SelectItemPanel.java
 *
 * Created on 2011-12-20, 9:40:12
 */
package com.lorent.lvmc.ui;

import com.lorent.lvmc.bean.OptionDto;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author test
 */
public class SelectItemPanel extends javax.swing.JPanel {

	/** Creates new form SelectItemPanel */
	public SelectItemPanel() {
		initComponents();
		this.jPanel2.setVisible(false);
		//        initItem();
	}

	private voteMainPanel mainPanel;
	private VoteTabItemPane voteTabItemPane;

	public SelectItemPanel(voteMainPanel mainPanel) {
		initComponents();
		this.mainPanel = mainPanel;
		this.jPanel2.setVisible(false);
		//        initItem();
	}

	public SelectItemPanel(VoteTabItemPane voteTabItemPane) {
		initComponents();
		this.voteTabItemPane = voteTabItemPane;
		this.jPanel2.setVisible(false);
		//        initItem();
	}

	//	public void initItem() {
	//		this.jPanel1.setLayout(new GridLayout(3, 1));
	//		this.jPanel1.add(new SingleSelectPanel());
	//		this.jPanel1.add(new SingleSelectPanel());
	//		this.jPanel1.add(new SingleSelectPanel());
	//		this.jPanel1.validate();
	//	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jLabel7 = new javax.swing.JLabel();
		jPanel4 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();

		jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1,
				javax.swing.BoxLayout.Y_AXIS));

		jPanel2.setLayout(new java.awt.BorderLayout());

		jLabel5.setText("\u7edf\u8ba1\u7ed3\u679c:");
		jLabel5.setPreferredSize(new java.awt.Dimension(60, 17));
		jPanel2.add(jLabel5, java.awt.BorderLayout.WEST);

		jLabel6.setText(" ");
		jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
		jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
		jPanel2.add(jLabel6, java.awt.BorderLayout.CENTER);

		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/com/lorent/lvmc/resource/images/vote_icon/edit-4.png"))); // NOI18N
		jButton1.setBorderPainted(false);
		jButton1.setContentAreaFilled(false);
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2
				.setIcon(new javax.swing.ImageIcon(
						getClass()
								.getResource(
										"/com/lorent/lvmc/resource/images/vote_icon/list-remove-3.png"))); // NOI18N
		jButton2.setBorderPainted(false);
		jButton2.setContentAreaFilled(false);
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel7.setText("        ");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jLabel7,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																49,
																Short.MAX_VALUE)
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																jPanel3Layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				21,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				21,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap()));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel3Layout.createSequentialGroup().addGroup(
						jPanel3Layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								false).addComponent(jButton2,
								javax.swing.GroupLayout.Alignment.LEADING, 0,
								0, Short.MAX_VALUE).addComponent(jButton1,
								javax.swing.GroupLayout.Alignment.LEADING,
								javax.swing.GroupLayout.PREFERRED_SIZE, 23,
								Short.MAX_VALUE)).addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jLabel7,
								javax.swing.GroupLayout.PREFERRED_SIZE, 5,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));

		jLabel1.setFont(new java.awt.Font("宋体", 0, 14));
		jLabel1.setText("\u8868\u51b3\u9879");

		jLabel3.setText(" \u63cf \u8ff0:");

		jLabel4.setText("jLabel4");

		jLabel2.setFont(new java.awt.Font("宋体", 0, 14));
		jLabel2.setText("jLabel2");

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel1)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				jLabel2))
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel3,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				42,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel4,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)))
										.addContainerGap(609, Short.MAX_VALUE)));
		jPanel4Layout
				.setVerticalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(jLabel2))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(jLabel4))));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addComponent(
												jPanel3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												jPanel4,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE))
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(19, 19, 19)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jPanel2,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				745,
																				Short.MAX_VALUE)
																		.addGap(
																				10,
																				10,
																				10))
														.addComponent(
																jPanel1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																755,
																Short.MAX_VALUE))));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(jPanel3,
																0, 41,
																Short.MAX_VALUE)
														.addComponent(
																jPanel4,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanel1,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												65, Short.MAX_VALUE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanel2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)));
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		//        System.out.print(this.getItemPanelKey());
		this.voteTabItemPane.showUpdateSelectItemDlg(this.getItemPanelKey());
	}//GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		this.voteTabItemPane.deleteSeletedPanel(this.getItemPanelKey());
	}//GEN-LAST:event_jButton2ActionPerformed

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	// End of variables declaration//GEN-END:variables

	private int itemPanelType;
	private String itemPanelKey;
	private String id;
	private List<MultiSelectPanel> multiSelectPanelList = new ArrayList<MultiSelectPanel>();
	private List<SingleSelectPanel> singleSelectPanelList = new ArrayList<SingleSelectPanel>();
	private List<YesorNoPanel> yesorNoPanelList = new ArrayList<YesorNoPanel>();
	private OptionDto[] optionDtos;

	public JButton getjButton1() {
		return jButton1;
	}

	public JButton getjButton2() {
		return jButton2;
	}

	public List<SingleSelectPanel> getSingleSelectPanelList() {
		return singleSelectPanelList;
	}

	public void setSingleSelectPanelList(
			List<SingleSelectPanel> singleSelectPanelList) {
		this.singleSelectPanelList = singleSelectPanelList;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public OptionDto[] getOptionDtos() {
		return optionDtos;
	}

	public void setOptionDtos(OptionDto[] optionDtos) {
		this.optionDtos = optionDtos;
	}

	public String getItemPanelKey() {
		return itemPanelKey;
	}

	public void setItemPanelKey(String itemPanelKey) {
		this.itemPanelKey = itemPanelKey;
	}

	public List<MultiSelectPanel> getMultiSelectPanelList() {
		return multiSelectPanelList;
	}

	public List<YesorNoPanel> getYesorNoPanelList() {
		return yesorNoPanelList;
	}

	public JLabel getjLabel1() {
		return jLabel1;
	}

	public int getItemPanelType() {
		return itemPanelType;
	}

	public void setItemPanelType(int itemPanelType) {
		this.itemPanelType = itemPanelType;
	}

	public JLabel getjLabel2() {
		return jLabel2;
	}

	public void setjLabel2(JLabel jLabel2) {
		this.jLabel2 = jLabel2;
	}

	public JLabel getjLabel4() {
		return jLabel4;
	}

	public void setjLabel4(JLabel jLabel4) {
		this.jLabel4 = jLabel4;
	}

	public JPanel getjPanel1() {
		return jPanel1;
	}

	public void setjPanel1(JPanel jPanel1) {
		this.jPanel1 = jPanel1;
	}

	public ButtonGroup getButtonGroup1() {
		return buttonGroup1;
	}

	public JLabel getjLabel5() {
		return jLabel5;
	}

	public JLabel getjLabel6() {
		return jLabel6;
	}

	public JPanel getjPanel2() {
		return jPanel2;
	}

}
