/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ShareFileListItem.java
 *
 * Created on 2011-12-22, 14:16:52
 */
package com.lorent.lvmc.ui;

import java.io.File;

import javax.swing.JPanel;
import javax.swing.JProgressBar;

import org.apache.log4j.Logger;

import com.lorent.common.util.StringUtil;
import com.lorent.lvmc.controller.ControllerFacade;

/**
 *
 * @author Administrator
 */
public class ShareFileListItem extends javax.swing.JPanel {

	private static Logger log = Logger.getLogger(ShareFileListItem.class);

	private String absolutePath;
	private String uniqueFileID;

	public String getUniqueFileID() {
		return uniqueFileID;
	}

	public void setUniqueFileID(String uniqueFileID) {
		this.uniqueFileID = uniqueFileID;
	}

	public String getAbsolutePath() {
		return absolutePath;
	}

	public void setAbsolutePath(String absolutePath) {
		this.absolutePath = absolutePath;
	}

	/** Creates new form ShareFileListItem */
	public ShareFileListItem() {
		initComponents();
		progressBar.setVisible(false);
		cancelTransferXHyperlink.setVisible(false);
		openXHyperlink.setVisible(false);
		openPathXHyperlink.setVisible(false);
	}

	public void setFileName(String filename) {
		fileNameLabel.setText(filename);
	}

	public String getFileName() {
		return fileNameLabel.getText();
	}

	private void setIcon(String ext) {
		String name = ext.toLowerCase();
		if (name.equals("doc")) {
			iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(
					"/com/lorent/lvmc/resource/images/files/report-word.png")));
		} else if (name.equals("pdf")) {
			iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(
					"/com/lorent/lvmc/resource/images/files/acroread.png")));
		} else if (name.equals("jpg") || name.equals("png")
				|| name.equals("jpeg") || name.equals("bmp")) {
			iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(
					"/com/lorent/lvmc/resource/images/files/picture.png")));
		} else if (name.equals("mp3") || name.equals("wav")) {
			iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(
					"/com/lorent/lvmc/resource/images/files/kbemusedsrv.png")));
		}

	}

	public void setIconFromFileName(String filename) {
		if (filename != null || !filename.equals("")) {
			int lastIndexOf = filename.lastIndexOf(".");
			if (lastIndexOf != -1) {
				String extStr = filename.substring(lastIndexOf + 1);
				setIcon(extStr);
			}
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		leftPanel = new javax.swing.JPanel();
		iconLabel = new javax.swing.JLabel();
		fileNameLabel = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		progressBar = new javax.swing.JProgressBar();
		jPanel2 = new javax.swing.JPanel();
		cancelTransferXHyperlink = new org.jdesktop.swingx.JXHyperlink();
		openXHyperlink = new org.jdesktop.swingx.JXHyperlink();
		openPathXHyperlink = new org.jdesktop.swingx.JXHyperlink();

		setMaximumSize(new java.awt.Dimension(2147483647, 27));
		setOpaque(false);
		setLayout(new java.awt.BorderLayout());

		leftPanel.setOpaque(false);
		leftPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

		iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/com/lorent/lvmc/resource/images/files/paste-plain.png"))); // NOI18N
		leftPanel.add(iconLabel);

		fileNameLabel.setText("\u6587\u4ef6\u540d");
		leftPanel.add(fileNameLabel);

		add(leftPanel, java.awt.BorderLayout.WEST);

		jPanel1.setOpaque(false);
		jPanel1.setLayout(new java.awt.BorderLayout());

		progressBar.setMaximumSize(new java.awt.Dimension(32767, 16));
		progressBar.setMinimumSize(new java.awt.Dimension(10, 16));
		progressBar.setOpaque(true);
		progressBar.setPreferredSize(new java.awt.Dimension(146, 16));
		progressBar.setStringPainted(true);
		jPanel1.add(progressBar, java.awt.BorderLayout.CENTER);

		jPanel2.setOpaque(false);

		cancelTransferXHyperlink.setText("\u53d6\u6d88");
		cancelTransferXHyperlink
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						cancelTransferXHyperlinkActionPerformed(evt);
					}
				});
		jPanel2.add(cancelTransferXHyperlink);

		openXHyperlink.setText("\u6253\u5f00");
		openXHyperlink.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				openXHyperlinkActionPerformed(evt);
			}
		});
		jPanel2.add(openXHyperlink);

		openPathXHyperlink.setText("\u6253\u5f00\u6587\u4ef6\u5939");
		openPathXHyperlink
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						openPathXHyperlinkActionPerformed(evt);
					}
				});
		jPanel2.add(openPathXHyperlink);

		jPanel1.add(jPanel2, java.awt.BorderLayout.EAST);

		add(jPanel1, java.awt.BorderLayout.CENTER);
	}// </editor-fold>
	//GEN-END:initComponents

	private void openPathXHyperlinkActionPerformed(
			java.awt.event.ActionEvent evt) {
		File file = new File(getAbsolutePath());
		String path = file.getParent();
		try {
			String cmd = "cmd.exe /c explorer " + StringUtil.convertFilePath2DOSCommandStr(path);
			log.info("打开文件夹："+cmd);
			Runtime.getRuntime().exec(cmd);
		} catch (Exception e) {
			log.error("打开文件夹:", e);
			e.printStackTrace();
		}
	}

	private void openXHyperlinkActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			String cmd = "cmd.exe /c " + StringUtil.convertFilePath2DOSCommandStr(getAbsolutePath());
			log.info("打开文件：" + cmd);
			Runtime.getRuntime().exec(cmd);
		} catch (Exception e) {
			log.error("打开文件:", e);
			e.printStackTrace();
		}
	}

	private void cancelTransferXHyperlinkActionPerformed(
			java.awt.event.ActionEvent evt) {
		ControllerFacade.execute("shareFileListController",
				"cancelTransferShareFile", getUniqueFileID());
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private org.jdesktop.swingx.JXHyperlink cancelTransferXHyperlink;
	private javax.swing.JLabel fileNameLabel;
	private javax.swing.JLabel iconLabel;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel leftPanel;
	private org.jdesktop.swingx.JXHyperlink openPathXHyperlink;
	private org.jdesktop.swingx.JXHyperlink openXHyperlink;
	private javax.swing.JProgressBar progressBar;

	// End of variables declaration//GEN-END:variables

	public JPanel getLeftPanel() {
		return leftPanel;
	}

	public JProgressBar getProgressBar() {
		return progressBar;
	}

	public void setTextForeground(java.awt.Color color) {
		fileNameLabel.setForeground(color);
	}

	public org.jdesktop.swingx.JXHyperlink getCancelTransferXHyperlink() {
		return cancelTransferXHyperlink;
	}

	public org.jdesktop.swingx.JXHyperlink getOpenPathXHyperlink() {
		return openPathXHyperlink;
	}

	public org.jdesktop.swingx.JXHyperlink getOpenXHyperlink() {
		return openXHyperlink;
	}

}
