/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * singleSelectPanel.java
 *
 * Created on 2011-12-20, 9:55:17
 */
package com.lorent.lvmc.ui;

import java.awt.Color;

import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;

import com.lorent.lvmc.util.Constants;

/**
 *
 * @author test
 */
public class SingleSelectPanel extends javax.swing.JPanel {

	/** Creates new form singleSelectPanel */
	public SingleSelectPanel() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		singleGroup1 = new javax.swing.ButtonGroup();
		jRadioButton1 = new javax.swing.JRadioButton();

		singleGroup1.add(jRadioButton1);
		jRadioButton1.setText("jRadioButton1");
		jRadioButton1.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				jRadioButton1FocusGained(evt);
			}

			public void focusLost(java.awt.event.FocusEvent evt) {
				jRadioButton1FocusLost(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addGap(40, 40, 40).addComponent(
						jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE,
						554, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
	}// </editor-fold>
	//GEN-END:initComponents

	private void jRadioButton1FocusLost(java.awt.event.FocusEvent evt) {
		this.jRadioButton1.setBackground(bgcolor);
	}

	private Color bgcolor = null;
	private void jRadioButton1FocusGained(java.awt.event.FocusEvent evt) {
//		if(null==bgcolor)
		this.bgcolor=this.jRadioButton1.getBackground();
//		this.jRadioButton1.setBackground(Constants.SELECTEDBACKGROUNDCOLOR);
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JRadioButton jRadioButton1;
	private javax.swing.ButtonGroup singleGroup1;
	// End of variables declaration//GEN-END:variables

	private String id;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public JRadioButton getjRadioButton1() {
		return jRadioButton1;
	}

	public void setjRadioButton1(JRadioButton jRadioButton1) {
		this.jRadioButton1 = jRadioButton1;
	}

	public ButtonGroup getSingleGroup1() {
		return singleGroup1;
	}

	public void setSingleGroup1(ButtonGroup singleGroup1) {
		this.singleGroup1 = singleGroup1;
	}

}
