/*
 * VideoSetupDialog.java
 *
 * Created on __DATE__, __TIME__
 */

package com.lorent.lvmc.ui;

import java.util.Enumeration;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.Map;

import javax.swing.AbstractButton;
import javax.swing.JLabel;
import javax.swing.JRadioButton;

import com.lorent.lvmc.controller.ControllerFacade;
import com.lorent.lvmc.controller.ViewManager;
import com.lorent.lvmc.util.ConfigUtil;
import com.lorent.lvmc.util.Constants;
import com.lorent.lvmc.util.DataUtil;
import com.lorent.lvmc.util.MathUtil;
import com.lorent.lvmc.util.StringUtil;

/**
 *
 * @author  __USER__
 */
public class VideoSetupDialog extends javax.swing.JDialog {

	private double bw;
	private JRadioButton[] highQualityButtons = new JRadioButton[] {
			new JRadioButton("1920*1080"), new JRadioButton("1280*720"),
			new JRadioButton("640*360"), new JRadioButton("960*540"),
			new JRadioButton("1280*800"), new JRadioButton("1024*768") };
	private JRadioButton[] standardQualityButtons = new JRadioButton[] {
			new JRadioButton("720*576"), new JRadioButton("640*480"),
			new JRadioButton("352*288"), new JRadioButton("320*240"),
			new JRadioButton("176*144"), new JRadioButton("160*120") };

	/** Creates new form VideoSetupDialog */
	public VideoSetupDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		Hashtable labelTable = new Hashtable();
		labelTable.put(new Integer(1), new JLabel("1"));
		labelTable.put(new Integer(30), new JLabel("30"));
		this.jSlider1.setLabelTable(labelTable);
		Hashtable labelTable1 = new Hashtable();
		labelTable1.put(new Integer(1), new JLabel("1K"));
		labelTable1.put(new Integer(70), new JLabel("1M"));
		labelTable1.put(new Integer(100), new JLabel("4M"));
		this.jSlider2.setLabelTable(labelTable1);
		initData();
	}

	public void initData() {
		String pixelType = ConfigUtil.getProperty(
				com.lorent.lvmc.util.Constants.VideoParam.PixelType.toString(),
				StringUtil.getUIString("video.pixel.standardquality"));
		this.jComboBox1.setSelectedItem(pixelType);
		int frameRate = ConfigUtil.getIntProperty(
				Constants.VideoParam.FrameRate.toString(), 15);
		this.jSlider1.setValue(frameRate);
		try {
			double bandWidth = Double.parseDouble(ConfigUtil
					.getProperty("VideoBitrate","128"));
			int bandWidthValue = computeBandWidthSliderValue(bandWidth);
			this.jSlider2.setValue(bandWidthValue);
			setBandwidthLabel(bandWidth);
		} catch (Exception ex) {
			
		}
		setPixelValueButton();
		
		setFrameRateLabelValue();
	}
	
	public void setBandwidthLabel(double bandWidth){
		bw = bandWidth;
		if(bandWidth>=1024){
			bandWidth = bandWidth / 1024;
			bandWidth = MathUtil.getTwoDecimal(bandWidth);
			this.bandwidthLabel.setText(bandWidth + " Mbps");
		}else{
			this.bandwidthLabel.setText(bandWidth + " Kbps");
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		pixelbuttonGroup = new javax.swing.ButtonGroup();
		jPanel1 = new javax.swing.JPanel();
		jPanel3 = new javax.swing.JPanel();
		jPanel4 = new javax.swing.JPanel();
		jPanel6 = new javax.swing.JPanel();
		jPanel7 = new javax.swing.JPanel();
		jPanel8 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jPanel9 = new javax.swing.JPanel();
		jComboBox1 = new javax.swing.JComboBox();
		jPanel10 = new javax.swing.JPanel();
		pixelButtonPanel = new javax.swing.JPanel();
		jRadioButton1 = new javax.swing.JRadioButton();
		jRadioButton2 = new javax.swing.JRadioButton();
		jRadioButton3 = new javax.swing.JRadioButton();
		jRadioButton4 = new javax.swing.JRadioButton();
		jRadioButton5 = new javax.swing.JRadioButton();
		jRadioButton6 = new javax.swing.JRadioButton();
		jPanel13 = new javax.swing.JPanel();
		jPanel14 = new javax.swing.JPanel();
		jPanel15 = new javax.swing.JPanel();
		jPanel11 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jPanel16 = new javax.swing.JPanel();
		jSlider1 = new javax.swing.JSlider();
		jPanel17 = new javax.swing.JPanel();
		framerateLabel = new javax.swing.JLabel();
		jPanel18 = new javax.swing.JPanel();
		jPanel19 = new javax.swing.JPanel();
		jPanel20 = new javax.swing.JPanel();
		jPanel21 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		jPanel22 = new javax.swing.JPanel();
		jSlider2 = new javax.swing.JSlider();
		jPanel23 = new javax.swing.JPanel();
		bandwidthLabel = new javax.swing.JLabel();
		jPanel24 = new javax.swing.JPanel();
		jPanel25 = new javax.swing.JPanel();
		jPanel26 = new javax.swing.JPanel();
		jPanel27 = new javax.swing.JPanel();
		jLabel6 = new javax.swing.JLabel();
		jPanel28 = new javax.swing.JPanel();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jPanel29 = new javax.swing.JPanel();
		jPanel30 = new javax.swing.JPanel();
		jPanel5 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle(StringUtil
				.getUIString("SystemSetupPopupMenu.videoSetupItem.txt"));
		setResizable(false);

		jPanel1.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));
		jPanel1.setLayout(new java.awt.GridBagLayout());

		jPanel3.setMinimumSize(new java.awt.Dimension(0, 10));
		jPanel3.setPreferredSize(new java.awt.Dimension(100, 10));

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 495,
				Short.MAX_VALUE));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 10,
				Short.MAX_VALUE));

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		jPanel1.add(jPanel3, gridBagConstraints);

		jPanel4.setLayout(new java.awt.GridBagLayout());

		jPanel6.setMinimumSize(new java.awt.Dimension(10, 0));
		jPanel6.setPreferredSize(new java.awt.Dimension(10, 100));

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(
				jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout.setHorizontalGroup(jPanel6Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 10,
				Short.MAX_VALUE));
		jPanel6Layout.setVerticalGroup(jPanel6Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 224,
				Short.MAX_VALUE));

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
		gridBagConstraints.weighty = 1.0;
		jPanel4.add(jPanel6, gridBagConstraints);

		jPanel7.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(204, 204, 204)));
		jPanel7.setLayout(new java.awt.GridBagLayout());

		jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

		jLabel1.setFont(new java.awt.Font("微软雅黑", 1, 12));
		jLabel1.setText("\u5927\u5c0f\uff08\u50cf\u7d20\uff09");
		jPanel8.add(jLabel1);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		jPanel7.add(jPanel8, gridBagConstraints);

		jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				StringUtil.getUIString("video.pixel.highquality"),
				StringUtil.getUIString("video.pixel.standardquality") }));
		jComboBox1.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				jComboBox1ItemStateChanged(evt);
			}
		});
		jPanel9.add(jComboBox1);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		jPanel7.add(jPanel9, gridBagConstraints);

		jPanel10.setMinimumSize(new java.awt.Dimension(0, 10));
		jPanel10.setPreferredSize(new java.awt.Dimension(100, 10));

		javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(
				jPanel10);
		jPanel10.setLayout(jPanel10Layout);
		jPanel10Layout.setHorizontalGroup(jPanel10Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 100,
				Short.MAX_VALUE));
		jPanel10Layout.setVerticalGroup(jPanel10Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 10,
				Short.MAX_VALUE));

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		jPanel7.add(jPanel10, gridBagConstraints);

		pixelButtonPanel.setLayout(new java.awt.GridLayout(6, 1));

		pixelbuttonGroup.add(jRadioButton1);
		jRadioButton1.setText("1920*1080");
		pixelButtonPanel.add(jRadioButton1);

		pixelbuttonGroup.add(jRadioButton2);
		jRadioButton2.setText("1280*720");
		pixelButtonPanel.add(jRadioButton2);

		pixelbuttonGroup.add(jRadioButton3);
		jRadioButton3.setText("640*360");
		pixelButtonPanel.add(jRadioButton3);

		pixelbuttonGroup.add(jRadioButton4);
		jRadioButton4.setText("960*540");
		pixelButtonPanel.add(jRadioButton4);

		pixelbuttonGroup.add(jRadioButton5);
		jRadioButton5.setText("1280*800");
		pixelButtonPanel.add(jRadioButton5);

		pixelbuttonGroup.add(jRadioButton6);
		jRadioButton6.setText("1024*768");
		pixelButtonPanel.add(jRadioButton6);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 4;
		jPanel7.add(pixelButtonPanel, gridBagConstraints);

		jPanel13.setMinimumSize(new java.awt.Dimension(0, 10));
		jPanel13.setPreferredSize(new java.awt.Dimension(100, 10));

		javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(
				jPanel13);
		jPanel13.setLayout(jPanel13Layout);
		jPanel13Layout.setHorizontalGroup(jPanel13Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 100,
				Short.MAX_VALUE));
		jPanel13Layout.setVerticalGroup(jPanel13Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 16,
				Short.MAX_VALUE));

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 5;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 1.0;
		jPanel7.add(jPanel13, gridBagConstraints);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
		gridBagConstraints.weighty = 1.0;
		jPanel4.add(jPanel7, gridBagConstraints);

		jPanel14.setMaximumSize(new java.awt.Dimension(10, 32767));
		jPanel14.setMinimumSize(new java.awt.Dimension(10, 0));
		jPanel14.setPreferredSize(new java.awt.Dimension(10, 100));

		javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(
				jPanel14);
		jPanel14.setLayout(jPanel14Layout);
		jPanel14Layout.setHorizontalGroup(jPanel14Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 10,
				Short.MAX_VALUE));
		jPanel14Layout.setVerticalGroup(jPanel14Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 224,
				Short.MAX_VALUE));

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
		gridBagConstraints.weighty = 1.0;
		jPanel4.add(jPanel14, gridBagConstraints);

		jPanel15.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(204, 204, 204)));
		jPanel15.setLayout(new java.awt.GridBagLayout());

		jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

		jLabel2.setFont(new java.awt.Font("微软雅黑", 1, 12));
		jLabel2.setText("\u5e27\u7387\uff08\u5e27/\u79d2\uff09");
		jPanel11.add(jLabel2);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		jPanel15.add(jPanel11, gridBagConstraints);

		jPanel16.setMinimumSize(new java.awt.Dimension(25, 170));
		jPanel16.setPreferredSize(new java.awt.Dimension(100, 170));
		jPanel16.setLayout(new java.awt.GridBagLayout());

		jSlider1.setMajorTickSpacing(29);
		jSlider1.setMaximum(30);
		jSlider1.setMinimum(1);
		jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
		jSlider1.setPaintLabels(true);
		jSlider1.setPaintTicks(true);
		jSlider1.setValue(15);
		jSlider1.setMaximumSize(new java.awt.Dimension(25, 100));
		jSlider1.setMinimumSize(new java.awt.Dimension(25, 0));
		jSlider1.setPreferredSize(new java.awt.Dimension(38, 0));
		jSlider1.setVerifyInputWhenFocusTarget(false);
		jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				jSlider1StateChanged(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
		gridBagConstraints.weighty = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
		jPanel16.add(jSlider1, gridBagConstraints);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		jPanel15.add(jPanel16, gridBagConstraints);

		framerateLabel.setText("5 \u5e27/\u79d2");
		jPanel17.add(framerateLabel);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		jPanel15.add(jPanel17, gridBagConstraints);

		javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(
				jPanel18);
		jPanel18.setLayout(jPanel18Layout);
		jPanel18Layout.setHorizontalGroup(jPanel18Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 0,
				Short.MAX_VALUE));
		jPanel18Layout.setVerticalGroup(jPanel18Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 0,
				Short.MAX_VALUE));

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 1.0;
		jPanel15.add(jPanel18, gridBagConstraints);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 3;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
		gridBagConstraints.weighty = 1.0;
		jPanel4.add(jPanel15, gridBagConstraints);

		jPanel19.setMinimumSize(new java.awt.Dimension(10, 0));
		jPanel19.setPreferredSize(new java.awt.Dimension(10, 100));

		javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(
				jPanel19);
		jPanel19.setLayout(jPanel19Layout);
		jPanel19Layout.setHorizontalGroup(jPanel19Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 10,
				Short.MAX_VALUE));
		jPanel19Layout.setVerticalGroup(jPanel19Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 224,
				Short.MAX_VALUE));

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 4;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
		gridBagConstraints.weighty = 1.0;
		jPanel4.add(jPanel19, gridBagConstraints);

		jPanel20.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(204, 204, 204)));
		jPanel20.setLayout(new java.awt.GridBagLayout());

		jPanel21.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

		jLabel4.setFont(new java.awt.Font("微软雅黑", 1, 12));
		jLabel4.setText("\u5bbd\u5e26\uff08bps\uff09");
		jPanel21.add(jLabel4);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		jPanel20.add(jPanel21, gridBagConstraints);

		jPanel22.setMinimumSize(new java.awt.Dimension(25, 170));
		jPanel22.setPreferredSize(new java.awt.Dimension(100, 170));
		jPanel22.setLayout(new java.awt.GridBagLayout());

		jSlider2.setMajorTickSpacing(99);
		jSlider2.setMinimum(1);
		jSlider2.setOrientation(javax.swing.JSlider.VERTICAL);
		jSlider2.setPaintLabels(true);
		jSlider2.setPaintTicks(true);
		jSlider2.setMinimumSize(new java.awt.Dimension(100, 0));
		jSlider2.setPreferredSize(new java.awt.Dimension(50, 0));
		jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				jSlider2StateChanged(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
		gridBagConstraints.weighty = 1.0;
		gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 0);
		jPanel22.add(jSlider2, gridBagConstraints);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		jPanel20.add(jPanel22, gridBagConstraints);

		bandwidthLabel.setText("2.0 Mbps");
		jPanel23.add(bandwidthLabel);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		jPanel20.add(jPanel23, gridBagConstraints);

		javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(
				jPanel24);
		jPanel24.setLayout(jPanel24Layout);
		jPanel24Layout.setHorizontalGroup(jPanel24Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 0,
				Short.MAX_VALUE));
		jPanel24Layout.setVerticalGroup(jPanel24Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 0,
				Short.MAX_VALUE));

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 1.0;
		jPanel20.add(jPanel24, gridBagConstraints);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 5;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
		gridBagConstraints.weighty = 1.0;
		jPanel4.add(jPanel20, gridBagConstraints);

		jPanel25.setMinimumSize(new java.awt.Dimension(10, 0));
		jPanel25.setPreferredSize(new java.awt.Dimension(10, 100));

		javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(
				jPanel25);
		jPanel25.setLayout(jPanel25Layout);
		jPanel25Layout.setHorizontalGroup(jPanel25Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 10,
				Short.MAX_VALUE));
		jPanel25Layout.setVerticalGroup(jPanel25Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 224,
				Short.MAX_VALUE));

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 6;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
		gridBagConstraints.weighty = 1.0;
		jPanel4.add(jPanel25, gridBagConstraints);

		jPanel26.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(204, 204, 204)));
		jPanel26.setMinimumSize(new java.awt.Dimension(137, 137));
		jPanel26.setPreferredSize(new java.awt.Dimension(137, 100));
		jPanel26.setLayout(new java.awt.GridBagLayout());

		jPanel27.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

		jLabel6.setFont(new java.awt.Font("微软雅黑", 1, 12));
		jLabel6.setText("\u8d28\u91cf");
		jPanel27.add(jLabel6);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		jPanel26.add(jPanel27, gridBagConstraints);

		jPanel28.setLayout(new java.awt.GridLayout(5, 1, 0, 15));

		jButton3.setFont(new java.awt.Font("宋体", 0, 14));
		jButton3
				.setText("\u89c6\u9891\u91c7\u96c6\u8bbe\u5907\u3002\u3002\u3002");
		jButton3.setEnabled(false);
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		jPanel28.add(jButton3);

		jButton4.setFont(new java.awt.Font("宋体", 0, 14));
		jButton4
				.setText("\u89c6\u9891\u91c7\u96c6\u683c\u5f0f\u3002\u3002\u3002");
		jButton4.setEnabled(false);
		jPanel28.add(jButton4);

		jButton5.setFont(new java.awt.Font("宋体", 0, 14));
		jButton5.setText("\u9884\u89c8\u7a97\u53e3");
		jButton5.setEnabled(false);
		jPanel28.add(jButton5);

		jButton6.setFont(new java.awt.Font("宋体", 0, 14));
		jButton6.setText("\u89c6\u9891");
		jButton6.setEnabled(false);
		jPanel28.add(jButton6);

		jButton7.setFont(new java.awt.Font("宋体", 0, 14));
		jButton7.setText("\u7535\u89c6\u8c03\u8c10");
		jButton7.setEnabled(false);
		jPanel28.add(jButton7);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
		jPanel26.add(jPanel28, gridBagConstraints);

		javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(
				jPanel29);
		jPanel29.setLayout(jPanel29Layout);
		jPanel29Layout.setHorizontalGroup(jPanel29Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 0,
				Short.MAX_VALUE));
		jPanel29Layout.setVerticalGroup(jPanel29Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 0,
				Short.MAX_VALUE));

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 1.0;
		jPanel26.add(jPanel29, gridBagConstraints);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 7;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
		gridBagConstraints.weighty = 1.0;
		jPanel4.add(jPanel26, gridBagConstraints);

		jPanel30.setMinimumSize(new java.awt.Dimension(10, 0));
		jPanel30.setPreferredSize(new java.awt.Dimension(10, 100));

		javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(
				jPanel30);
		jPanel30.setLayout(jPanel30Layout);
		jPanel30Layout.setHorizontalGroup(jPanel30Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 12,
				Short.MAX_VALUE));
		jPanel30Layout.setVerticalGroup(jPanel30Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 224,
				Short.MAX_VALUE));

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 8;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 1.0;
		jPanel4.add(jPanel30, gridBagConstraints);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 1.0;
		jPanel1.add(jPanel4, gridBagConstraints);

		jPanel5.setMinimumSize(new java.awt.Dimension(0, 10));
		jPanel5.setPreferredSize(new java.awt.Dimension(100, 10));

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(
				jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 495,
				Short.MAX_VALUE));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 10,
				Short.MAX_VALUE));

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		jPanel1.add(jPanel5, gridBagConstraints);

		getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

		jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT,
				15, 5));

		jButton1.setText(StringUtil
				.getUIString("InviteDialog.inviteButton.txt"));
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jPanel2.add(jButton1);

		jButton2.setText(StringUtil
				.getUIString("InviteDialog.cancelButton.txt"));
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		jPanel2.add(jButton2);

		getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
		Map<String, String> paras = new HashMap<String, String>();
		String pixelType = (String) this.jComboBox1.getSelectedItem();
		paras.put(Constants.VideoParam.PixelType.toString(), pixelType);
		Enumeration<AbstractButton> buttons = this.pixelbuttonGroup
				.getElements();
		while (buttons.hasMoreElements()) {
			JRadioButton button = (JRadioButton) buttons.nextElement();
			if (button.isSelected()) {
				paras.put(Constants.VideoParam.PixelValue.toString(), button
						.getText());
			}
		}
		paras.put(Constants.VideoParam.FrameRate.toString(), String
				.valueOf(this.jSlider1.getValue()));
		paras
				.put(Constants.VideoParam.BandWidth.toString(), String
						.valueOf(bw));
		ControllerFacade.execute("videoAudioSetupController", "setVideoParas",
				paras);
	}

	private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {
		setBandWidthLabelValue();
		if (!this.jSlider2.getValueIsAdjusting()) {
			Map<String, String> paras = new HashMap<String, String>();
			paras.put(Constants.VideoParam.BandWidth.toString(), String
					.valueOf(bw));
			ControllerFacade.execute("videoAudioSetupController",
					"setVideoParas", paras);
		}
		//		javax.swing.JSlider source = (javax.swing.JSlider) evt.getSource();
		//		double fps = (double) source.getValue();
		//		double value = computeBandWidth(fps);
		//		if(value>=1024){
		//			value = value/1024;
		//			value = MathUtil.getTwoDecimal(value);
		//			this.bandwidthLabel.setText(String.valueOf(value) + " Mbps");
		//		}else{
		//			this.bandwidthLabel.setText(String.valueOf(value)
		//					+ " Kbps");
		//		}
		//		if (value >= 1) {
		//			value = MathUtil.getTwoDecimal(value);
		//			this.bandwidthLabel.setText(String.valueOf(value) + " Mbps");
		//		} else {
		//			if(fps==1){
		//				this.bandwidthLabel.setText(String.valueOf(1)
		//						+ " Kbps");
		//			}else{
		//				this.bandwidthLabel.setText(String.valueOf((int) (value * 1000))
		//						+ " Kbps");
		//			}
		//			
		//		}

	}

	private void setBandWidthLabelValue() {
		double fps = (double) this.jSlider2.getValue();
		double value = computeBandWidth(fps);
//		bw = value;
//		System.out.println("bw=============" + bw);
//		if (value >= 1024) {
//			value = value / 1024;
//			value = MathUtil.getTwoDecimal(value);
//			this.bandwidthLabel.setText(value + " Mbps");
//		} else {
//			this.bandwidthLabel.setText(value + " Kbps");
//		}
		setBandwidthLabel(value);
	}

	private double computeBandWidth(double fps) {
		double bandWidth = 0;
		if (fps >= 70) {
			bandWidth = 3 * (fps - 70) * 1024 / 30 + 1024;
		} else {
			if (fps == 1) {
				bandWidth = 1;
			} else {
				bandWidth = (int) (fps * 1024 / 70);
			}
		}
		return bandWidth;
	}

	private int computeBandWidthSliderValue(double bandWidth) {
		int value = 1;
		if (bandWidth >= 1024) {
			value = (int) (70 + (bandWidth - 1024) / 1024 / 3 * 30);
		} else {
			value = (int) (bandWidth / 1024 * 70);
		}
		return value;
	}
	
	private void setPixelValueButton(){
		String pixelType = (String) this.jComboBox1.getSelectedItem();
		pixelbuttonGroup = null;
		pixelbuttonGroup = new javax.swing.ButtonGroup();
		this.pixelButtonPanel.removeAll();
		pixelButtonPanel.setLayout(new java.awt.GridLayout(6, 1));
		String videowidth = ConfigUtil.getProperty("videowidth", "352");
		String videoheight = ConfigUtil.getProperty("videoheight", "288");
		String pixelValue = videowidth + "*" + videoheight;

		if (pixelType.equals(StringUtil
				.getUIString("video.pixel.highquality"))) {
			for (int i = 0; i < this.highQualityButtons.length; i++) {
				pixelbuttonGroup.add(highQualityButtons[i]);
				this.pixelButtonPanel.add(highQualityButtons[i]);
				if (pixelValue != null
						&& pixelValue.equals(highQualityButtons[i]
								.getText())) {
					highQualityButtons[i].setSelected(true);
				}
			}
		} else if (pixelType.equals(StringUtil
				.getUIString("video.pixel.standardquality"))) {
			for (int i = 0; i < this.standardQualityButtons.length; i++) {
				pixelbuttonGroup.add(standardQualityButtons[i]);
				this.pixelButtonPanel.add(standardQualityButtons[i]);
				if (pixelValue != null
						&& pixelValue.equals(standardQualityButtons[i]
								.getText())) {
					standardQualityButtons[i].setSelected(true);
				}
			}
		}
		this.pixelButtonPanel.revalidate();
		this.pixelButtonPanel.repaint();
		this.repaint();
	}

	private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {
		if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
			setPixelValueButton();
		}
	}

	private void setFrameRateLabelValue() {
		int fps = (int) this.jSlider1.getValue();
		this.framerateLabel.setText(String.valueOf(fps) + " 帧/秒");
	}

	private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {
		setFrameRateLabelValue();
		if (!this.jSlider1.getValueIsAdjusting()) {
			Map<String, String> paras = new HashMap<String, String>();
			paras.put(Constants.VideoParam.FrameRate.toString(), String
					.valueOf(this.jSlider1.getValue()));
			ControllerFacade.execute("videoAudioSetupController",
					"setVideoParas", paras);
		}
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		VideoAttributeSetupDialog dialog = new VideoAttributeSetupDialog(
				(java.awt.Frame) DataUtil.getTopWindow(), true);
		try {
			ViewManager.setWindowCenterLocation(dialog);
		} catch (Exception e1) {
			e1.printStackTrace();
		}
		dialog.setVisible(true);
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		this.dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				VideoSetupDialog dialog = new VideoSetupDialog(
						new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel bandwidthLabel;
	private javax.swing.JLabel framerateLabel;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel10;
	private javax.swing.JPanel jPanel11;
	private javax.swing.JPanel jPanel13;
	private javax.swing.JPanel jPanel14;
	private javax.swing.JPanel jPanel15;
	private javax.swing.JPanel jPanel16;
	private javax.swing.JPanel jPanel17;
	private javax.swing.JPanel jPanel18;
	private javax.swing.JPanel jPanel19;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel20;
	private javax.swing.JPanel jPanel21;
	private javax.swing.JPanel jPanel22;
	private javax.swing.JPanel jPanel23;
	private javax.swing.JPanel jPanel24;
	private javax.swing.JPanel jPanel25;
	private javax.swing.JPanel jPanel26;
	private javax.swing.JPanel jPanel27;
	private javax.swing.JPanel jPanel28;
	private javax.swing.JPanel jPanel29;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel30;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JPanel jPanel9;
	private javax.swing.JRadioButton jRadioButton1;
	private javax.swing.JRadioButton jRadioButton2;
	private javax.swing.JRadioButton jRadioButton3;
	private javax.swing.JRadioButton jRadioButton4;
	private javax.swing.JRadioButton jRadioButton5;
	private javax.swing.JRadioButton jRadioButton6;
	private javax.swing.JSlider jSlider1;
	private javax.swing.JSlider jSlider2;
	private javax.swing.JPanel pixelButtonPanel;
	private javax.swing.ButtonGroup pixelbuttonGroup;
	// End of variables declaration//GEN-END:variables

}