/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VncViewPanel.java
 *
 * Created on 2012-1-12, 9:43:27
 */
package com.lorent.lvmc.ui;

import com.lorent.lvmc.controller.ControllerFacade;
import java.awt.Panel;
import java.awt.ScrollPane;
import java.awt.event.ItemEvent;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JToggleButton;

/**
 *
 * @author Administrator
 */
public class VncViewPanel extends javax.swing.JPanel {

	/** Creates new form VncViewPanel */
	public VncViewPanel() {
		initComponents();
		//        topPanel.setVisible(false);
		revertViewButton.setVisible(false);
		closeButton.setVisible(false);
	}

	private String username;

	private int connectTimes;

	private boolean connected;

	public int getConnectTimes() {
		return connectTimes;
	}

	public void setConnectTimes(int connectTimes) {
		this.connectTimes = connectTimes;
	}

	public boolean isConnected() {
		return connected;
	}

	public void setConnected(boolean connected) {
		this.connected = connected;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		desktopScrollPane = new java.awt.ScrollPane();
		topPanel = new javax.swing.JPanel();
		jToolBar1 = new javax.swing.JToolBar();
		askforControlButton = new javax.swing.JButton();
		stopControlButton = new javax.swing.JButton();
		maxViewButton = new javax.swing.JButton();
		revertViewButton = new javax.swing.JButton();
		closeButton = new javax.swing.JButton();
		titletext = new javax.swing.JLabel();
		statusText = new javax.swing.JLabel();
		jToolBar2 = new javax.swing.JToolBar();
		jToolBar3 = new javax.swing.JToolBar();
		jToolBar4 = new javax.swing.JToolBar();

		setLayout(new java.awt.BorderLayout());
		add(desktopScrollPane, java.awt.BorderLayout.CENTER);

		topPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

		jToolBar1.setFloatable(false);

		askforControlButton.setText("\u7533\u8bf7\u63a7\u5236");
		askforControlButton.setEnabled(false);
		askforControlButton.setFocusable(false);
		askforControlButton
				.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		askforControlButton.setMaximumSize(new java.awt.Dimension(81, 25));
		askforControlButton.setMinimumSize(new java.awt.Dimension(81, 25));
		askforControlButton.setPreferredSize(new java.awt.Dimension(81, 25));
		askforControlButton
				.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		askforControlButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						askforControlButtonActionPerformed(evt);
					}
				});
		jToolBar1.add(askforControlButton);

		stopControlButton.setText("\u505c\u6b62\u63a7\u5236");
		stopControlButton.setEnabled(false);
		stopControlButton.setFocusable(false);
		stopControlButton
				.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		stopControlButton.setMaximumSize(new java.awt.Dimension(81, 25));
		stopControlButton.setMinimumSize(new java.awt.Dimension(81, 25));
		stopControlButton.setPreferredSize(new java.awt.Dimension(81, 25));
		stopControlButton
				.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		stopControlButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						stopControlButtonActionPerformed(evt);
					}
				});
		jToolBar1.add(stopControlButton);

		maxViewButton.setText("\u6700\u5927\u5316");
		maxViewButton.setEnabled(false);
		maxViewButton.setFocusable(false);
		maxViewButton
				.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		maxViewButton.setMaximumSize(new java.awt.Dimension(81, 25));
		maxViewButton.setMinimumSize(new java.awt.Dimension(81, 25));
		maxViewButton.setPreferredSize(new java.awt.Dimension(81, 25));
		maxViewButton
				.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		maxViewButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				maxViewButtonActionPerformed(evt);
			}
		});
		jToolBar1.add(maxViewButton);

		revertViewButton.setText("\u8fd8\u539f");
		revertViewButton.setEnabled(false);
		revertViewButton.setFocusable(false);
		revertViewButton
				.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		revertViewButton.setMaximumSize(new java.awt.Dimension(81, 25));
		revertViewButton.setMinimumSize(new java.awt.Dimension(81, 25));
		revertViewButton.setPreferredSize(new java.awt.Dimension(81, 25));
		revertViewButton
				.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		revertViewButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				revertViewButtonActionPerformed(evt);
			}
		});
		jToolBar1.add(revertViewButton);

		closeButton.setText("\u5173\u95ed");
		closeButton.setEnabled(false);
		closeButton.setFocusable(false);
		closeButton
				.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		closeButton.setMaximumSize(new java.awt.Dimension(81, 25));
		closeButton.setMinimumSize(new java.awt.Dimension(81, 25));
		closeButton.setPreferredSize(new java.awt.Dimension(81, 25));
		closeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		closeButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				closeButtonActionPerformed(evt);
			}
		});
		jToolBar1.add(closeButton);
		jToolBar1.add(titletext);
		jToolBar1.add(statusText);

		topPanel.add(jToolBar1);

		jToolBar2.setFloatable(false);
		topPanel.add(jToolBar2);

		jToolBar3.setFloatable(false);
		topPanel.add(jToolBar3);

		jToolBar4.setFloatable(false);
		topPanel.add(jToolBar4);

		add(topPanel, java.awt.BorderLayout.NORTH);
	}// </editor-fold>
	//GEN-END:initComponents

	private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {
		ControllerFacade.execute("shareDesktopController", "closeDesktopView",
				getUsername());
	}

	private void revertViewButtonActionPerformed(java.awt.event.ActionEvent evt) {
		ControllerFacade.execute("shareDesktopController",
				"revertVncViewPanel", this);
	}

	private void maxViewButtonActionPerformed(java.awt.event.ActionEvent evt) {
		ControllerFacade.execute("shareDesktopController", "maxVncViewPanel",
				this);
	}

	private void askforControlButtonActionPerformed(
			java.awt.event.ActionEvent evt) {//GEN-FIRST:event_askforControlButtonActionPerformed
		ControllerFacade.execute("shareDesktopController",
				"askforControlDesktop", getUsername());
	}//GEN-LAST:event_askforControlButtonActionPerformed

	private void stopControlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopControlButtonActionPerformed
		ControllerFacade.execute("shareDesktopController",
				"stopControlRemoteDesktop", getUsername());
	}//GEN-LAST:event_stopControlButtonActionPerformed

	public ScrollPane getDesktopScrollPane() {
		return desktopScrollPane;
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton askforControlButton;
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.JButton closeButton;
	private java.awt.ScrollPane desktopScrollPane;
	private javax.swing.JToolBar jToolBar1;
	private javax.swing.JToolBar jToolBar2;
	private javax.swing.JToolBar jToolBar3;
	private javax.swing.JToolBar jToolBar4;
	private javax.swing.JButton maxViewButton;
	private javax.swing.JButton revertViewButton;
	private javax.swing.JLabel statusText;
	private javax.swing.JButton stopControlButton;
	private javax.swing.JLabel titletext;
	private javax.swing.JPanel topPanel;

	// End of variables declaration//GEN-END:variables

	public JButton getAskforControlButton() {
		return askforControlButton;
	}

	public JButton getStopControlButton() {
		return stopControlButton;
	}

	public javax.swing.JLabel getTitletext() {
		return titletext;
	}

	public javax.swing.JLabel getStatusText() {
		return statusText;
	}

	public javax.swing.JButton getMaxViewButton() {
		return maxViewButton;
	}

	public javax.swing.JButton getRevertViewButton() {
		return revertViewButton;
	}

	public javax.swing.JButton getCloseButton() {
		return closeButton;
	}

	public javax.swing.JPanel getTopPanel() {
		return topPanel;
	}

}
