/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WhiteBoardPanel.java
 *
 * Created on 2011-12-28, 14:17:43
 */
package com.lorent.lvmc.ui;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.LayoutManager;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JComponent;
import javax.swing.JInternalFrame;
import javax.swing.border.EmptyBorder;
import javax.swing.plaf.basic.BasicInternalFrameUI;

import org.jhotdraw.samples.svg.SVGPanels;

import com.lorent.lvmc.dto.LoginInfo;
import com.lorent.lvmc.util.DataUtil;
import com.lorent.lvmc.util.LCMUtil;

/**
 *
 * @author Administrator
 */
public class WhiteBoardPanel extends javax.swing.JPanel {

	private final JInternalFrame frame=new JInternalFrame();
    /** Creates new form WhiteBoardPanel */
    public WhiteBoardPanel() {
    	super.setLayout(new BorderLayout());
    	
    	((BasicInternalFrameUI)frame.getUI()).setNorthPane(null);
//    	JComponent component = ((BasicInternalFrameUI)frame.getUI()).getNorthPane();
//    	component.setPreferredSize(new Dimension(0,0));
    	
    	frame.setBorder(new EmptyBorder(0, 0, 0, 0));
    	super.add(frame);
        initComponents();
        frame.setVisible(true);
        frame.revalidate();
    	frame.repaint();
    }
    
    @Override
	public void setLayout(LayoutManager mgr) {
    	if(frame==null){
    		super.setLayout(mgr);
    	}else{
    		frame.getContentPane().setLayout(mgr);
    	}
	}

	@Override
	public Component add(Component comp) {
		return frame.getContentPane().add(comp);
	}

	@Override
	public Component add(String name, Component comp) {
		return frame.getContentPane().add(name, comp);
	}

	@Override
	public Component add(Component comp, int index) {
		return frame.getContentPane().add(comp, index);
	}

	@Override
	public void add(Component comp, Object constraints) {
		frame.getContentPane().add(comp, constraints);
	}

	@Override
	public void add(Component comp, Object constraints, int index) {
		super.add(comp, constraints, index);
	}

	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jTabbedPane1 = new CreatableJTabbedPane();
        add(jTabbedPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
    public javax.swing.JTabbedPane getJTabbedPane1(){
        return jTabbedPane1;
    }
}
